import {useState} from 'react'
import {ActivityIndicator,Pressable,SafeAreaView,StyleSheet,Text,View} from 'react-native'
import {router} from 'expo-router'
import {GoogleSignin} from '@react-native-google-signin/google-signin'
import {nativeGoogle} from '../api'
import {useSession} from '../session'
import {colors} from '../theme'
GoogleSignin.configure({iosClientId:process.env.EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID,webClientId:process.env.EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID,offlineAccess:false})
export default function Login(){const {setUser}=useSession(),[busy,setBusy]=useState(false),[error,setError]=useState('');const enter=async()=>{setBusy(true);setError('');try{await GoogleSignin.hasPlayServices({showPlayServicesUpdateDialog:true});const response=await GoogleSignin.signIn();if(response.type!=='success'||!response.data.idToken)throw new Error('Google no devolvió una identidad válida.');setUser(await nativeGoogle(response.data.idToken));router.replace('/(tabs)/events')}catch(reason){setError(reason instanceof Error?reason.message:'No se pudo iniciar sesión.')}finally{setBusy(false)}};return <SafeAreaView style={styles.page}><View style={styles.panel}><View style={styles.mark}><Text style={styles.markText}>S</Text></View><Text style={styles.title}>SPL</Text><Text style={styles.copy}>Control de eventos, finanzas y nóminas</Text>{error&&<Text accessibilityRole="alert" style={styles.error}>{error}</Text>}<Pressable accessibilityRole="button" disabled={busy} onPress={enter} style={styles.button}>{busy?<ActivityIndicator color="#fff"/>:<Text style={styles.buttonText}>Continuar con Google</Text>}</Pressable></View></SafeAreaView>}
const styles=StyleSheet.create({page:{flex:1,justifyContent:'center',padding:24,backgroundColor:colors.background},panel:{padding:28,borderRadius:18,borderWidth:1,borderColor:colors.border,backgroundColor:colors.panel,alignItems:'center'},mark:{width:52,height:52,borderRadius:14,backgroundColor:colors.orange,alignItems:'center',justifyContent:'center'},markText:{color:'#fff',fontSize:28,fontWeight:'900'},title:{color:colors.text,fontSize:28,fontWeight:'900',marginTop:16},copy:{color:colors.muted,fontSize:15,textAlign:'center',marginTop:6,marginBottom:28},button:{minHeight:50,width:'100%',borderRadius:10,backgroundColor:colors.orange,alignItems:'center',justifyContent:'center'},buttonText:{color:'#fff',fontSize:16,fontWeight:'800'},error:{color:'#fecaca',backgroundColor:'#3b1717',padding:12,borderRadius:8,marginBottom:12,width:'100%'}})
