import { expect, test, type APIRequestContext, type Page } from '@playwright/test'

async function saved(request: APIRequestContext, path: string, data: unknown, method: 'post' | 'put' | 'patch' = 'post') {
  const response = await request[method](path, { data })
  expect(response.ok(), `${method.toUpperCase()} ${path}: ${await response.text()}`).toBe(true)
  return (await response.json()).data
}

async function enter(page: Page) {
  await page.clock.setFixedTime(new Date('2026-09-30T19:00:00Z'))
  await page.goto('/')
  await page.getByRole('button', { name: 'Entrar en modo de pruebas' }).click()
  await expect(page.getByRole('heading', { name: 'Buen día, Oscar' })).toBeVisible()
}

test('business selector keeps its arrow centered inside the input at desktop and phone sizes', async ({ page }, testInfo) => {
  await enter(page)
  for (const [name, width, height] of [['desktop', 1440, 1000], ['phone', 390, 844]] as const) {
    await page.setViewportSize({ width, height })
    if (name === 'phone') {
      await page.locator('.menu-button').click()
      await expect.poll(async () => (await page.locator('.sidebar').boundingBox())?.x).toBe(0)
    }
    const selector = page.getByLabel('Vista de negocio')
    await selector.selectOption('5to Elemento')
    await page.evaluate(() => document.fonts.ready.then(() => undefined))
    const input = await selector.boundingBox()
    const arrow = await page.locator('.scope-control svg').boundingBox()
    const caption = await page.locator('.scope-control label > span').boundingBox()
    expect(input).not.toBeNull()
    expect(arrow).not.toBeNull()
    expect(caption).not.toBeNull()
    await page.screenshot({ path: testInfo.outputPath(`business-selector-${name}.png`) })
    await testInfo.attach(`selector geometry ${name}`, { body: JSON.stringify({ input, arrow, caption }), contentType: 'application/json' })
    expect.soft(arrow!.y, `${name}: arrow below caption`).toBeGreaterThanOrEqual(caption!.y + caption!.height)
    expect.soft(Math.abs(arrow!.y + arrow!.height / 2 - (input!.y + input!.height / 2)), `${name}: centered arrow`).toBeLessThanOrEqual(2)
    expect.soft(arrow!.x + arrow!.width, `${name}: arrow inside input`).toBeLessThanOrEqual(input!.x + input!.width)
    expect.soft(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth), `${name}: no horizontal page overflow`).toBe(true)
  }
})

test('finance uses the shared period for expected results, paid category bars, and its dated income ledger', async ({ page }, testInfo) => {
  await page.clock.setFixedTime(new Date('2026-09-30T19:00:00Z'))
  await page.request.post('/api/auth/test-login')
  const tag = crypto.randomUUID().slice(0, 8)
  const event = await saved(page.request, '/api/events', { businessUnit: '5to Elemento', clientName: `Evento vigente ${tag}`, venue: `Sede agosto ${tag}`, eventDate: '2026-08-19', agreedPrice: '1000.00' })
  const prior = await saved(page.request, '/api/events', { businessUnit: '5to Elemento', clientName: `Evento anterior ${tag}`, venue: `Sede julio ${tag}`, eventDate: '2026-07-31', agreedPrice: '2000.00' })
  const incomes: any[] = []
  const income = async (name: string, amount: string, expectedDate: string, receivedDate: string | null) => {
    const item = await saved(page.request, `/api/direct-income/${crypto.randomUUID()}`, { name: `${name} ${tag}`, amount, expectedDate, receivedDate: receivedDate === expectedDate ? receivedDate : null, businessUnit: '5to Elemento', notes: `Notas ${name}` }, 'put')
    const result = receivedDate && receivedDate !== expectedDate ? await saved(page.request, `/api/direct-income/${item.id}/receive`, { receivedDate, version: item.version }, 'patch') : item
    incomes.push(result)
    return result
  }
  const paid = await income('Utilidad pagada', '150.00', '2026-08-22', '2026-08-22')
  const pending = await income('Utilidad pendiente', '80.00', '2026-08-23', null)
  const moved = await income('Utilidad cobrada tarde', '125.00', '2026-07-30', '2026-08-24')
  const outside = await income('Utilidad cobrada siguiente semana', '60.00', '2026-08-19', '2026-08-26')
  const future = await income('Pendiente siguiente semana', '90.00', '2026-08-25', null)
  for (const [record, amount, date, kind] of [[event, '200.00', '2026-08-18', 'payment'], [prior, '300.00', '2026-08-20', 'payment'], [prior, '25.00', '2026-08-21', 'refund']] as const) {
    await saved(page.request, `/api/events/${record.id}/payments`, { amount, transactionDate: date, kind, idempotencyKey: crypto.randomUUID() })
  }
  const oldExpense = await saved(page.request, `/api/events/${prior.id}/expenses`, { name: `Gasto anterior pagado ahora ${tag}`, category: 'Transporte', amount: '40.00', expenseDate: '2026-07-31' })
  const laterExpense = await saved(page.request, `/api/events/${prior.id}/expenses`, { name: `Gasto anterior pagado después ${tag}`, category: 'Transporte', amount: '70.00', expenseDate: '2026-07-31' })
  const paidPermit = await saved(page.request, `/api/events/${event.id}/expenses`, { name: `Permiso pagado ${tag}`, category: 'Permisos especiales', amount: '50.00', expenseDate: '2026-08-20' })
  await saved(page.request, `/api/events/${event.id}/expenses`, { name: `Permiso pendiente ${tag}`, category: 'Permisos especiales', amount: '50.00', expenseDate: '2026-08-20' })
  const unpaid = await saved(page.request, `/api/events/${event.id}/expenses`, { name: `Material pendiente ${tag}`, category: 'Materiales', amount: '70.00', expenseDate: '2026-08-20' })
  for (const [expense, amount, paymentDate] of [[oldExpense, '40.00', '2026-08-20'], [laterExpense, '70.00', '2026-08-25'], [paidPermit, '50.00', '2026-08-21']] as const) {
    await saved(page.request, `/api/expenses/${expense.id}/settlements`, { amount, paymentDate, idempotencyKey: crypto.randomUUID() })
  }
  await saved(page.request, `/api/quick-expenses/${crypto.randomUUID()}`, { name: `Comida directa ${tag}`, category: 'Alimentos', amount: '25.00', expenseDate: '2026-08-21', businessUnit: '5to Elemento', notes: 'Recibo de agosto', paymentMethod: 'card' }, 'put')
  try {
    await page.goto('/')
    await page.getByLabel('Vista de negocio').selectOption('5to Elemento')
    for (let i = 0; i < 6; i++) await page.getByRole('button', { name: 'Periodo anterior' }).click()
    const period = await page.locator('.dashboard-period-nav strong').textContent()
    expect(period).toMatch(/18.*2026.*24.*2026/)
    await expect(page.locator('.metric-card').filter({ hasText: 'Cobros registrados' })).toContainText('$750.00')
    await expect(page.locator('.metric-card').filter({ hasText: 'Gastos pagados' })).toContainText('$115.00')
    const weeklyChart = page.getByRole('region', { name: 'Gastos y ganancias por semana' })
    const incomingPoint = weeklyChart.getByRole('img', { name: /Entradas \$775\.00/ })
    const profitPoint = weeklyChart.getByRole('img', { name: /Ganancia \$635\.00/ })
    await expect(incomingPoint).toHaveCount(1)
    await expect(profitPoint).toHaveCount(1)
    await incomingPoint.focus()
    await expect(weeklyChart.getByRole('status')).toContainText('Entradas $775.00')
    const incomingColor = await incomingPoint.evaluate(element => getComputedStyle(element).fill)
    const profitColor = await profitPoint.evaluate(element => getComputedStyle(element).fill)
    const green = incomingColor.match(/\d+/g)!.map(Number)
    const white = profitColor.match(/\d+/g)!.map(Number)
    expect(green[1]).toBeGreaterThan(green[0] + 30)
    expect(green[1]).toBeGreaterThan(green[2])
    expect(white.slice(0, 3).every(value => value >= 240)).toBe(true)
    for (const name of ['Ver ocho semanas anteriores', 'Ver ocho semanas siguientes']) {
      const button = weeklyChart.getByRole('button', { name })
      await expect(button.locator('svg')).toHaveCount(1)
      await expect(button).not.toHaveText(/Anterior|Siguiente/)
    }
    await page.getByRole('button', { name: 'Finanzas', exact: true }).click()
    await expect(page.locator('.dashboard-period-nav strong')).toHaveText(period!)
    const summary = page.locator('.finance-summary')
    await expect(summary).toContainText('$1,415.00')
    await expect(summary).toContainText('-$195.00')
    await expect(summary.locator('.finance-total')).toContainText('$1,220.00')
    const detail = page.getByRole('region', { name: 'Detalle de gastos', exact: true })
    await expect(detail.getByRole('combobox', { name: 'Estado', exact: true })).toHaveValue('Pagados')
    await expect(detail).toContainText(oldExpense.name)
    await expect(detail).toContainText(paidPermit.name)
    await expect(detail).not.toContainText(unpaid.name)
    const chart = detail.getByRole('img', { name: 'Gastos por categoría, pagados y pendientes', exact: true })
    for (const category of ['Otros gastos', 'Renta de equipo', 'Compra de equipo', 'Transporte', 'Alimentos', 'Materiales', 'Servicios', 'Permisos especiales']) {
      await expect(chart.getByRole('img', { name: new RegExp(`^${category}:`) })).toHaveCount(1)
    }
    await expect(chart.getByRole('img', { name: /^Transporte:/ })).toHaveAttribute('aria-label', /\$40\.00/)
    await expect(chart.getByRole('img', { name: /^Permisos especiales:/ })).toHaveAttribute('aria-label', /\$50\.00/)
    await expect(chart.getByRole('img', { name: /^Materiales:/ })).toHaveAttribute('aria-label', /\$0\.00/)
    const barColors = await chart.locator('.finance-category-column rect').evaluateAll(elements => elements.map(element => element.getAttribute('fill')!))
    expect(new Set(barColors).size).toBeGreaterThan(1)
    for (const color of barColors) {
      expect(color).toMatch(/^#[a-f\d]{6}$/i)
      const channels = color.slice(1).match(/.{2}/g)!.map(value => parseInt(value, 16))
      expect(channels[0]).toBeGreaterThan(channels[1])
      expect(channels[0]).toBeGreaterThan(channels[2])
    }
    const transportBar = await chart.getByRole('img', { name: /^Transporte:/ }).locator('rect').boundingBox()
    expect(transportBar!.height).toBeGreaterThan(transportBar!.width)
    const toggle = page.getByRole('button', { name: /entradas del periodo/i })
    await expect(toggle).toHaveAttribute('aria-expanded', 'false')
    const panelBox = await summary.boundingBox()
    const toggleBox = await toggle.boundingBox()
    expect(toggleBox!.x + toggleBox!.width / 2).toBeGreaterThan(panelBox!.x + panelBox!.width / 2)
    expect(toggleBox!.y + toggleBox!.height / 2).toBeGreaterThan(panelBox!.y + panelBox!.height / 2)
    await toggle.click()
    await expect(toggle).toHaveAttribute('aria-expanded', 'true')
    const ledger = page.getByRole('region', { name: 'Entradas del periodo' })
    await expect(ledger).toBeVisible()
    await expect(ledger).toContainText(paid.name)
    await expect(ledger).toContainText(pending.name)
    await expect(ledger).toContainText(moved.name)
    await expect(ledger).toContainText(prior.clientName)
    await expect(ledger).toContainText(event.clientName)
    await expect(ledger).toContainText('Reembolso')
    await expect(summary.locator('.finance-cash-result')).toContainText('$750.00')
    await expect(ledger.locator('article').filter({ hasText: outside.name })).toContainText('Pendiente')
    await expect(ledger).not.toContainText(future.name)
    const dates = await ledger.locator('time').evaluateAll(elements => elements.map(element => element.getAttribute('datetime')))
    expect(dates).toEqual(['2026-08-24', '2026-08-23', '2026-08-22', '2026-08-21', '2026-08-20', '2026-08-19', '2026-08-19', '2026-08-18'])
    await page.screenshot({ path: testInfo.outputPath('finance-week-ledger-desktop.png'), fullPage: true })
    for (const [name, width, height] of [['tablet', 820, 1180], ['phone', 390, 844]] as const) {
      await page.setViewportSize({ width, height })
      await expect.poll(async () => { const box = await page.locator('.sidebar').boundingBox(); return box !== null && box.x + box.width <= 0 }).toBe(true)
      await expect(summary.locator('.finance-cash-result')).toContainText('$750.00')
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth), `${name}: no horizontal page overflow`).toBe(true)
      const plot = chart.locator('.finance-category-scroll')
      expect(await plot.evaluate(element => element.scrollWidth > element.clientWidth), `${name}: chart scrolls inside its panel`).toBe(true)
      await page.screenshot({ path: testInfo.outputPath(`finance-week-ledger-${name}.png`), fullPage: true })
      if (name === 'phone') {
        await chart.getByRole('img', { name: /^Permisos especiales:/ }).scrollIntoViewIfNeeded()
        expect(await plot.evaluate(element => element.scrollLeft)).toBeGreaterThan(0)
        await detail.screenshot({ path: testInfo.outputPath('finance-paid-bars-phone.png') })
      }
    }
    await page.setViewportSize({ width: 1440, height: 1000 })
    await detail.getByRole('combobox', { name: 'Estado', exact: true }).selectOption('Pendientes')
    await expect(detail).toContainText(unpaid.name)
    await expect(chart.getByRole('img', { name: /^Materiales:/ })).toHaveAttribute('aria-label', /\$70\.00/)
    await page.getByRole('button', { name: 'Mes', exact: true }).click()
    await expect(summary).toContainText('$1,505.00')
    await expect(summary.locator('.finance-total')).toContainText('$1,310.00')
    await expect(ledger).toContainText(outside.name)
    await expect(ledger).toContainText(future.name)
    await expect(summary.locator('.finance-cash-result')).toContainText('$810.00')
    await toggle.click()
    await expect(toggle).toHaveAttribute('aria-expanded', 'false')
    await expect(ledger).not.toBeVisible()
    await page.getByRole('button', { name: 'Panel general' }).click()
    await expect(page.locator('.dashboard-period-nav strong')).toHaveText(/agosto.*2026/i)
    await expect(page.locator('.metric-card').filter({ hasText: 'Cobros registrados' })).toContainText('$810.00')
    await expect(page.locator('.metric-card').filter({ hasText: 'Gastos pagados' })).toContainText('$185.00')
  } finally {
    for (const record of incomes) await page.request.delete(`/api/direct-income/${record.id}`, { data: { version: record.version } })
    for (const record of [event, prior]) await page.request.delete(`/api/events/${record.id}`, { data: { version: record.version } })
  }
})

test('week and month selection follows both finance pages and survives reload without resetting the date', async ({ page }) => {
  await enter(page)
  const label = page.locator('.dashboard-period-nav strong')
  await expect(label).toContainText('29')
  await page.getByRole('button', { name: 'Periodo anterior' }).click()
  const selectedWeek = await label.textContent()
  await expect(label).toContainText('22')
  await page.getByRole('button', { name: 'Finanzas', exact: true }).click()
  await expect(label).toHaveText(selectedWeek!)
  await page.getByRole('button', { name: 'Mes', exact: true }).click()
  await expect(label).toHaveText(/septiembre.*2026/i)
  await page.getByRole('button', { name: 'Panel general' }).click()
  await expect(page.getByRole('button', { name: 'Mes', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(label).toHaveText(/septiembre.*2026/i)
  await page.getByRole('button', { name: 'Semana', exact: true }).click()
  await expect(label).toHaveText(selectedWeek!)
  await page.getByRole('button', { name: 'Finanzas', exact: true }).click()
  await page.getByRole('button', { name: 'Mes', exact: true }).click()
  await page.getByRole('button', { name: 'Periodo anterior' }).click()
  await expect(label).toHaveText(/agosto.*2026/i)
  await page.getByRole('button', { name: 'Semana', exact: true }).click()
  const augustWeek = await label.textContent()
  expect(augustWeek).toMatch(/28.*2026.*3.*2026/)
  await page.getByRole('button', { name: 'Panel general' }).click()
  await expect(label).toHaveText(augustWeek!)
  await page.reload()
  await expect(label).toHaveText(augustWeek!)
  await expect(page.getByRole('button', { name: 'Semana', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: 'Finanzas', exact: true }).click()
  await expect(label).toHaveText(augustWeek!)
  await page.getByRole('button', { name: 'Mes', exact: true }).click()
  await expect(label).toHaveText(/agosto.*2026/i)
  await page.getByRole('button', { name: 'Periodo anterior' }).click()
  await expect(label).toHaveText(/julio.*2026/i)
  await page.getByRole('button', { name: 'Panel general' }).click()
  await expect(label).toHaveText(/julio.*2026/i)
})
