import { test, expect, type Page } from '@playwright/test'

async function enter(page:Page) {
  await page.goto('/')
  await page.getByRole('button',{name:'Entrar en modo de pruebas'}).click()
  await page.getByRole('button',{name:'Nómina',exact:true}).click()
  await expect(page.getByRole('heading',{name:'Nóminas',exact:true})).toBeVisible()
}
async function addPerson(page:Page,name:string,base:string) {
  await page.getByRole('button',{name:'Agregar trabajador',exact:true}).click()
  await page.getByRole('textbox',{name:'Buscar o crear trabajador'}).fill(name)
  await page.getByRole('button',{name:`Crear y agregar «${name}»`}).click()
  await page.getByRole('spinbutton',{name:`Base ${name}`,exact:true}).fill(base)
}

test('real server: team, optional expenses, persistence, full payment, reversal and templates',async({page})=>{
  const suffix=Date.now(),andrea='Andrea López',luis='Luis Torres'
  await enter(page)
  await page.getByRole('button',{name:'Nueva nómina',exact:true}).click()
  await expect(page.getByRole('button',{name:'Guardar borrador'})).toHaveCount(0)
  await addPerson(page,andrea,'1000.10');await addPerson(page,luis,'750.20')
  await page.getByRole('spinbutton',{name:`Deducciones ${andrea}`,exact:true}).fill('50.05')
  await page.getByRole('button',{name:'Agregar gasto',exact:true}).click()
  await page.getByRole('textbox',{name:'Concepto del gasto 1'}).fill('Transporte del equipo')
  await page.getByRole('spinbutton',{name:'Importe del gasto 1'}).fill('200.25')
  await expect(page.locator('.pr-grand-total strong')).toHaveText('$1,900.50')
  await page.getByRole('button',{name:'Guardar nómina',exact:true}).click()
  await expect(page.getByRole('status')).toContainText('Nómina guardada')
  await page.screenshot({path:'../outputs/payroll-v2-desktop.png',fullPage:true})
  await page.reload();await page.getByRole('button',{name:'Nómina',exact:true}).click()
  await page.locator('.pr-batch').filter({hasText:'$1,900.50'}).click()
  await expect(page.getByRole('spinbutton',{name:`Base ${andrea}`,exact:true})).toHaveValue('1000.10')
  await expect(page.getByRole('button',{name:'Pagar saldo completo'})).toHaveCount(0)
  await page.getByRole('button',{name:'Registrar pago completo',exact:true}).click()
  const dialog=page.getByRole('dialog')
  await dialog.getByLabel('Fecha de pago').fill('2026-09-20')
  await dialog.getByRole('button',{name:'Confirmar pago completo'}).click()
  await expect(page.locator('.pr-summary .pr-status')).toHaveText('Pagada')
  await expect(page.getByRole('spinbutton',{name:`Base ${andrea}`,exact:true})).toBeDisabled()
  await page.reload();await page.getByRole('button',{name:'Nómina',exact:true}).click()
  await page.locator('.pr-batch').filter({hasText:'$1,900.50'}).click()
  await expect(page.locator('.pr-summary .pr-status')).toHaveText('Pagada')
  await page.getByRole('button',{name:'Revertir registro de pago'}).click()
  await dialog.getByLabel('Motivo de la reversión').fill('La fecha registrada fue incorrecta')
  await dialog.getByRole('button',{name:'Confirmar reversión'}).click()
  await expect(page.locator('.pr-summary .pr-status')).toHaveText('No pagada')
  await page.getByRole('button',{name:'Crear plantilla con este equipo'}).click()
  await page.getByLabel('Nombre de plantilla').fill(`Equipo ${suffix}`)
  await page.getByLabel('Usar como predeterminada').check()
  await page.getByRole('button',{name:'Guardar plantilla',exact:true}).click()
  await expect(page.locator('.pr-template').filter({hasText:`Equipo ${suffix}`})).toContainText('Predeterminada')
  await page.getByRole('button',{name:'Nueva nómina',exact:true}).click()
  await expect(page.getByRole('spinbutton',{name:`Base ${andrea}`,exact:true})).toHaveValue('1000.10')
  await expect(page.getByRole('textbox',{name:'Concepto del gasto 1'})).toHaveCount(0)
  await page.getByRole('spinbutton',{name:`Base ${andrea}`,exact:true}).fill('1200')
  await page.getByRole('button',{name:'Guardar nómina',exact:true}).click()
  await expect(page.getByRole('status')).toContainText('Nómina guardada')
  await page.getByRole('button',{name:'Volver a nóminas'}).click()
  await page.getByRole('button',{name:'Plantillas',exact:true}).click()
  await page.locator('.pr-template').filter({hasText:`Equipo ${suffix}`}).getByRole('button',{name:'Editar plantilla'}).click()
  await expect(page.getByRole('spinbutton',{name:`Base ${andrea}`,exact:true})).toHaveValue('1000.10')
})

for(const width of [1440,820,390]) test(`usable payroll layout at ${width}px`,async({page})=>{
  await page.setViewportSize({width,height:1000})
  await page.goto('/');await page.getByRole('button',{name:'Entrar en modo de pruebas'}).click()
  if(width<1100)await page.locator('.menu-button').click()
  await page.getByRole('button',{name:'Nómina',exact:true}).click()
  await page.getByRole('button',{name:'Nueva nómina',exact:true}).click()
  const name=`Trabajador visual ${width} ${Date.now()}`
  await addPerson(page,name,'1800.50')
  await page.getByRole('button',{name:'Agregar gasto',exact:true}).click()
  await page.getByRole('textbox',{name:'Concepto del gasto 1'}).fill('Alimentos')
  await page.getByRole('spinbutton',{name:'Importe del gasto 1'}).fill('250')
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true)
  await expect(page.getByRole('button',{name:'Guardar nómina',exact:true})).toBeEnabled()
  await page.screenshot({path:`../outputs/payroll-v2-${width}.png`,fullPage:true})
})

test('preserves capture on server rejection and supports keyboard interaction',async({page})=>{
  await enter(page);await page.getByRole('button',{name:'Nueva nómina',exact:true}).click()
  const name=`Validación ${Date.now()}`;await addPerson(page,name,'100')
  await page.getByRole('spinbutton',{name:`Deducciones ${name}`,exact:true}).fill('200')
  await page.getByRole('button',{name:'Guardar nómina',exact:true}).click()
  await expect(page.locator('.pr-alert')).toContainText('deducciones')
  await page.getByRole('spinbutton',{name:`Deducciones ${name}`,exact:true}).fill('0')
  await page.route('**/api/weekly-payroll/*',route=>route.fulfill({status:503,json:{error:'unavailable'}}))
  await page.getByRole('button',{name:'Guardar nómina',exact:true}).click()
  await expect(page.locator('.pr-alert')).toBeVisible()
  await expect(page.getByRole('spinbutton',{name:`Base ${name}`,exact:true})).toHaveValue('100')
  await page.getByRole('button',{name:'Volver a nóminas'}).focus();await page.keyboard.press('Enter')
  await expect(page.getByRole('dialog')).toBeVisible();await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).not.toBeVisible()
})

test('real server: event allocations and payroll expenses reconcile without duplicate charges',async({page})=>{
  await enter(page)
  const response=await page.request.post('/api/events',{data:{businessUnit:'SPL',clientName:'Cliente nómina',venue:'Salón nómina',eventDate:'2026-09-20',operationalStatus:'Confirmado',payrollBudget:'5000.00',extraExpenseBudget:'1000.00',agreedPrice:'10000.00'}})
  expect(response.status()).toBe(201);const event=(await response.json()).data
  await page.reload();await page.getByRole('button',{name:'Nómina',exact:true}).click()
  await page.getByRole('button',{name:'Nueva nómina',exact:true}).click()
  await page.getByRole('combobox',{name:'Plantilla',exact:true}).selectOption('')
  const name=`Distribución ${Date.now()}`;await addPerson(page,name,'1000')
  const row=page.locator('.pr-worker').filter({hasText:name})
  await row.locator('summary').click()
  await row.getByRole('button',{name:'Dividir en otro destino'}).click()
  await page.getByLabel(`Distribución ${name} 1`,{exact:true}).fill('400')
  await page.getByLabel(`Destino ${name} 2`,{exact:true}).selectOption(event.id)
  await page.getByLabel(`Distribución ${name} 2`,{exact:true}).fill('600')
  await page.getByRole('button',{name:'Agregar gasto',exact:true}).click()
  await page.getByLabel('Concepto del gasto 1').fill('Transporte asignado')
  await page.getByLabel('Importe del gasto 1').fill('150')
  await page.getByLabel('Destino del gasto 1').selectOption(event.id)
  await page.getByRole('button',{name:'Guardar nómina',exact:true}).click()
  await expect(page.getByRole('status')).toContainText('guardada')
  await page.getByRole('button',{name:'Eventos',exact:true}).click()
  await page.locator('.event-table-row').filter({hasText:'Salón nómina'}).click()
  await expect(page.locator('.cost-summary').getByText('$600.00',{exact:true})).toBeVisible()
  await expect(page.locator('.expense-detail-list')).toContainText('Transporte asignado')
  await expect(page.locator('.expense-detail-list')).toContainText('Gasto originado en nómina')
  await expect(page.locator('.expense-detail-list').getByRole('button',{name:'Marcar como pagado'})).toHaveCount(0)
  const expenses=(await (await page.request.get(`/api/events/${event.id}/expenses`)).json()).data
  expect(expenses).toHaveLength(1);expect(expenses[0].amount).toBe('150.00')
})
