import { beforeEach, describe, expect, it } from 'vitest'
import type { FastifyRequest } from 'fastify'
import { buildApp } from './app.js'
import type { Authenticator } from './auth.js'
import type { CreateEvent, CreateExpense, CreatePayment, CreateSettlement, EventRecord, Principal } from './domain.js'
import type { EventRepository, ExpenseRecord, PaymentRecord, SettlementRecord } from './repository.js'
import { FinancialConflictError } from './repository.js'

const owner: Principal = { userId:'owner-1',role:'owner',unit:null }
const coordinator: Principal = { userId:'coord-1',role:'coordinator',unit:'5to Elemento' }
const baseEvents: EventRecord[] = [
  {id:'11111111-1111-4111-8111-111111111111',businessUnit:'SPL',clientName:'Cliente SPL',clientPhone:null,venue:'Lugar SPL',eventDate:'2026-10-01',operationalStatus:'Confirmado',operationalNotes:null,financialNotes:'Margen reservado',agreedPrice:'100000.00',payrollBudget:'20000.00',extraExpenseBudget:'10000.00',version:1,createdAt:'2026-09-14T00:00:00.000Z',updatedAt:'2026-09-14T00:00:00.000Z'},
  {id:'22222222-2222-4222-8222-222222222222',businessUnit:'5to Elemento',clientName:'Cliente 5to',clientPhone:'555-0100',venue:'Lugar 5to',eventDate:'2026-10-02',operationalStatus:'Pendiente',operationalNotes:'Acceso por puerta norte',financialNotes:'No revelar',agreedPrice:'80000.00',payrollBudget:'15000.00',extraExpenseBudget:'9000.00',version:1,createdAt:'2026-09-14T00:00:00.000Z',updatedAt:'2026-09-14T00:00:00.000Z'},
]

class MemoryRepository implements EventRepository {
  events = structuredClone(baseEvents)
  expenses: ExpenseRecord[] = []
  payments: PaymentRecord[] = []
  settlements:SettlementRecord[]=[]
  async list(principal: Principal) { return this.events.filter(event => principal.role === 'owner' || event.businessUnit === principal.unit) }
  async findById(id: string, principal: Principal) { return this.events.find(event => event.id === id && (principal.role === 'owner' || event.businessUnit === principal.unit)) ?? null }
  async create(input: CreateEvent, principal: Principal) {
    const ownerInput = principal.role === 'owner' ? input as Record<string,unknown> : {}
    const event: EventRecord = {id:crypto.randomUUID(),businessUnit:input.businessUnit,clientName:input.clientName,clientPhone:input.clientPhone??null,venue:input.venue,eventDate:input.eventDate,operationalStatus:input.operationalStatus,operationalNotes:input.operationalNotes??null,financialNotes:ownerInput.financialNotes as string??null,agreedPrice:ownerInput.agreedPrice as string??null,payrollBudget:ownerInput.payrollBudget as string??'0.00',extraExpenseBudget:ownerInput.extraExpenseBudget as string??'0.00',version:1,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}
    this.events.push(event); return event
  }
  async updatePayrollBudget(id:string,payrollBudget:string,principal:Principal){const event=await this.findById(id,principal);if(!event)return null;event.payrollBudget=payrollBudget;event.version++;return event}
  async addExpense(eventId: string, input: CreateExpense, _principal: Principal) { if(!this.events.some(event=>event.id===eventId))return null; const expense={...input,id:crypto.randomUUID(),eventId,paidAmount:'0.00',version:1};this.expenses.push(expense);return expense }
  async listExpenses(eventId: string) { return this.events.some(event=>event.id===eventId) ? this.expenses.filter(expense=>expense.eventId===eventId) : null }
  async addPayment(eventId:string,input:CreatePayment){if(!this.events.some(event=>event.id===eventId))return null;const existing=this.payments.find(payment=>payment.idempotencyKey===input.idempotencyKey&&payment.eventId===eventId);if(existing)return existing;const payment={...input,id:crypto.randomUUID(),eventId,createdAt:new Date().toISOString()};this.payments.push(payment);return payment}
  async listPayments(eventId:string){return this.events.some(event=>event.id===eventId)?this.payments.filter(payment=>payment.eventId===eventId):null}
  async addSettlement(expenseId:string,input:CreateSettlement){const expense=this.expenses.find(item=>item.id===expenseId);if(!expense)return null;const existing=this.settlements.find(item=>item.expenseId===expenseId&&item.idempotencyKey===input.idempotencyKey);if(existing)return existing;const pending=Number(expense.amount)-Number(expense.paidAmount);if(Math.abs(Number(input.amount)-pending)>.005)throw new FinancialConflictError('full payment required');expense.paidAmount=Number(expense.amount).toFixed(2);const settlement={...input,id:crypto.randomUUID(),expenseId,createdAt:new Date().toISOString(),paidAmount:expense.paidAmount};this.settlements.push(settlement);return settlement}
  async listSettlements(){return this.settlements}
}

function auth(): Authenticator { return async (request: FastifyRequest) => request.headers.authorization === 'Bearer owner' ? owner : request.headers.authorization === 'Bearer coordinator' ? coordinator : null }
const headers = (token: 'owner'|'coordinator') => ({ authorization:`Bearer ${token}`,'content-type':'application/json' })
const ownerPayload = {businessUnit:'SPL',clientName:'Ana García',clientPhone:null,venue:'Jardín Central',eventDate:'2026-11-07',operationalStatus:'Pendiente',operationalNotes:null,financialNotes:'Anticipo por confirmar',agreedPrice:'125000.25',payrollBudget:'20000.00',extraExpenseBudget:'10000.00'}

describe('event API', () => {
  it('leaves non-API routes available for the desktop frontend while protecting APIs',async()=>{const app=buildApp(new MemoryRepository(),async()=>null);expect((await app.inject({method:'GET',url:'/desktop-shell'})).statusCode).toBe(404);expect((await app.inject({method:'GET',url:'/api/events'})).statusCode).toBe(401);await app.close()})
  let repo: MemoryRepository
  beforeEach(()=>{repo=new MemoryRepository()})
  it('creates an owner event with exact decimal values', async()=>{const app=buildApp(repo,auth());const response=await app.inject({method:'POST',url:'/api/events',headers:headers('owner'),payload:ownerPayload});expect(response.statusCode).toBe(201);expect(response.json().data.agreedPrice).toBe('125000.25');expect(repo.events).toHaveLength(3);await app.close()})
  it('supports a pending price and zero budgets', async()=>{const app=buildApp(repo,auth());const response=await app.inject({method:'POST',url:'/api/events',headers:headers('owner'),payload:{...ownerPayload,agreedPrice:null,payrollBudget:'0.00',extraExpenseBudget:'0'}});expect(response.statusCode).toBe(201);expect(response.json().data.agreedPrice).toBeNull();await app.close()})
  it('updates a payroll budget after creation and rejects coordinator or attack payloads',async()=>{const app=buildApp(repo,auth());const url=`/api/events/${baseEvents[0].id}/budget`;const updated=await app.inject({method:'PATCH',url,headers:headers('owner'),payload:{payrollBudget:'45000.00'}});expect(updated.statusCode).toBe(200);expect(updated.json().data.payrollBudget).toBe('45000.00');expect((await app.inject({method:'PATCH',url,headers:headers('coordinator'),payload:{payrollBudget:'1.00'}})).statusCode).toBe(403);for(const payload of [{payrollBudget:'-1.00'},{payrollBudget:'1.001'},{payrollBudget:'1.00',role:'admin'}])expect((await app.inject({method:'PATCH',url,headers:headers('owner'),payload})).statusCode).toBe(400);await app.close()})
  it('rejects malformed and out-of-range money', async()=>{const app=buildApp(repo,auth());for(const value of ['-1.00','0.001','NaN','9999999999999.00']){const response=await app.inject({method:'POST',url:'/api/events',headers:headers('owner'),payload:{...ownerPayload,agreedPrice:value}});expect(response.statusCode).toBe(400)}await app.close()})
  it('requires authentication without disclosing internals', async()=>{const app=buildApp(repo,auth());const response=await app.inject({method:'GET',url:'/api/events'});expect(response.statusCode).toBe(401);expect(response.json()).toEqual({error:'No autorizado'});await app.close()})
  it('scopes coordinator lists and strips every financial field', async()=>{const app=buildApp(repo,auth());const response=await app.inject({method:'GET',url:'/api/events',headers:headers('coordinator')});const body=response.json();expect(body.data).toHaveLength(1);expect(body.data[0].businessUnit).toBe('5to Elemento');for(const field of ['financialNotes','agreedPrice','payrollBudget','extraExpenseBudget','createdAt'])expect(body.data[0]).not.toHaveProperty(field);await app.close()})
  it('returns not found instead of revealing an SPL event to a coordinator', async()=>{const app=buildApp(repo,auth());const response=await app.inject({method:'GET',url:`/api/events/${baseEvents[0].id}`,headers:headers('coordinator')});expect(response.statusCode).toBe(404);expect(response.body).not.toContain('SPL');await app.close()})
  it('blocks coordinator mass assignment and cross-unit creation', async()=>{const app=buildApp(repo,auth());for(const payload of [{businessUnit:'5to Elemento',clientName:'Ataque',venue:'Lugar',eventDate:'2026-11-07',agreedPrice:'1.00'},{businessUnit:'SPL',clientName:'Ataque',venue:'Lugar',eventDate:'2026-11-07'}]){const response=await app.inject({method:'POST',url:'/api/events',headers:headers('coordinator'),payload});expect(response.statusCode).toBe(400)}expect(repo.events).toHaveLength(2);await app.close()})
  it('treats SQL and script payloads as data and rejects prototype fields', async()=>{const app=buildApp(repo,auth());const injection="' OR 1=1; DROP TABLE events; --";const lookup=await app.inject({method:'GET',url:`/api/events/${encodeURIComponent(injection)}`,headers:headers('owner')});expect(lookup.statusCode).toBe(404);const script='<script>fetch("https://attacker.invalid")</script>';const created=await app.inject({method:'POST',url:'/api/events',headers:headers('owner'),payload:{...ownerPayload,clientName:script}});expect(created.statusCode).toBe(201);expect(created.json().data.clientName).toBe(script);const polluted=await app.inject({method:'POST',url:'/api/events',headers:headers('owner'),payload:{...ownerPayload,__protoAdmin:true}});expect(polluted.statusCode).toBe(400);await app.close()})
  it('rejects malformed JSON and oversized bodies safely', async()=>{const app=buildApp(repo,auth());const malformed=await app.inject({method:'POST',url:'/api/events',headers:headers('owner'),payload:'{"clientName":'});expect(malformed.statusCode).toBe(400);const oversized=await app.inject({method:'POST',url:'/api/events',headers:headers('owner'),payload:{...ownerPayload,operationalNotes:'x'.repeat(40000)}});expect(oversized.statusCode).toBe(413);await app.close()})
  it('allows only owners to add an itemized expense', async()=>{const app=buildApp(repo,auth());const payload={name:'Cableado',category:'Renta',expenseDate:'2026-10-01',amount:'800.50'};const denied=await app.inject({method:'POST',url:`/api/events/${baseEvents[1].id}/expenses`,headers:headers('coordinator'),payload});expect(denied.statusCode).toBe(403);const created=await app.inject({method:'POST',url:`/api/events/${baseEvents[0].id}/expenses`,headers:headers('owner'),payload});expect(created.statusCode).toBe(201);expect(created.json().data.amount).toBe('800.50');await app.close()})
  it('lists itemized expenses only for owners and existing visible events',async()=>{const app=buildApp(repo,auth());await repo.addExpense(baseEvents[0].id,{name:'Cableado',category:'Renta',expenseDate:'2026-10-01',amount:'800.50'},owner);const denied=await app.inject({method:'GET',url:`/api/events/${baseEvents[1].id}/expenses`,headers:headers('coordinator')});expect(denied.statusCode).toBe(403);const found=await app.inject({method:'GET',url:`/api/events/${baseEvents[0].id}/expenses`,headers:headers('owner')});expect(found.statusCode).toBe(200);expect(found.json().data).toHaveLength(1);const missing=await app.inject({method:'GET',url:'/api/events/not-found/expenses',headers:headers('owner')});expect(missing.statusCode).toBe(404);await app.close()})
  it('records partial payments without duplicating retried submissions',async()=>{const app=buildApp(repo,auth());const payload={transactionDate:'2026-10-01',amount:'25000.50',kind:'payment',idempotencyKey:'123e4567-e89b-42d3-a456-426614174000'};const first=await app.inject({method:'POST',url:`/api/events/${baseEvents[0].id}/payments`,headers:headers('owner'),payload});const duplicate=await app.inject({method:'POST',url:`/api/events/${baseEvents[0].id}/payments`,headers:headers('owner'),payload});expect(first.statusCode).toBe(201);expect(duplicate.json().data.id).toBe(first.json().data.id);expect(repo.payments).toHaveLength(1);await app.close()})
  it('supports refunds and rejects coordinator access and hostile payment payloads',async()=>{const app=buildApp(repo,auth());const base={transactionDate:'2026-10-01',amount:'100.00',kind:'refund',idempotencyKey:'123e4567-e89b-42d3-a456-426614174001'};expect((await app.inject({method:'POST',url:`/api/events/${baseEvents[0].id}/payments`,headers:headers('owner'),payload:base})).statusCode).toBe(201);expect((await app.inject({method:'GET',url:`/api/events/${baseEvents[1].id}/payments`,headers:headers('coordinator')})).statusCode).toBe(403);for(const payload of [{...base,amount:'0.00'},{...base,amount:"1; DROP TABLE users"},{...base,kind:'chargeback'},{...base,admin:true}])expect((await app.inject({method:'POST',url:`/api/events/${baseEvents[0].id}/payments`,headers:headers('owner'),payload})).statusCode).toBe(400);await app.close()})
  it('settles an expense only in full without counting a retried payment twice',async()=>{const app=buildApp(repo,auth());const expense=await repo.addExpense(baseEvents[0].id,{name:'Audio',category:'Renta',expenseDate:'2026-10-01',amount:'1000.00'},owner);const first={paymentDate:'2026-10-02',amount:'1000.00',idempotencyKey:'123e4567-e89b-42d3-a456-426614174010'};const one=await app.inject({method:'POST',url:`/api/expenses/${expense!.id}/settlements`,headers:headers('owner'),payload:first});const retry=await app.inject({method:'POST',url:`/api/expenses/${expense!.id}/settlements`,headers:headers('owner'),payload:first});expect(one.json().data.paidAmount).toBe('1000.00');expect(retry.json().data.id).toBe(one.json().data.id);expect(repo.settlements).toHaveLength(1);await app.close()})
  it('rejects partial or excessive expense payment, coordinator access, malformed money, and mass assignment',async()=>{const app=buildApp(repo,auth());const expense=await repo.addExpense(baseEvents[0].id,{name:'Audio',category:'Renta',expenseDate:'2026-10-01',amount:'500.00'},owner);const base={paymentDate:'2026-10-02',amount:'600.00',idempotencyKey:'123e4567-e89b-42d3-a456-426614174011'};expect((await app.inject({method:'POST',url:`/api/expenses/${expense!.id}/settlements`,headers:headers('owner'),payload:base})).statusCode).toBe(409);expect((await app.inject({method:'POST',url:`/api/expenses/${expense!.id}/settlements`,headers:headers('owner'),payload:{...base,amount:'100.00'}})).statusCode).toBe(409);expect((await app.inject({method:'POST',url:`/api/expenses/${expense!.id}/settlements`,headers:headers('coordinator'),payload:{...base,amount:'500.00'}})).statusCode).toBe(403);for(const payload of [{...base,amount:'0'},{...base,amount:'0.001'},{...base,amount:'500.00',role:'admin'}])expect((await app.inject({method:'POST',url:`/api/expenses/${expense!.id}/settlements`,headers:headers('owner'),payload})).statusCode).toBe(400);await app.close()})
})
