import { afterEach, beforeAll, beforeEach, describe, expect, it } from 'vitest'
import { buildApp } from './app.js'
import { sessionAuthenticator, SESSION_COOKIE } from './auth.js'
import { hashPassword } from './password.js'
import type { LoginUser, SessionStore } from './sessions.js'
import type { EventRepository } from './repository.js'

let passwordHash=''
beforeAll(async()=>{passwordHash=await hashPassword('Correct-Horse-2026')})

class MemorySessions implements SessionStore {
  users:LoginUser[]=[{id:'user-1',email:'owner@spl.test',displayName:'Oscar García',role:'owner',businessUnit:null,passwordHash:'',active:true}]
  sessions=new Map<string,{userId:string;expiresAt:Date;revoked:boolean}>()
  async findUserByEmail(email:string){return this.users.find(user=>user.email===email)??null}
  async createSession(userId:string,tokenHash:string,expiresAt:Date){this.sessions.set(tokenHash,{userId,expiresAt,revoked:false})}
  async findPrincipal(tokenHash:string,now:Date){const session=this.sessions.get(tokenHash),user=session&&this.users.find(item=>item.id===session.userId);if(!session||session.revoked||session.expiresAt<=now||!user?.active)return null;return {userId:user.id,email:user.email,displayName:user.displayName,role:user.role,unit:user.businessUnit}}
  async revokeSession(tokenHash:string){const session=this.sessions.get(tokenHash);if(session)session.revoked=true}
  async findOrCreateGoogleUser(email:string,displayName:string,role:LoginUser['role'],businessUnit:LoginUser['businessUnit']){let user=this.users.find(item=>item.email===email);if(!user){user={id:`user-${this.users.length+1}`,email,displayName,role,businessUnit,passwordHash:null,active:true};this.users.push(user)}return user}
}
const emptyRepo={list:async()=>[],findById:async()=>null,create:async()=>{throw new Error('unused')},updatePayrollBudget:async()=>null,addExpense:async()=>null,listExpenses:async()=>null,addPayment:async()=>null,listPayments:async()=>null,addSettlement:async()=>null,listSettlements:async()=>[]} as EventRepository
const firstCookie=(value:string|string[]|undefined)=>(Array.isArray(value)?value[0]:value??'').split(';')[0]

describe('session authentication',()=>{
  let store:MemorySessions
  beforeEach(()=>{store=new MemorySessions();store.users[0].passwordHash=passwordHash})
  afterEach(()=>{delete process.env.NODE_ENV;delete process.env.SPL_DESKTOP;delete process.env.SPL_ALLOW_TEST_LOGIN;delete process.env.ADMIN_EMAIL;delete process.env.GOOGLE_ALLOWED_EMAILS})
  it('logs in with a protected session cookie and returns the current user',async()=>{const app=buildApp(emptyRepo,sessionAuthenticator(store),store);const login=await app.inject({method:'POST',url:'/api/auth/login',payload:{email:'OWNER@SPL.TEST',password:'Correct-Horse-2026'}});expect(login.statusCode).toBe(200);const cookie=login.headers['set-cookie'];expect(cookie).toContain(`${SESSION_COOKIE}=`);expect(cookie).toContain('HttpOnly');expect(cookie).toContain('SameSite=Strict');expect(cookie).toContain('Path=/');const me=await app.inject({method:'GET',url:'/api/auth/me',headers:{cookie:firstCookie(cookie)}});expect(me.json().data).toMatchObject({role:'owner',displayName:'Oscar García'});await app.close()})
  it('uses a Secure cookie in production',async()=>{process.env.NODE_ENV='production';const app=buildApp(emptyRepo,sessionAuthenticator(store),store);const response=await app.inject({method:'POST',url:'/api/auth/login',payload:{email:'owner@spl.test',password:'Correct-Horse-2026'}});expect(response.headers['set-cookie']).toContain('Secure');await app.close()})
  it('keeps the loopback desktop cookie usable without weakening remote production',async()=>{process.env.NODE_ENV='production';process.env.SPL_DESKTOP='1';const app=buildApp(emptyRepo,sessionAuthenticator(store),store);const response=await app.inject({method:'POST',url:'/api/auth/login',payload:{email:'owner@spl.test',password:'Correct-Horse-2026'}});expect(response.headers['set-cookie']).not.toContain('Secure');expect(response.headers['set-cookie']).toContain('SameSite=Strict');await app.close()})
  it('returns the same error for an unknown user and wrong password',async()=>{const app=buildApp(emptyRepo,sessionAuthenticator(store),store);const unknown=await app.inject({method:'POST',url:'/api/auth/login',payload:{email:'nobody@spl.test',password:'Wrong-Pass-2026'}});const wrong=await app.inject({method:'POST',url:'/api/auth/login',payload:{email:'owner@spl.test',password:'Wrong-Pass-2026'}});expect(unknown.statusCode).toBe(401);expect(wrong.statusCode).toBe(401);expect(unknown.body).toBe(wrong.body);await app.close()})
  it('rejects forged, expired, and revoked sessions',async()=>{const app=buildApp(emptyRepo,sessionAuthenticator(store),store);expect((await app.inject({method:'GET',url:'/api/auth/me',headers:{cookie:`${SESSION_COOKIE}=forged`}})).statusCode).toBe(401);const login=await app.inject({method:'POST',url:'/api/auth/login',payload:{email:'owner@spl.test',password:'Correct-Horse-2026'}});const cookie=firstCookie(login.headers['set-cookie']);for(const session of store.sessions.values())session.expiresAt=new Date(0);expect((await app.inject({method:'GET',url:'/api/auth/me',headers:{cookie}})).statusCode).toBe(401);await app.close()})
  it('revokes the session on logout and clears the cookie',async()=>{const app=buildApp(emptyRepo,sessionAuthenticator(store),store);const login=await app.inject({method:'POST',url:'/api/auth/login',payload:{email:'owner@spl.test',password:'Correct-Horse-2026'}});const cookie=firstCookie(login.headers['set-cookie']);const logout=await app.inject({method:'POST',url:'/api/auth/logout',headers:{cookie}});expect(logout.statusCode).toBe(204);expect(logout.headers['set-cookie']).toContain(`${SESSION_COOKIE}=;`);expect((await app.inject({method:'GET',url:'/api/auth/me',headers:{cookie}})).statusCode).toBe(401);await app.close()})
  it('rejects mass assignment, malformed emails, oversized passwords, and brute force',async()=>{const app=buildApp(emptyRepo,sessionAuthenticator(store),store);for(const payload of [{email:'owner@spl.test',password:'Correct-Horse-2026',role:'owner'},{email:"' OR 1=1 --",password:'Wrong-Pass-2026'},{email:'owner@spl.test',password:'x'.repeat(500)}])expect((await app.inject({method:'POST',url:'/api/auth/login',payload})).statusCode).toBe(400);for(let index=0;index<5;index++)await app.inject({method:'POST',url:'/api/auth/login',payload:{email:'owner@spl.test',password:'Wrong-Pass-2026'}});expect((await app.inject({method:'POST',url:'/api/auth/login',payload:{email:'owner@spl.test',password:'Wrong-Pass-2026'}})).statusCode).toBe(429);await app.close()})
  it('creates the allowlisted Google administrator with a persistent session',async()=>{process.env.ADMIN_EMAIL='omendivilg@gmail.com';process.env.GOOGLE_ALLOWED_EMAILS='omendivilg@gmail.com';const verify=async()=>({email:'OMENDIVILG@gmail.com',name:'Oscar Méndez',emailVerified:true});const app=buildApp(emptyRepo,sessionAuthenticator(store),store,verify);const response=await app.inject({method:'POST',url:'/api/auth/google',payload:{credential:'x'.repeat(120)}});expect(response.statusCode).toBe(200);expect(response.json().data).toMatchObject({email:'omendivilg@gmail.com',role:'admin'});expect(response.headers['set-cookie']).toContain('Max-Age=15552000');await app.close()})
  it('rejects unapproved, unverified, malformed, and oversized Google credentials',async()=>{process.env.ADMIN_EMAIL='omendivilg@gmail.com';process.env.GOOGLE_ALLOWED_EMAILS='omendivilg@gmail.com';const app=buildApp(emptyRepo,sessionAuthenticator(store),store,async token=>({email:token.startsWith('u')?'omendivilg@gmail.com':'attacker@example.com',name:'<img src=x onerror=alert(1)>',emailVerified:!token.startsWith('u')}));for(const credential of ['short','x'.repeat(10001)])expect((await app.inject({method:'POST',url:'/api/auth/google',payload:{credential}})).statusCode).toBe(400);expect((await app.inject({method:'POST',url:'/api/auth/google',payload:{credential:'a'.repeat(120)}})).statusCode).toBe(403);expect((await app.inject({method:'POST',url:'/api/auth/google',payload:{credential:'u'.repeat(120)}})).statusCode).toBe(401);await app.close()})
  it('creates a local administrator session through the explicit test mode',async()=>{process.env.SPL_ALLOW_TEST_LOGIN='1';process.env.ADMIN_EMAIL='omendivilg@gmail.com';const app=buildApp(emptyRepo,sessionAuthenticator(store),store);expect((await app.inject('/api/auth/test-login/config')).json()).toEqual({data:{enabled:true}});const response=await app.inject({method:'POST',url:'/api/auth/test-login',payload:{role:'coordinator',email:'attacker@example.com'}});expect(response.statusCode).toBe(200);expect(response.json().data).toMatchObject({email:'omendivilg@gmail.com',role:'admin'});expect(response.headers['set-cookie']).toContain(`${SESSION_COOKIE}=`);await app.close()})
  it('keeps test login disabled on a remote production server even when the flag is present',async()=>{process.env.NODE_ENV='production';process.env.SPL_ALLOW_TEST_LOGIN='1';const app=buildApp(emptyRepo,sessionAuthenticator(store),store);expect((await app.inject('/api/auth/test-login/config')).json()).toEqual({data:{enabled:false}});expect((await app.inject({method:'POST',url:'/api/auth/test-login'})).statusCode).toBe(404);expect(store.sessions.size).toBe(0);await app.close()})

  it('issues and revokes a bearer session for a native Google client',async()=>{process.env.GOOGLE_ALLOWED_EMAILS='owner@spl.mx';process.env.ADMIN_EMAIL='owner@spl.mx';const app=buildApp(emptyRepo,sessionAuthenticator(store),store,async()=>({email:'owner@spl.mx',name:'Owner',emailVerified:true}));const login=await app.inject({method:'POST',url:'/api/auth/google/native',payload:{credential:'x'.repeat(120)}});expect(login.statusCode).toBe(200);const token=login.json().data.token;expect(token).toMatch(/^[A-Za-z0-9_-]{43}$/);expect((await app.inject({url:'/api/auth/me',headers:{authorization:`Bearer ${token}`}})).statusCode).toBe(200);expect((await app.inject({method:'POST',url:'/api/auth/logout',headers:{authorization:`Bearer ${token}`}})).statusCode).toBe(204);expect((await app.inject({url:'/api/auth/me',headers:{authorization:`Bearer ${token}`}})).statusCode).toBe(401);await app.close()})
})
