import {describe,it,expect,vi} from 'vitest'
import {buildRemoteDesktop,centralOrigin} from './desktop-remote.js'

const host='127.0.0.1:43123',apiUrl='https://spl-crm.fly.dev',redirectBase=`http://${host}`
describe('desktop central proxy',()=>{
  it('reports central health instead of loopback readiness and fails closed offline',async()=>{
    const fetcher=vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({status:'ok'}))).mockResolvedValueOnce(new Response(JSON.stringify({status:'unavailable'}),{status:503})).mockRejectedValueOnce(new Error('offline'))
    const app=await buildRemoteDesktop({apiUrl,redirectBase,fetcher})
    expect((await app.inject({url:'/health',headers:{host}})).json()).toEqual({status:'ok'})
    expect((await app.inject({url:'/health',headers:{host}})).statusCode).toBe(503)
    const offline=await app.inject({url:'/health',headers:{host}})
    expect(offline.statusCode).toBe(503)
    expect(offline.json()).toEqual({status:'unavailable'})
    expect(fetcher.mock.calls[0][0]).toBe(`${apiUrl}/health`)
    await app.close()
  })
  it('restricts destination to the configured central HTTPS origin',()=>{
    expect(centralOrigin(apiUrl)).toBe(apiUrl)
    for(const value of ['http://spl-crm.fly.dev','https://evil.test','https://user@spl-crm.fly.dev','https://spl-crm.fly.dev/api','https://spl-crm.fly.dev/?x=1'])expect(()=>centralOrigin(value)).toThrow()
  })
  it('forwards session cookie, ignores forged bearer, and preserves remote role filtering',async()=>{
    const fetcher=vi.fn().mockResolvedValue(new Response(JSON.stringify({data:[{id:'scoped-event'}]}),{headers:{'content-type':'application/json'}}))
    const app=await buildRemoteDesktop({apiUrl,redirectBase,fetcher})
    const response=await app.inject({url:'/api/events',headers:{host,cookie:`spl_session=${'s'.repeat(43)}`,authorization:`Bearer ${'a'.repeat(43)}`}})
    expect(response.json()).toEqual({data:[{id:'scoped-event'}]})
    expect(fetcher.mock.calls[0][0]).toBe(`${apiUrl}/api/events`)
    expect(fetcher.mock.calls[0][1].headers).toEqual({authorization:`Bearer ${'s'.repeat(43)}`})
    expect(fetcher.mock.calls[0][1].redirect).toBe('error')
    await app.close()
  })
  it('rejects hostile hosts, origins, traversal and native token disclosure',async()=>{
    const fetcher=vi.fn(),app=await buildRemoteDesktop({apiUrl,redirectBase,fetcher})
    expect((await app.inject({url:'/api/events',headers:{host:'evil.test'}})).statusCode).toBe(403)
    expect((await app.inject({method:'POST',url:'/api/auth/login',headers:{host,origin:'https://evil.test'},payload:{}})).statusCode).toBe(403)
    expect((await app.inject({url:'/api/%2e%2e%2fhealth',headers:{host}})).statusCode).toBe(400)
    expect((await app.inject({method:'POST',url:'/api/auth/google/native',headers:{host},payload:{}})).statusCode).toBe(404)
    expect(fetcher).not.toHaveBeenCalled()
    await app.close()
  })
  it('handles offline centrally without a local fallback, and revokes logout remotely',async()=>{
    const fetcher=vi.fn().mockRejectedValueOnce(new Error('network')).mockResolvedValueOnce(new Response(null,{status:204}))
    const app=await buildRemoteDesktop({apiUrl,redirectBase,fetcher})
    expect((await app.inject({url:'/api/events',headers:{host}})).statusCode).toBe(503)
    const logout=await app.inject({method:'POST',url:'/api/auth/logout',headers:{host,cookie:`spl_session=${'s'.repeat(43)}`}})
    expect(logout.statusCode).toBe(204)
    expect(logout.cookies[0].value).toBe('')
    expect(fetcher.mock.calls[1][1].headers.authorization).toBe(`Bearer ${'s'.repeat(43)}`)
    await app.close()
  })
  it('preserves central denial and binary reports without leaking upstream headers',async()=>{
    const fetcher=vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({error:'No autorizado'}),{status:401,headers:{'content-type':'application/json'}})).mockResolvedValueOnce(new Response(new Uint8Array([80,75,3,4]),{headers:{'content-type':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','content-disposition':'attachment; filename="report.xlsx"','x-private':'secret'}}))
    const app=await buildRemoteDesktop({apiUrl,redirectBase,fetcher})
    expect((await app.inject({url:'/api/events',headers:{host}})).statusCode).toBe(401)
    const report=await app.inject({url:'/api/reports/monthly?month=2026-10',headers:{host}})
    expect([...report.rawPayload]).toEqual([80,75,3,4])
    expect(report.headers['content-disposition']).toContain('report.xlsx')
    expect(report.headers['x-private']).toBeUndefined()
    await app.close()
  })
  it('converts only the central session cookie for password login to loopback',async()=>{
    const fetcher=vi.fn().mockResolvedValue(new Response(JSON.stringify({data:{userId:'remote-owner'}}),{headers:{'content-type':'application/json','set-cookie':`spl_session=${'s'.repeat(43)}; Secure; HttpOnly; Path=/; SameSite=Strict`}}))
    const app=await buildRemoteDesktop({apiUrl,redirectBase,fetcher})
    const response=await app.inject({method:'POST',url:'/api/auth/login',headers:{host,origin:redirectBase},payload:{email:'owner@example.com',password:'test-password'}})
    expect(response.cookies[0]).toMatchObject({name:'spl_session',value:'s'.repeat(43),httpOnly:true,sameSite:'Strict'})
    expect(response.cookies[0].secure).not.toBe(true)
    expect(fetcher.mock.calls[0][1].body).toBe(JSON.stringify({email:'owner@example.com',password:'test-password'}))
    await app.close()
  })
  it('exchanges PKCE identity with central server without local user authorization or token disclosure',async()=>{
    const session={token:'s'.repeat(43),expiresAt:new Date(Date.now()+60000).toISOString(),user:{userId:'remote-user',email:'owner@example.com',displayName:'Owner',role:'owner',unit:null}}
    const fetcher=vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({id_token:'i'.repeat(120)}))).mockResolvedValueOnce(new Response(JSON.stringify({data:session})))
    const app=await buildRemoteDesktop({apiUrl,redirectBase,fetcher,clientId:'desktop-id',clientSecret:'test-secret'})
    const start=await app.inject({method:'POST',url:'/api/auth/google/desktop/start',headers:{host}})
    const {flowId,authorizationUrl}=start.json().data,state=new URL(authorizationUrl).searchParams.get('state')
    const callback=await app.inject({url:`/api/auth/google/desktop/callback?code=${'c'.repeat(20)}&state=${state}`,headers:{host,'sec-fetch-site':'cross-site'}})
    expect(callback.statusCode).toBe(200)
    expect(fetcher.mock.calls[1][0]).toBe(`${apiUrl}/api/auth/google/native`)
    const status=await app.inject({url:`/api/auth/google/desktop/status?flowId=${flowId}`,headers:{host}})
    expect(status.json().data.user).toEqual(session.user)
    expect(status.body).not.toContain(session.token)
    expect(status.cookies[0]).toMatchObject({name:'spl_session',httpOnly:true,sameSite:'Strict'})
    expect((await app.inject({url:`/api/auth/google/desktop/status?flowId=${flowId}`,headers:{host}})).statusCode).toBe(404)
    await app.close()
  })
})
