import {beforeEach,describe,expect,it} from 'vitest'
import type {FastifyRequest} from 'fastify'
import {buildApp} from './app.js'
import type {Authenticator} from './auth.js'
import type {Principal} from './domain.js'
import {DevelopmentStore} from './dev.js'

const owner:Principal={userId:'owner-1',role:'owner',unit:null}
const coordinator:Principal={userId:'coord-1',role:'coordinator',unit:'SPL'}
const auth:Authenticator=async(request:FastifyRequest)=>request.headers.authorization==='Bearer owner'?owner:request.headers.authorization==='Bearer coordinator'?coordinator:null
const headers=(token:'owner'|'coordinator')=>({authorization:`Bearer ${token}`,'content-type':'application/json'})
const payload={employeeName:'Andrea López',periodStart:'2026-09-01',periodEnd:'2026-09-15',baseCost:'1000.10',additions:'200.20',deductions:'50.05',allocations:[{scope:'warehouse',eventId:null,amount:'400.10'},{scope:'event',eventId:'11111111-1111-4111-8111-111111111111',amount:'800.20'}]}

describe('payroll API',()=>{
  let store:DevelopmentStore
  beforeEach(()=>{store=new DevelopmentStore()})
  it('creates, lists and partially pays exact payroll totals idempotently',async()=>{const app=buildApp(store,auth,undefined,undefined,store);const created=await app.inject({method:'POST',url:'/api/payroll',headers:headers('owner'),payload});expect(created.statusCode).toBe(201);expect(created.json().data).toMatchObject({laborCost:'1200.30',netPay:'1150.25',outstandingAmount:'1150.25'});const id=created.json().data.id;const payment={paymentDate:'2026-09-15',amount:'500.25',idempotencyKey:'123e4567-e89b-42d3-a456-426614174020'};const first=await app.inject({method:'POST',url:`/api/payroll/${id}/settlements`,headers:headers('owner'),payload:payment});const retry=await app.inject({method:'POST',url:`/api/payroll/${id}/settlements`,headers:headers('owner'),payload:payment});expect(first.json().data.outstandingAmount).toBe('650.00');expect(retry.json().data.id).toBe(first.json().data.id);expect(store.payrollSettlements).toHaveLength(1);expect((await app.inject({method:'GET',url:'/api/payroll',headers:headers('owner')})).json().data[0].paidAmount).toBe('500.25');await app.close()})
  it('blocks coordinators from payroll records and payments',async()=>{const app=buildApp(store,auth,undefined,undefined,store);expect((await app.inject({method:'GET',url:'/api/payroll',headers:headers('coordinator')})).statusCode).toBe(403);expect((await app.inject({method:'POST',url:'/api/payroll',headers:headers('coordinator'),payload})).statusCode).toBe(403);expect((await app.inject({method:'POST',url:'/api/payroll/hidden/settlements',headers:headers('coordinator'),payload:{paymentDate:'2026-09-15',amount:'1.00',idempotencyKey:'123e4567-e89b-42d3-a456-426614174021'}})).statusCode).toBe(403);await app.close()})
  it('rejects invalid totals, dates, money, mass assignment and overpayment',async()=>{const app=buildApp(store,auth,undefined,undefined,store);for(const hostile of [{...payload,periodEnd:'2026-08-31'},{...payload,baseCost:"1; DROP TABLE payroll_entries"},{...payload,allocations:[{scope:'warehouse',amount:'1.00'}]},{...payload,role:'admin'},{...payload,allocations:[{scope:'event',eventId:null,amount:'1200.30'}]}])expect((await app.inject({method:'POST',url:'/api/payroll',headers:headers('owner'),payload:hostile})).statusCode).toBe(400);const created=await app.inject({method:'POST',url:'/api/payroll',headers:headers('owner'),payload});const id=created.json().data.id;const badPayment={paymentDate:'2026-09-15',amount:'9999.00',idempotencyKey:'123e4567-e89b-42d3-a456-426614174022'};expect((await app.inject({method:'POST',url:`/api/payroll/${id}/settlements`,headers:headers('owner'),payload:badPayment})).statusCode).toBe(409);for(const hostile of [{...badPayment,amount:'0.001'},{...badPayment,admin:true},{...badPayment,paymentDate:'not-a-date'}])expect((await app.inject({method:'POST',url:`/api/payroll/${id}/settlements`,headers:headers('owner'),payload:hostile})).statusCode).toBe(400);await app.close()})
  it('returns hostile employee markup as inert data',async()=>{const app=buildApp(store,auth,undefined,undefined,store);const employeeName='<img src=x onerror=alert(1)>';const response=await app.inject({method:'POST',url:'/api/payroll',headers:headers('owner'),payload:{...payload,employeeName}});expect(response.statusCode).toBe(201);expect(response.json().data.employeeName).toBe(employeeName);await app.close()})
  it('exports valid monthly workbooks only for financial roles',async()=>{const app=buildApp(store,auth,undefined,undefined,store);const valid=await app.inject({method:'GET',url:'/api/reports/monthly.xlsx?month=2026-09',headers:headers('owner')});expect(valid.statusCode).toBe(200);expect(valid.headers['content-type']).toContain('spreadsheetml.sheet');expect(valid.rawPayload.subarray(0,2).toString()).toBe('PK');expect((await app.inject({method:'GET',url:'/api/reports/monthly.xlsx?month=2026-09',headers:headers('coordinator')})).statusCode).toBe(403);for(const month of ['2026-13','2026-09-01',"2026-09'%20OR%201=1--"] )expect((await app.inject({method:'GET',url:`/api/reports/monthly.xlsx?month=${month}`,headers:headers('owner')})).statusCode).toBe(400);await app.close()})
  it('stores workers and creates reusable editable payroll templates',async()=>{const app=buildApp(store,auth,undefined,undefined,store);const worker=await app.inject({method:'POST',url:'/api/workers',headers:headers('owner'),payload:{name:'Andrea López'}});expect(worker.statusCode).toBe(201);const input={name:'Nómina semanal',employeeId:worker.json().data.id,baseCost:'1000.00',additions:'50.00',deductions:'25.00',allocations:[{scope:'warehouse',amount:'1050.00'}]};const created=await app.inject({method:'POST',url:'/api/payroll-templates',headers:headers('owner'),payload:input});expect(created.statusCode).toBe(201);const updated=await app.inject({method:'PUT',url:`/api/payroll-templates/${created.json().data.id}`,headers:headers('owner'),payload:{...input,baseCost:'1200.00',allocations:[{scope:'warehouse',amount:'1250.00'}]}});expect(updated.json().data.baseCost).toBe('1200.00');expect((await app.inject({method:'GET',url:'/api/workers',headers:headers('owner')})).json().data[0].name).toBe('Andrea López');expect((await app.inject({method:'GET',url:'/api/payroll-templates',headers:headers('owner')})).json().data).toHaveLength(1);await app.close()})
  it('protects payroll directories from coordinators and hostile payloads',async()=>{const app=buildApp(store,auth,undefined,undefined,store);expect((await app.inject({method:'GET',url:'/api/workers',headers:headers('coordinator')})).statusCode).toBe(403);expect((await app.inject({method:'POST',url:'/api/payroll-templates',headers:headers('coordinator'),payload:{}})).statusCode).toBe(403);for(const value of ['', 'x'.repeat(161)])expect((await app.inject({method:'POST',url:'/api/workers',headers:headers('owner'),payload:{name:value}})).statusCode).toBe(400);expect((await app.inject({method:'POST',url:'/api/workers',headers:headers('owner'),payload:{name:'Andrea',role:'admin'}})).statusCode).toBe(400);const hostile="Robert'); DROP TABLE workers; --";const created=await app.inject({method:'POST',url:'/api/workers',headers:headers('owner'),payload:{name:hostile}});expect(created.json().data.name).toBe(hostile);const invalid={name:'Ataque',baseCost:'100',additions:'0',deductions:'0',allocations:[{scope:'event',eventId:null,amount:'100'}],__protoAdmin:true};expect((await app.inject({method:'POST',url:'/api/payroll-templates',headers:headers('owner'),payload:invalid})).statusCode).toBe(400);await app.close()})
})
