import type {PropsWithChildren,ReactNode} from 'react'
import {ActivityIndicator,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,TextInput,View,type TextInputProps} from 'react-native'
import {colors} from './theme'
export function Screen({title,action,children,loading=false}:{title:string;action?:ReactNode;loading?:boolean}&PropsWithChildren){return <SafeAreaView style={styles.safe}><View style={styles.head}><Text style={styles.title}>{title}</Text>{action}</View>{loading?<ActivityIndicator color={colors.orange} size="large"/>:<ScrollView contentContainerStyle={styles.body} refreshControl={undefined}>{children}</ScrollView>}</SafeAreaView>}
export function Card({children,onPress}:{children:ReactNode;onPress?:()=>void}){return <Pressable disabled={!onPress} onPress={onPress} style={styles.card}>{children}</Pressable>}
export function Money({value,color=colors.text}:{value:string|number;color?:string}){return <Text style={[styles.money,{color}]}>{new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'}).format(Number(value))}</Text>}
export function Field({label,...props}:TextInputProps&{label:string}){return <View style={{gap:6}}><Text style={ui.label}>{label}</Text><TextInput placeholderTextColor="#667487" {...props} style={[ui.input,props.style]}/></View>}
export const ui=StyleSheet.create({label:{color:colors.muted,fontSize:13,lineHeight:20},text:{color:colors.text,fontSize:16,lineHeight:24},row:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:12},section:{color:colors.text,fontSize:20,fontWeight:'700',marginTop:8,marginBottom:4},empty:{color:colors.muted,fontSize:15,textAlign:'center',padding:30},button:{backgroundColor:colors.orange,borderRadius:10,paddingHorizontal:16,paddingVertical:12,alignItems:'center'},secondaryButton:{borderColor:colors.border,borderWidth:1,borderRadius:10,paddingHorizontal:16,paddingVertical:12,alignItems:'center'},buttonText:{color:'#fff',fontSize:15,fontWeight:'700'},input:{minHeight:48,color:colors.text,fontSize:16,backgroundColor:colors.panelAlt,borderWidth:1,borderColor:colors.border,borderRadius:10,paddingHorizontal:12},error:{color:'#fecaca',padding:12,backgroundColor:'#3b1717',borderRadius:10}})
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},head:{minHeight:70,paddingHorizontal:20,paddingVertical:14,borderBottomWidth:1,borderColor:colors.border,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},title:{color:colors.text,fontSize:24,fontWeight:'800'},body:{padding:16,gap:12},card:{backgroundColor:colors.panel,borderWidth:1,borderColor:colors.border,borderRadius:14,padding:16,gap:8},money:{fontSize:18,fontWeight:'800'}})
