import { useCallback, useEffect, useRef, useState } from 'react'
import { ArrowLeft, CalendarDays, Check, ChevronRight, Plus, Search, Trash2, Users, Wallet, X } from 'lucide-react'
import { payrollDirectoryApi, weeklyPayrollApi, type ApiTeamTemplate, type ApiWeeklyPayroll, type ApiWorker, type LegacyPayroll } from '../api'
import { applyTeam, blank, cash, decimal, localDate, totals, validate, type Editor } from './model'
import './payroll.css'

type EventChoice = { id: string; client: string; venue: string; date: string }
type Props = { events: EventChoice[]; onChanged: () => void }
const message = (error: unknown) => error instanceof Error ? error.message : 'No se pudo completar la operación.'
const period = (start: string, end: string) => `${new Date(`${start}T12:00:00`).toLocaleDateString('es-MX',{day:'numeric',month:'short'})} - ${new Date(`${end}T12:00:00`).toLocaleDateString('es-MX',{day:'numeric',month:'short',year:'numeric'})}`

export function PayrollPage({ events, onChanged }: Props) {
  const [batches,setBatches] = useState<ApiWeeklyPayroll[]>([]), [workers,setWorkers] = useState<ApiWorker[]>([]), [templates,setTemplates] = useState<ApiTeamTemplate[]>([])
  const [legacy,setLegacy] = useState<LegacyPayroll>({entries:[],settlements:[]}), [loading,setLoading] = useState(true), [error,setError] = useState(''), [notice,setNotice] = useState(''), [busy,setBusy] = useState(false)
  const [editor,setEditor] = useState<Editor|null>(null), [dirty,setDirty] = useState(false), [templateMode,setTemplateMode] = useState(false)
  const [templateId,setTemplateId] = useState(''), [templateName,setTemplateName] = useState(''), [isDefault,setIsDefault] = useState(false), [includeExpenses,setIncludeExpenses] = useState(false)
  const [query,setQuery] = useState(''), [workerOpen,setWorkerOpen] = useState(false), [month,setMonth] = useState(''), [filter,setFilter] = useState('all'), [showTemplates,setShowTemplates] = useState(false)
  const [dialog,setDialog] = useState<'pay'|'reverse'|'discard'|null>(null), [paymentDate,setPaymentDate] = useState(localDate()), [reason,setReason] = useState('')
  const lock = useRef(false), dialogRef = useRef<HTMLDialogElement>(null), actionRequest = useRef<{kind:string;key:string;version:number;value:string}|null>(null)
  const active = batches.find(b=>b.id===editor?.id), paid = active?.status==='paid', readOnly = paid || active?.historical
  const load = useCallback(async()=>{
    setLoading(true); setError('')
    try { const [records,directory,teams,old] = await Promise.all([weeklyPayrollApi.list(),payrollDirectoryApi.workers(),weeklyPayrollApi.templates(),weeklyPayrollApi.legacy()]);setBatches(records);setWorkers(directory);setTemplates(teams);setLegacy(old) }
    catch(e) { setError(message(e)) } finally { setLoading(false) }
  },[])
  useEffect(()=>{void load()},[load])
  useEffect(()=>{if(dialog)dialogRef.current?.showModal();else dialogRef.current?.close()},[dialog])
  useEffect(()=>{if(!dirty)return;const prevent=(e:BeforeUnloadEvent)=>{e.preventDefault()};window.addEventListener('beforeunload',prevent);return()=>window.removeEventListener('beforeunload',prevent)},[dirty])
  const change = (next: Editor) => {setEditor({...next,idempotencyKey:crypto.randomUUID()});setDirty(true);setError('');setNotice('')}
  const open = (batch: ApiWeeklyPayroll) => {
    setEditor({id:batch.id,version:batch.version,idempotencyKey:crypto.randomUUID(),periodStart:batch.periodStart,periodEnd:batch.periodEnd,lines:batch.lines.map(({id,employeeId,baseCost,additions,deductions,allocations})=>({id,employeeId,baseCost,additions,deductions,allocations:structuredClone(allocations)})),expenses:structuredClone(batch.expenses)})
    setTemplateMode(false);setDirty(false);setError('');setNotice('');setWorkerOpen(false);setQuery('');setTemplateId('')
  }
  const create = (template?: ApiTeamTemplate, asTemplate=false) => {
    const team=template??(!asTemplate?templates.find(t=>t.isDefault):undefined)
    setEditor(team?applyTeam(blank(),team):blank());setTemplateMode(asTemplate);setShowTemplates(false);setTemplateId(asTemplate?template?.id??'':team?.id??'');setTemplateName(asTemplate?template?.name??'':'');setIsDefault(asTemplate?template?.isDefault??false:false);setIncludeExpenses(asTemplate?Boolean(template?.expenses.length):false);setDirty(false);setError('');setNotice('');setWorkerOpen(false);setQuery('')
  }
  const closeEditor = () => {setEditor(null);setDirty(false);setDialog(null);setError('');setNotice('')}
  const guard = async(task:()=>Promise<void>) => {
    if(lock.current)return;lock.current=true;setBusy(true);setError('');setNotice('')
    try{await task()}catch(e){setError(message(e))}finally{lock.current=false;setBusy(false)}
  }
  const save = () => guard(async()=>{
    if(!editor)return
    const problem=validate(templateMode&&!includeExpenses?{...editor,expenses:[]}:editor);if(problem)throw new Error(problem)
    if(templateMode){
      if(!templateName.trim())throw new Error('Escribe el nombre de la plantilla.')
      const existing=templates.find(t=>t.id===templateId),id=existing?.id??editor.id
      await weeklyPayrollApi.saveTemplate(id,{version:existing?.version??0,idempotencyKey:editor.idempotencyKey,name:templateName,isDefault,lines:editor.lines.map(({employeeId,baseCost,additions,deductions})=>({employeeId,baseCost,additions,deductions})),expenses:includeExpenses?editor.expenses.map(({concept,amount,notes})=>({concept,amount,notes})):[]})
      setTemplates(await weeklyPayrollApi.templates());setDirty(false);setEditor(null);setShowTemplates(true);setNotice('Plantilla guardada.')
    }else{
      const {id,...input}=editor,saved=await weeklyPayrollApi.save(id,input)
      setBatches(current=>[saved,...current.filter(b=>b.id!==id)]);setEditor({...editor,version:saved.version,idempotencyKey:crypto.randomUUID()});setDirty(false);setNotice('Nómina guardada. Aún no está pagada.');onChanged()
    }
  })
  const addWorker = (worker: ApiWorker) => {
    if(!editor||editor.lines.some(l=>l.employeeId===worker.id))return
    change({...editor,lines:[...editor.lines,{id:crypto.randomUUID(),employeeId:worker.id,baseCost:'0.00',additions:'0.00',deductions:'0.00',allocations:[{scope:'warehouse',amount:'0.00'}]}]});setQuery('');setWorkerOpen(false)
  }
  const createWorker = () => guard(async()=>{const worker=await payrollDirectoryApi.createWorker(query.trim());setWorkers(current=>[...current,worker]);addWorker(worker)})
  const updateLine = (id:string,key:'baseCost'|'additions'|'deductions',value:string) => {
    if(!editor)return
    change({...editor,lines:editor.lines.map(line=>{
      if(line.id!==id)return line
      const next={...line,[key]:value}
      if(next.allocations.length===1)next.allocations=[{...next.allocations[0],amount:decimal(next.baseCost).plus(next.additions||0).toFixed(2)}]
      return next
    })})
  }
  const doPayment = () => guard(async()=>{
    if(!active||!editor)return
    const kind=dialog==='reverse'?'reverse':'pay',value=kind==='pay'?paymentDate:reason
    if(kind==='pay'&&!paymentDate)throw new Error('Selecciona la fecha de pago.')
    if(kind==='reverse'&&!reason.trim())throw new Error('Explica el motivo de la reversión.')
    if(!actionRequest.current||actionRequest.current.kind!==kind||actionRequest.current.version!==active.version||actionRequest.current.value!==value)actionRequest.current={kind,key:crypto.randomUUID(),version:active.version,value}
    const input={version:active.version,idempotencyKey:actionRequest.current.key}
    const updated=kind==='pay'?await weeklyPayrollApi.pay(active.id,{...input,paymentDate}):await weeklyPayrollApi.reverse(active.id,{...input,reason})
    setBatches(current=>current.map(b=>b.id===updated.id?updated:b));setEditor({...editor,version:updated.version});setDialog(null);setDirty(false);setNotice(kind==='pay'?'Pago completo registrado.':'El pago se revirtió; la nómina está No pagada.');onChanged()
  })
  const selectedTemplate=templates.find(t=>t.id===templateId),summary=editor?totals(editor):null
  const available=workers.filter(w=>!editor?.lines.some(l=>l.employeeId===w.id)&&w.name.toLocaleLowerCase().includes(query.toLocaleLowerCase()))
  const chooseDestination = (value:string) => value==='warehouse'?{scope:'warehouse' as const,eventId:null}:{scope:'event' as const,eventId:value}
  const destinations = <><option value="warehouse">Almacén</option>{events.map(e=><option key={e.id} value={e.id}>{e.client} · {e.venue} · {e.date}</option>)}</>
  const filtered=batches.filter(b=>(filter==='all'||b.status===filter)&&(!month||(b.periodStart<=`${month}-31`&&b.periodEnd>=`${month}-01`))).sort((a,b)=>b.periodEnd.localeCompare(a.periodEnd))

  return <div className="content payroll-v2">
    <header className="pr-heading"><div><p className="pr-eyebrow">EQUIPO Y COSTOS</p><h1>{editor?templateMode?'Plantilla de equipo':active?'Detalle de nómina':'Nueva nómina':'Nóminas'}</h1><p>{editor?'Una semana, todo tu equipo y un solo pago.':'Organiza tu semana. Revisa los importes. Registra el pago completo.'}</p></div>
      {editor?<button className="pr-button" disabled={busy} onClick={()=>dirty?setDialog('discard'):closeEditor()}><ArrowLeft size={16}/>Volver a nóminas</button>:<div className="pr-actions"><button className="pr-button" onClick={()=>setShowTemplates(!showTemplates)}>Plantillas</button><button className="pr-button pr-primary" disabled={loading} onClick={()=>create()}><Plus size={18}/>Nueva nómina</button></div>}
    </header>
    {error&&<div className="pr-alert" role="alert">{error}{!editor&&<button className="pr-button" onClick={()=>void load()}>Reintentar</button>}{editor&&active&&<button className="pr-button" onClick={()=>{void guard(async()=>{const fresh=await weeklyPayrollApi.list();setBatches(fresh);const latest=fresh.find(b=>b.id===active.id);if(latest){setEditor({...editor,version:latest.version,idempotencyKey:crypto.randomUUID()});setNotice('Versión actualizada. Tu captura se conserva; revisa los cambios antes de guardar.')}})}}>Consultar versión actual</button>}</div>}
    {notice&&<div className="pr-notice" role="status"><Check size={17}/>{notice}</div>}
    {loading?<div className="pr-empty" role="status">Cargando nóminas...</div>:editor?<div className="pr-editor-layout"><div className="pr-sections" inert={busy}>
      <section className="pr-panel"><div className="pr-section-title"><span>01</span><div><h2>{templateMode?'Nombre y preferencias':'Semana y plantilla'}</h2><p>{templateMode?'Guarda el equipo que utilizas habitualmente.':'Las fechas se aplican a todos los trabajadores.'}</p></div></div>
        {templateMode?<div className="pr-fields"><label>Nombre de plantilla<input value={templateName} maxLength={120} onChange={e=>{setTemplateName(e.target.value);change(editor)}}/></label><label className="pr-checkbox"><input type="checkbox" checked={isDefault} onChange={e=>{setIsDefault(e.target.checked);change(editor)}}/>Usar como predeterminada</label></div>:<div className="pr-fields"><label>Inicio<input type="date" disabled={readOnly||busy} value={editor.periodStart} onChange={e=>change({...editor,periodStart:e.target.value})}/></label><label>Fin<input type="date" disabled={readOnly||busy} value={editor.periodEnd} onChange={e=>change({...editor,periodEnd:e.target.value})}/></label>{!active&&<label>Plantilla<select value={templateId} disabled={busy} onChange={e=>{setTemplateId(e.target.value);const team=templates.find(t=>t.id===e.target.value);change(team?applyTeam(editor,team):{...editor,lines:[],expenses:[]})}}><option value="">Sin plantilla</option>{templates.map(t=><option key={t.id} value={t.id}>{t.name}{t.isDefault?' · Predeterminada':''}</option>)}</select></label>}</div>}
      </section>
      <section className="pr-panel"><div className="pr-section-title"><span>02</span><div><h2>Trabajadores <small>{editor.lines.length}</small></h2><p>Un importe distinto para cada persona.</p></div>{!readOnly&&<button className="pr-button" disabled={busy} onClick={()=>setWorkerOpen(!workerOpen)}><Plus size={16}/>Agregar trabajador</button>}</div>
        {workerOpen&&!readOnly&&<div className="pr-worker-picker"><label><Search size={17}/><input autoFocus aria-label="Buscar o crear trabajador" placeholder="Buscar o crear trabajador..." value={query} maxLength={160} onChange={e=>setQuery(e.target.value)}/></label><div className="pr-worker-results">{available.map(w=><button disabled={busy} key={w.id} onClick={()=>addWorker(w)}><Users size={15}/>{w.name}<Plus size={15}/></button>)}{!available.length&&<p>No hay trabajadores disponibles con ese nombre.</p>}</div>{query.trim()&&!workers.some(w=>w.name.toLocaleLowerCase()===query.trim().toLocaleLowerCase())&&<button className="pr-button" disabled={busy} onClick={()=>void createWorker()}>Crear y agregar «{query.trim()}»</button>}</div>}
        {!editor.lines.length?<div className="pr-empty"><Users size={30}/><h3>Empieza por tu equipo</h3><p>Agrega trabajadores o selecciona una plantilla.</p></div>:<div className="pr-workers"><div className="pr-worker-head"><span>Trabajador</span><span>Sueldo base</span><span>Adiciones</span><span>Deducciones</span><span>Neto</span><span/></div>{editor.lines.map(line=>{
          const name=workers.find(w=>w.id===line.employeeId)?.name??active?.lines.find(l=>l.id===line.id)?.employeeName??'Trabajador histórico'
          const labor=decimal(line.baseCost).plus(line.additions||0),net=labor.minus(line.deductions||0),allocated=line.allocations.reduce((s,a)=>s.plus(a.amount||0),decimal('0'))
          return <article className="pr-worker" key={line.id}><div className="pr-worker-grid"><strong className="pr-worker-name">{name}</strong>{(['baseCost','additions','deductions'] as const).map((key,index)=><label key={key}><span>{['Sueldo base','Adiciones','Deducciones'][index]}</span><input aria-label={`${['Base','Adiciones','Deducciones'][index]} ${name}`} type="number" min="0" step="0.01" disabled={readOnly||busy} value={line[key]} onChange={e=>updateLine(line.id,key,e.target.value)}/></label>)}<strong className={net.lt(0)?'pr-net pr-invalid':'pr-net'}><small>Neto</small>{cash(net.toFixed(2))}</strong>{!readOnly&&<button className="pr-icon-button" disabled={busy} aria-label={`Quitar ${name}`} onClick={()=>change({...editor,lines:editor.lines.filter(l=>l.id!==line.id)})}><Trash2 size={17}/></button>}</div>
            {!templateMode&&<details className="pr-allocation"><summary>Distribución del costo · {line.allocations.length===1&&line.allocations[0].scope==='warehouse'?'Almacén':`${line.allocations.length} destino(s)`} <span>{cash(labor.toFixed(2))}</span></summary><p>Distribuye el sueldo más las adiciones, antes de deducciones.</p>{line.allocations.map((allocation,index)=><div className="pr-allocation-row" key={index}><select aria-label={`Destino ${name} ${index+1}`} disabled={readOnly||busy} value={allocation.scope==='warehouse'?'warehouse':allocation.eventId??''} onChange={e=>change({...editor,lines:editor.lines.map(l=>l.id===line.id?{...l,allocations:l.allocations.map((a,i)=>i===index?{...a,...chooseDestination(e.target.value)}:a)}:l)})}>{destinations}</select><input aria-label={`Distribución ${name} ${index+1}`} type="number" min="0.01" step="0.01" disabled={readOnly||busy||line.allocations.length===1} value={allocation.amount} onChange={e=>change({...editor,lines:editor.lines.map(l=>l.id===line.id?{...l,allocations:l.allocations.map((a,i)=>i===index?{...a,amount:e.target.value}:a)}:l)})}/>{!readOnly&&line.allocations.length>1&&<button className="pr-icon-button" aria-label={`Quitar destino ${index+1} de ${name}`} onClick={()=>change({...editor,lines:editor.lines.map(l=>{if(l.id!==line.id)return l;const remaining=l.allocations.filter((_,i)=>i!==index);return{...l,allocations:remaining.length===1?[{...remaining[0],amount:labor.toFixed(2)}]:remaining}})})}><X size={16}/></button>}</div>)}{!readOnly&&<button className="pr-link" onClick={()=>change({...editor,lines:editor.lines.map(l=>l.id===line.id?{...l,allocations:[...l.allocations,{scope:'warehouse',amount:'0.00'}]}:l)})}>+ Dividir en otro destino</button>}<p className={!allocated.eq(labor)?'pr-invalid':''}>Distribuido {cash(allocated.toFixed(2))} de {cash(labor.toFixed(2))}</p></details>}
            {net.lt(0)&&<p className="pr-invalid" role="alert">Las deducciones superan el importe de este trabajador.</p>}
          </article>
        })}</div>}
      </section>
      <section className="pr-panel"><div className="pr-section-title"><span>03</span><div><h2>Otros gastos <small>Opcional</small></h2><p>Transporte, alimentos u otros gastos de toda la nómina.</p></div>{!readOnly&&<button className="pr-button" disabled={busy} onClick={()=>change({...editor,expenses:[...editor.expenses,{id:crypto.randomUUID(),concept:'',amount:'',notes:'',scope:'warehouse'}]})}><Plus size={16}/>Agregar gasto</button>}</div>
        {!editor.expenses.length?<p className="pr-muted">Sin gastos adicionales. Puedes guardar la nómina solo con los sueldos.</p>:editor.expenses.map((expense,index)=><div className="pr-expense" key={expense.id}><div className="pr-expense-fields"><label>Concepto<input aria-label={`Concepto del gasto ${index+1}`} value={expense.concept} disabled={readOnly||busy} maxLength={200} onChange={e=>change({...editor,expenses:editor.expenses.map(x=>x.id===expense.id?{...x,concept:e.target.value}:x)})}/></label><label>Importe<input aria-label={`Importe del gasto ${index+1}`} type="number" min="0.01" step="0.01" value={expense.amount} disabled={readOnly||busy} onChange={e=>change({...editor,expenses:editor.expenses.map(x=>x.id===expense.id?{...x,amount:e.target.value}:x)})}/></label>{!templateMode&&<label>Destino<select aria-label={`Destino del gasto ${index+1}`} value={expense.scope==='warehouse'?'warehouse':expense.eventId??''} disabled={readOnly||busy} onChange={e=>change({...editor,expenses:editor.expenses.map(x=>x.id===expense.id?{...x,...chooseDestination(e.target.value)}:x)})}>{destinations}</select></label>}{!readOnly&&<button className="pr-icon-button" aria-label={`Quitar gasto ${index+1}`} onClick={()=>change({...editor,expenses:editor.expenses.filter(x=>x.id!==expense.id)})}><Trash2 size={17}/></button>}</div><label className="pr-expense-notes">Notas opcionales<input aria-label={`Notas del gasto ${index+1}`} disabled={readOnly||busy} maxLength={1000} value={expense.notes} onChange={e=>change({...editor,expenses:editor.expenses.map(x=>x.id===expense.id?{...x,notes:e.target.value}:x)})}/></label></div>)}
        {templateMode&&<label className="pr-checkbox"><input type="checkbox" checked={includeExpenses} onChange={e=>{setIncludeExpenses(e.target.checked);change(editor)}}/>Incluir estos gastos recurrentes en la plantilla</label>}
      </section>
      {active&&active.history.length>0&&<details className="pr-panel pr-history"><summary>Historial de la nómina</summary>{[...active.history].reverse().map((h,i)=><div key={i}><strong>{h.reason}</strong><span>{new Date(h.at).toLocaleString('es-MX')}</span><small>Usuario: {h.actor}</small></div>)}</details>}
    </div><aside className="pr-panel pr-summary"><div className="pr-section-title"><span>04</span><h2>Resumen</h2></div><span className={`pr-status ${paid?'paid':''}`}>{templateMode?'Plantilla':paid?'Pagada':'No pagada'}</span><p className="pr-summary-period"><CalendarDays size={16}/>{period(editor.periodStart||localDate(),editor.periodEnd||localDate())}</p><dl><div><dt>Trabajadores</dt><dd>{editor.lines.length}</dd></div><div><dt>Sueldos netos</dt><dd>{cash(summary!.wages)}</dd></div><div><dt>Otros gastos</dt><dd>{cash(summary!.expenses)}</dd></div></dl><div className="pr-grand-total"><span>Total de la nómina</span><strong>{cash(summary!.total)}</strong><small>MXN · Incluye todos los trabajadores y gastos</small></div>
      {!readOnly&&<button className="pr-button pr-primary" disabled={busy} onClick={()=>void save()}>{busy?'Guardando...':templateMode?'Guardar plantilla':'Guardar nómina'}</button>}
      {!templateMode&&active&&!readOnly&&<><button className="pr-button" disabled={busy||dirty} onClick={()=>{setPaymentDate(localDate());setDialog('pay')}}><Wallet size={16}/>Registrar pago completo</button><p className="pr-muted">{dirty?'Guarda los cambios antes de registrar el pago.':'El pago se registra para toda la nómina.'}</p></>}
      {paid&&<><p className="pr-paid-note"><Check size={18}/>Pago completo registrado el {active?.payments.findLast(p=>!p.reversedAt)?.paymentDate}.</p><p className="pr-muted">Esta nómina está protegida contra cambios.</p>{!active?.historical&&<button className="pr-link" disabled={busy} onClick={()=>{setReason('');setDialog('reverse')}}>Revertir registro de pago</button>}</>}
      {!templateMode&&!readOnly&&editor.lines.length>0&&<button className="pr-link" disabled={busy} onClick={()=>{setTemplateMode(true);setTemplateId('');setTemplateName('');setIsDefault(false);setIncludeExpenses(false);setEditor({...editor,id:crypto.randomUUID(),version:0,idempotencyKey:crypto.randomUUID()});setDirty(true)}}>Crear plantilla con este equipo</button>}
      {!active&&!templateMode&&<p className="pr-muted">Guardar no registra un pago.</p>}
    </aside></div>:<>
      {showTemplates&&<section className="pr-panel pr-template-panel"><div className="pr-section-title"><div><h2>Plantillas de equipo</h2><p>Tu equipo habitual, listo para otra semana.</p></div><button className="pr-button" onClick={()=>create(undefined,true)}><Plus size={16}/>Nueva plantilla</button></div>{!templates.length?<p className="pr-muted">Crea una plantilla con los trabajadores y montos habituales.</p>:templates.map(t=><article className="pr-template" key={t.id}><div><strong>{t.name}</strong><small>{t.lines.length} trabajadores{t.isDefault?' · Predeterminada':''}</small></div><button className="pr-button" onClick={()=>create(t)}>Usar</button><button className="pr-button" onClick={()=>create(t,true)}>Editar plantilla</button>{!t.isDefault&&<button className="pr-link" disabled={busy} onClick={()=>void guard(async()=>{const {id,operations,...input}=t;void operations;await weeklyPayrollApi.saveTemplate(id,{...input,isDefault:true,idempotencyKey:crypto.randomUUID()});setTemplates(await weeklyPayrollApi.templates())})}>Hacer predeterminada</button>}</article>)}</section>}
      <section className="pr-overview"><div><span>Nóminas registradas</span><strong>{batches.length}</strong></div><div><span>No pagadas</span><strong>{batches.filter(b=>b.status==='unpaid').length}</strong></div><div><span>Pagadas</span><strong>{batches.filter(b=>b.status==='paid').length}</strong></div></section>
      <section className="pr-panel"><div className="pr-list-toolbar"><h2>Historial semanal</h2><div className="pr-filters"><label>Periodo<input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label><label>Estado<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Todos</option><option value="unpaid">No pagada</option><option value="paid">Pagada</option></select></label></div></div>{!filtered.length?<div className="pr-empty"><CalendarDays size={32}/><h3>{batches.length?'Sin resultados':'Tu primera semana empieza aquí'}</h3><p>{batches.length?'Ajusta los filtros para ver otras nóminas.':'Crea una nómina, agrega tu equipo y revisa el total.'}</p>{!batches.length&&<button className="pr-button pr-primary" onClick={()=>create()}>Crear primera nómina</button>}</div>:<div className="pr-batch-list">{filtered.map(batch=><button className="pr-batch" key={batch.id} onClick={()=>open(batch)}><span className="pr-calendar"><CalendarDays size={22}/></span><span className="pr-batch-title"><strong>{period(batch.periodStart,batch.periodEnd)}</strong><small>{batch.lines.length} trabajadores · {batch.expenses.length} gastos</small></span><span className={`pr-status ${batch.status==='paid'?'paid':''}`}>{batch.status==='paid'?'Pagada':'No pagada'}</span><strong>{cash(batch.total)}</strong><ChevronRight size={18}/></button>)}</div>}</section>
      {legacy.entries.length>0&&<details className="pr-panel pr-legacy"><summary>Registros anteriores · Solo consulta ({legacy.entries.length})</summary><p>Se conservaron los importes y pagos originales. Estos registros no admiten nuevos pagos ni cambios.</p>{legacy.entries.map(entry=><article key={entry.id}><strong>{entry.employeeName}</strong><span>{entry.periodStart} - {entry.periodEnd}</span><span>Neto {cash(entry.netPay)} · Registrado {cash(entry.paidAmount)}</span>{entry.archivedDraft&&<small>Captura anterior sin confirmar. No afecta costos.</small>}{legacy.settlements.filter(s=>s.payrollEntryId===entry.id).map(s=><small key={s.id}>Pago histórico {s.paymentDate}: {cash(s.amount)}</small>)}</article>)}</details>}
    </>}
    <dialog ref={dialogRef} className="pr-dialog" aria-labelledby="pr-dialog-title" onCancel={e=>{e.preventDefault();if(!busy)setDialog(null)}}><div className="pr-dialog-head"><h2 id="pr-dialog-title">{dialog==='pay'?'Registrar pago completo':dialog==='reverse'?'Revertir registro de pago':'Salir del editor'}</h2><button className="pr-icon-button" disabled={busy} aria-label="Cerrar diálogo" onClick={()=>setDialog(null)}><X size={20}/></button></div>{dialog==='discard'?<><p>Hay cambios sin guardar. Puedes volver al editor o descartarlos.</p><div className="pr-actions"><button className="pr-button" onClick={()=>setDialog(null)}>Seguir editando</button><button className="pr-button pr-primary" onClick={closeEditor}>Descartar cambios</button></div></>:<><p>{dialog==='pay'?'Registrarás el pago de todos los trabajadores y gastos de esta nómina.':'Esta acción corrige el registro interno. La nómina volverá a No pagada y conservará el historial.'}</p>{dialog==='pay'?<><strong className="pr-dialog-total">{cash(active?.total??'0')}</strong><label>Fecha de pago<input autoFocus type="date" value={paymentDate} onChange={e=>setPaymentDate(e.target.value)}/></label></>:<label>Motivo de la reversión<textarea autoFocus rows={3} maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></label>}{error&&<p className="pr-invalid" role="alert">{error}</p>}<div className="pr-actions"><button className="pr-button" disabled={busy} onClick={()=>setDialog(null)}>Cancelar</button><button className="pr-button pr-primary" disabled={busy} onClick={()=>void doPayment()}>{busy?'Registrando...':dialog==='pay'?'Confirmar pago completo':'Confirmar reversión'}</button></div></>}</dialog>
    {selectedTemplate&&templateMode&&<span className="pr-sr-only">Editando {selectedTemplate.name}</span>}
  </div>
}
