import { afterEach, describe, expect, it, vi } from 'vitest'
import { ApiError, authApi, eventApi } from './api'

const ok = (data:unknown) => new Response(JSON.stringify({data}),{status:200,headers:{'content-type':'application/json'}})
describe('eventApi',()=>{
  afterEach(()=>vi.unstubAllGlobals())
  it('loads events on the happy path',async()=>{const fetch=vi.fn().mockResolvedValue(ok([{id:'1'}]));vi.stubGlobal('fetch',fetch);await expect(eventApi.list()).resolves.toEqual([{id:'1'}]);expect(fetch).toHaveBeenCalledOnce()})
  it('retries a safe GET once after a temporary server failure',async()=>{const fetch=vi.fn().mockResolvedValueOnce(new Response('',{status:503})).mockResolvedValueOnce(ok([]));vi.stubGlobal('fetch',fetch);await expect(eventApi.list()).resolves.toEqual([]);expect(fetch).toHaveBeenCalledTimes(2)})
  it('does not retry a create that could duplicate a financial record',async()=>{const fetch=vi.fn().mockResolvedValue(new Response('',{status:503}));vi.stubGlobal('fetch',fetch);await expect(eventApi.create({} as never)).rejects.toMatchObject({kind:'server'});expect(fetch).toHaveBeenCalledOnce()})
  it('maps authentication and authorization failures without exposing response bodies',async()=>{for(const [status,kind] of [[401,'unauthorized'],[403,'forbidden']] as const){vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response('sensitive server detail',{status})));await expect(eventApi.list()).rejects.toMatchObject({kind})}})
  it('rejects malformed success responses',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response('{bad json',{status:200})));await expect(eventApi.list()).rejects.toBeInstanceOf(ApiError)})
  it('encodes hostile identifiers instead of placing them raw in the URL',async()=>{const fetch=vi.fn().mockResolvedValue(ok([]));vi.stubGlobal('fetch',fetch);await eventApi.listExpenses("../events?all=true#' OR 1=1");expect(fetch.mock.calls[0][0]).not.toContain("#' OR")})
  it('reports network failures with a recoverable error',async()=>{vi.stubGlobal('fetch',vi.fn().mockRejectedValue(new TypeError('offline')));await expect(eventApi.list()).rejects.toMatchObject({kind:'network'})})
  it('sends login credentials only in a JSON body and requests an HTTP-only session',async()=>{const fetch=vi.fn().mockResolvedValue(ok({role:'owner'}));vi.stubGlobal('fetch',fetch);await authApi.login('owner@spl.test','Secret-Password');const [url,options]=fetch.mock.calls[0];expect(url).not.toContain('Secret-Password');expect(JSON.parse(options.body)).toEqual({email:'owner@spl.test',password:'Secret-Password'});expect(options.credentials).toBe('include')})
  it('sends the Google credential to the dedicated backend verifier',async()=>{const fetch=vi.fn().mockResolvedValue(ok({role:'admin'}));vi.stubGlobal('fetch',fetch);await authApi.google('signed-google-id-token');const [url,options]=fetch.mock.calls[0];expect(url).toContain('/api/auth/google');expect(JSON.parse(options.body)).toEqual({credential:'signed-google-id-token'});expect(options.credentials).toBe('include')})
  it('uses idempotency keys for payment and settlement writes without automatic retries',async()=>{const fetch=vi.fn().mockImplementation(()=>Promise.resolve(ok({id:'movement-1'})));vi.stubGlobal('fetch',fetch);const key=crypto.randomUUID();await eventApi.addPayment('event/1',{transactionDate:'2026-09-15',amount:'100.00',kind:'payment',idempotencyKey:key});await eventApi.settleExpense('expense/1',{paymentDate:'2026-09-15',amount:'50.00',idempotencyKey:key});expect(fetch).toHaveBeenCalledTimes(2);expect(fetch.mock.calls[0][0]).toContain('event%2F1');expect(fetch.mock.calls[1][0]).toContain('expense%2F1');expect(JSON.parse(fetch.mock.calls[0][1].body).idempotencyKey).toBe(key)})
})
