import { PayrollPage } from './payroll/PayrollPage'
import React from 'react'
import ReactDOM from 'react-dom/client'
import { CalendarDays, Check, ChevronDown, CircleDollarSign, Database, Download, LayoutDashboard, Menu, MoreHorizontal, Plus, Search, Settings, ShieldCheck, Users, WalletCards, Wifi, X } from 'lucide-react'
import { authApi, desktopGoogleApi, eventApi, healthApi, payrollApi, reportApi, testLoginApi, type ApiEvent, type ApiExpense, type ApiPayment, type ApiPayroll, type CreateEventInput, type SessionUser } from './api'
import {waitForDesktopGoogle} from './desktop-auth'
import {calculateFinanceSummary} from './finance'
import {defaultPreferences,parsePreferences,type Preferences} from './settings'
import './styles.css'
type Scope = 'SPL consolidado' | 'SPL - eventos propios' | '5to Elemento'
type View = 'dashboard' | 'events' | 'finance' | 'payroll' | 'settings'
type Unit = 'SPL' | '5to Elemento'
type Expense = { id: string; name: string; category: string; amount: number; paid: number; source?: 'payroll' }
type Payment = { id: string; date: string; amount: number; kind?:'payment'|'refund'; version?:number }
type EventRecord = { id: string; version:number; unit: Unit; name: string; client: string; venue: string; date: string; price: number | null; payrollBudget: number; expenseBudget: number; payrollActual: number; status: 'Confirmado' | 'Pendiente'; payments: Payment[]; expenses: Expense[] }
type GoogleIdentityApi={initialize:(input:{client_id:string;callback:(response:{credential:string})=>void})=>void;renderButton:(element:HTMLElement,input:Record<string,unknown>)=>void}
declare global { interface Window { google?:{accounts:{id:GoogleIdentityApi}} } }
const money = new Intl.NumberFormat('es-MX', { style: 'currency', currency: 'MXN', minimumFractionDigits: 2 })
const totalPayments = (event: EventRecord) => event.payments.reduce((sum, item) => sum + (item.kind==='refund'?-item.amount:item.amount), 0)
const totalExpenses = (event: EventRecord) => event.expenses.reduce((sum, item) => sum + item.amount, 0)
function fromApiEvent(event:ApiEvent):EventRecord { return {id:event.id,version:event.version,unit:event.businessUnit,name:`Evento · ${event.venue}`,client:event.clientName,venue:event.venue,date:event.eventDate,price:event.agreedPrice==null?null:Number(event.agreedPrice),payrollBudget:Number(event.payrollBudget??0),expenseBudget:Number(event.extraExpenseBudget??0),payrollActual:0,status:event.operationalStatus==='Confirmado'||event.operationalStatus==='Completado'?'Confirmado':'Pendiente',payments:[],expenses:[]} }
function fromApiExpense(expense:ApiExpense):Expense { return {id:expense.id,name:expense.name,category:expense.category,amount:Number(expense.amount),paid:Number(expense.paidAmount),source:expense.source} }
function fromApiPayment(payment:ApiPayment):Payment{return{id:payment.id,date:payment.transactionDate,amount:Number(payment.amount),kind:payment.kind,version:payment.version}}
function FormModal({title,eyebrow,close,submit,children,submitLabel='Guardar'}:{title:string;eyebrow:string;close:()=>void;submit:(event:React.FormEvent)=>void;children:React.ReactNode;submitLabel?:string}){
  return <div className="modal-layer" role="dialog" aria-modal="true" aria-label={title}><button className="modal-backdrop" onClick={close}/><form className="event-modal compact-modal" onSubmit={submit}><div className="modal-head"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div><button type="button" aria-label="Cerrar" onClick={close}><X size={20}/></button></div><div className="form-grid">{children}</div><div className="modal-actions"><button type="button" onClick={close}>Cancelar</button><button className="primary" type="submit">{submitLabel}</button></div></form></div>
}
function ExpenseModal({close,save}:{close:()=>void;save:(value:{name:string;category:string;amount:string;expenseDate:string})=>Promise<void>}){
  const [form,setForm]=React.useState({name:'',category:'Otros gastos',amount:'',expenseDate:new Date().toISOString().slice(0,10)}),[error,setError]=React.useState('')
  const submit=async(event:React.FormEvent)=>{event.preventDefault();setError('');try{await save(form);close()}catch{setError('No se pudo guardar el gasto. Revisa los datos y la conexión.')}}
  return <FormModal title="Agregar gasto extra" eyebrow="Detalle del evento" close={close} submit={event=>void submit(event)}><label className="full">Nombre del gasto<input autoFocus required maxLength={200} value={form.name} onChange={event=>setForm({...form,name:event.target.value})}/></label><label>Categoría<select value={form.category} onChange={event=>setForm({...form,category:event.target.value})}><option>Otros gastos</option><option>Renta de equipo</option><option>Transporte</option><option>Alimentos</option></select></label><label>Monto MXN<input type="number" min="0.01" step="0.01" required value={form.amount} onChange={event=>setForm({...form,amount:event.target.value})}/></label><label className="full">Fecha<input type="date" required value={form.expenseDate} onChange={event=>setForm({...form,expenseDate:event.target.value})}/></label>{error&&<div className="form-error full" role="alert">{error}</div>}</FormModal>
}
function MovementModal({kind,eventName,close,save}:{kind:'payment'|'refund';eventName:string;close:()=>void;save:(amount:string,date:string)=>Promise<void>}){
  const [amount,setAmount]=React.useState(''),[date,setDate]=React.useState(new Date().toISOString().slice(0,10)),[error,setError]=React.useState('')
  const submit=async(event:React.FormEvent)=>{event.preventDefault();setError('');try{await save(Number(amount).toFixed(2),date);close()}catch{setError('No se pudo guardar el movimiento.')}}
  return <FormModal title={kind==='payment'?'Registrar abono':'Registrar reembolso'} eyebrow={eventName} close={close} submit={event=>void submit(event)} submitLabel={kind==='payment'?'Guardar abono':'Guardar reembolso'}><label className="full">Monto MXN<input autoFocus type="number" min="0.01" step="0.01" required value={amount} onChange={event=>setAmount(event.target.value)}/></label><label className="full">Fecha del movimiento<input type="date" required value={date} onChange={event=>setDate(event.target.value)}/></label>{error&&<div className="form-error full" role="alert">{error}</div>}</FormModal>
}
function BudgetModal({event,close,save}:{event:EventRecord;close:()=>void;save:(amount:string)=>Promise<void>}){
  const [amount,setAmount]=React.useState(event.payrollBudget.toFixed(2)),[error,setError]=React.useState('')
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setError('');try{await save(Number(amount).toFixed(2));close()}catch{setError('No se pudo actualizar el presupuesto de nómina.')}}
  return <FormModal title="Modificar presupuesto de nómina" eyebrow={event.name} close={close} submit={event=>void submit(event)}><label className="full">Presupuesto MXN<input autoFocus type="number" min="0" step="0.01" required value={amount} onChange={event=>setAmount(event.target.value)}/></label>{error&&<div className="form-error full" role="alert">{error}</div>}</FormModal>
}
function PriceModal({event,close,save}:{event:EventRecord;close:()=>void;save:(amount:string)=>Promise<void>}){
  const [amount,setAmount]=React.useState(event.price?.toFixed(2)??''),[error,setError]=React.useState('')
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setError('');try{await save(amount);close()}catch{setError('No se pudo actualizar el precio. Recarga el evento y vuelve a intentarlo.')}}
  return <FormModal title="Editar precio acordado" eyebrow={event.name} close={close} submit={event=>void submit(event)} submitLabel="Guardar precio"><label className="full">Precio MXN<input autoFocus type="number" min="0" step="0.01" value={amount} onChange={event=>setAmount(event.target.value)} placeholder="Puede quedar pendiente"/></label>{error&&<div className="form-error full" role="alert">{error}</div>}</FormModal>
}
function MonthModal({close,save}:{close:()=>void;save:(month:string)=>Promise<void>}){
  const [month,setMonth]=React.useState(new Date().toISOString().slice(0,7)),[error,setError]=React.useState('')
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setError('');try{await save(month);close()}catch{setError('No pudimos generar el reporte.')}}
  return <FormModal title="Exportar reporte mensual" eyebrow="Finanzas" close={close} submit={event=>void submit(event)} submitLabel="Descargar Excel"><label className="full">Mes del reporte<input type="month" required value={month} onChange={event=>setMonth(event.target.value)}/></label>{error&&<div className="form-error full" role="alert">{error}</div>}</FormModal>
}
function Sidebar({ view, setView, mobileNav, close, user, logout }: { view: View; setView: (view: View) => void; mobileNav: boolean; close: () => void; user:SessionUser; logout:()=>void }) {
  const go = (next: View) => { setView(next); close() }
  return <><aside className={mobileNav?'sidebar open':'sidebar'}><div className="brand"><div className="brand-mark">S</div><div><strong>SPL</strong><span>{user.role==='coordinator'?'Coordinación de eventos':'Control financiero'}</span></div><button className="mobile-close" onClick={close}><X size={20}/></button></div><nav>{user.role!=='coordinator'&&<button className={view==='dashboard'?'active':''} onClick={()=>go('dashboard')}><LayoutDashboard size={19}/>Panel general</button>}<button className={view==='events'?'active':''} onClick={()=>go('events')}><CalendarDays size={19}/>Eventos</button>{user.role!=='coordinator'&&<><button className={view==='finance'?'active':''} onClick={()=>go('finance')}><WalletCards size={19}/>Finanzas</button><button className={view==='payroll'?'active':''} onClick={()=>go('payroll')}><Users size={19}/>Nómina</button></>}<button className={view==='settings'?'active':''} onClick={()=>go('settings')}><Settings size={19}/>Configuración</button></nav><button className="user-card" onClick={logout}><div className="avatar">{user.displayName.split(' ').map(value=>value[0]).slice(0,2).join('')}</div><div><strong>{user.displayName}</strong><span>{user.role==='coordinator'?'Coordinación':'Administrador'} · Cerrar sesión</span></div><MoreHorizontal size={18}/></button></aside>{mobileNav&&<button className="backdrop" onClick={close}/>}</>
}
function ScopeControl({ value, onChange }: { value: Scope; onChange: (scope: Scope) => void }) { return <div className="scope-control"><span>Vista de negocio</span><label><select value={value} onChange={e => onChange(e.target.value as Scope)}><option>SPL consolidado</option><option>SPL - eventos propios</option><option>5to Elemento</option></select><ChevronDown size={16}/></label></div> }
function Dashboard({ scope, setScope,events }: { scope: Scope; setScope: (scope: Scope) => void;events:EventRecord[] }) {
  const visible=events.filter(event=>scope==='SPL consolidado'||(scope==='SPL - eventos propios'?event.unit==='SPL':event.unit==='5to Elemento')),received=visible.reduce((sum,event)=>sum+totalPayments(event),0),expenses=visible.reduce((sum,event)=>sum+totalExpenses(event),0),payroll=visible.reduce((sum,event)=>sum+event.payrollActual,0),agreed=visible.reduce((sum,event)=>sum+(event.price??0),0),receivable=Math.max(agreed-received,0),contribution=agreed-expenses-payroll
  const metrics = [{label:'Cobros del mes',value:received,change:`${visible.length} eventos`,trend:'neutral',caption:'movimientos registrados'},{label:'Gastos del mes',value:expenses+payroll,change:`${visible.reduce((sum,event)=>sum+event.expenses.length,0)} registros`,trend:'neutral',caption:'costos incurridos'},{label:'Saldo por cobrar',value:receivable,change:`${visible.filter(event=>(event.price??0)>totalPayments(event)).length} eventos`,trend:'neutral',caption:'pendiente de clientes'},{label:'Contribución directa',value:contribution,change:agreed?`${((contribution/agreed)*100).toFixed(1)}%`:'0%',trend:'neutral',caption:'antes de gastos compartidos'}]
  const categoryTotal=expenses+payroll,categoryAmount=(name:string)=>visible.flatMap(event=>event.expenses).filter(expense=>expense.category===name).reduce((sum,expense)=>sum+expense.amount,0),share=(value:number)=>categoryTotal?Math.round(value/categoryTotal*100):0,rent=categoryAmount('Renta de equipo'),transport=categoryAmount('Transporte'),other=Math.max(expenses-rent-transport,0)
  const categoryItems=[['Nómina de eventos',payroll,share(payroll),'#ea580c'],['Renta de equipo',rent,share(rent),'#fb923c'],['Transporte',transport,share(transport),'#38bdf8'],['Otros gastos',other,share(other),'#64748b']] as const
  const alerts=visible.filter(event=>totalExpenses(event)>event.expenseBudget||event.payrollActual>event.payrollBudget)
  return <div className="content"><section className="page-heading"><div><p className="eyebrow">Panel financiero</p><h1>Buen día, Oscar</h1><p>Este es el estado financiero y operativo de tu negocio.</p></div><ScopeControl value={scope} onChange={setScope}/></section><section className="metrics-grid">{metrics.map(metric=><article className="metric-card" key={metric.label}><div className="metric-title"><span>{metric.label}</span><CircleDollarSign size={19}/></div><strong>{money.format(metric.value)}</strong><div className={`metric-foot ${metric.trend}`}><b>{metric.change}</b><span>{metric.caption}</span></div></article>)}</section><section className="main-grid"><article className="panel cashflow-panel"><div className="panel-head"><div><h2>Flujo de efectivo</h2><p>Cobros y pagos registrados</p></div></div><div className="empty-state">{received?'Los movimientos ya se reflejan en los indicadores':'Sin movimientos todavía'}</div></article><article className="panel category-panel"><div className="panel-head"><div><h2>Gasto por categoría</h2><p>Costos incurridos</p></div></div><div className="donut-row"><div className="donut"><div><strong>{money.format(categoryTotal)}</strong><span>Total</span></div></div></div><div className="category-list">{categoryItems.map(item=><div key={item[0]}><span><i style={{background:item[3]}}/>{item[0]}</span><strong>{money.format(item[1])}</strong><small>{item[2]}%</small></div>)}</div></article></section><section className="lower-grid"><article className="panel events-panel"><div className="panel-head"><div><h2>Próximos eventos</h2><p>Agenda consolidada de ambas unidades</p></div></div>{visible.length===0?<div className="empty-state">Aún no hay eventos</div>:<div className="event-list">{visible.slice(0,5).map(event=><div className="event-row" key={event.id}><div className="date-box"><strong>{event.date.slice(8)}</strong><span>{new Date(`${event.date}T12:00:00`).toLocaleDateString('es-MX',{month:'short'}).toUpperCase()}</span></div><i className={`event-line ${event.unit==='5to Elemento'?'blue':''}`}/><div className="event-info"><strong>{event.name}</strong><span>{event.unit}</span></div><span className={`status ${event.status==='Confirmado'?'confirmed':''}`}>{event.status}</span></div>)}</div>}</article><article className="panel budget-panel"><div className="panel-head"><div><h2>Alertas de presupuesto</h2><p>Eventos que requieren atención</p></div><span className="count">{alerts.length}</span></div>{alerts.length===0?<div className="empty-state">Sin alertas de presupuesto</div>:alerts.map(event=><div className="alert-item" key={event.id}><div><strong>{event.name}</strong><span>Revisa nómina o gastos extra</span></div></div>)}</article></section></div>
}
function EventsPage({ events, setEvents, selectedId, setSelectedId, openCreate, loadState, retry, role }: { events: EventRecord[]; setEvents: React.Dispatch<React.SetStateAction<EventRecord[]>>; selectedId: string; setSelectedId: (id:string)=>void; openCreate:()=>void; loadState:'loading'|'ready'|'error'; retry:()=>void; role:SessionUser['role'] }) {
  const [filter,setFilter]=React.useState<'Todos'|Unit>('Todos'),[expenseOpen,setExpenseOpen]=React.useState(false); const selected=events.find(event=>event.id===selectedId) ?? events[0]; const filtered=events.filter(event=>filter==='Todos'||event.unit===filter)
  React.useEffect(()=>{const update=()=>setEvents(current=>[...current]);window.addEventListener('spl-financial-change',update);return()=>window.removeEventListener('spl-financial-change',update)},[setEvents])
  React.useEffect(()=>{if(!selectedId||role==='coordinator')return;let active=true;Promise.all([eventApi.listExpenses(selectedId),eventApi.listPayments(selectedId)]).then(([expenses,payments])=>{if(active)setEvents(current=>current.map(event=>event.id===selectedId?{...event,expenses:expenses.map(fromApiExpense),payments:payments.map(fromApiPayment)}:event))}).catch(()=>{});return()=>{active=false}},[selectedId,setEvents,role])
  const addExpense=async(value:{name:string;category:string;amount:string;expenseDate:string})=>{if(!selected)return;const item=await eventApi.addExpense(selected.id,{...value,amount:Number(value.amount).toFixed(2)});setEvents(current=>current.map(event=>event.id===selected.id?{...event,expenses:[...event.expenses,fromApiExpense(item)]}:event))}
  return <div className="content events-workspace"><section className="page-heading"><div><p className="eyebrow">{role==='owner'?'Operación y finanzas':'Agenda operativa'}</p><h1>Eventos</h1><p>{role==='owner'?'Consulta cada evento y abre los registros que explican sus totales.':'Administra únicamente la información operativa de 5to Elemento.'}</p></div><button className="primary page-action" onClick={openCreate}><Plus size={18}/>Nuevo evento</button></section>{loadState==='error'&&<div className="connection-banner" role="alert"><div><strong>No pudimos cargar los eventos</strong><span>Revisa tu conexión. Tus datos no fueron modificados.</span></div><button onClick={retry}>Reintentar</button></div>}{loadState==='loading'&&<div className="loading-state" aria-live="polite">Cargando eventos...</div>}{loadState==='ready'&&<><div className="event-toolbar">{role==='owner'?<div className="segmented">{(['Todos','SPL','5to Elemento'] as const).map(item=><button className={filter===item?'active':''} onClick={()=>setFilter(item)} key={item}>{item}</button>)}</div>:<span>5to Elemento</span>}<span>{filtered.length} eventos</span></div>{events.length===0?<div className="panel no-events"><CalendarDays size={24}/><strong>Aún no hay eventos</strong><span>Crea la primera reservación para comenzar.</span><button className="primary" onClick={openCreate}>Nuevo evento</button></div>:<section className="event-workspace-grid"><article className={`panel event-table-panel ${role==='coordinator'?'operational':''}`}><div className="event-table-head"><span>Evento</span><span>Fecha</span><span>Estado</span>{role==='owner'&&<span>Saldo</span>}</div>{filtered.map(event=>{const balance=Math.max((event.price??0)-totalPayments(event),0);return <button className={`event-table-row ${selected?.id===event.id?'selected':''}`} onClick={()=>setSelectedId(event.id)} key={event.id}><div><i className={event.unit==='SPL'?'unit-spl':'unit-5to'}/><span><strong>{event.name}</strong><small>{event.client} · {event.id}</small></span></div><span>{new Date(`${event.date}T12:00:00`).toLocaleDateString('es-MX',{day:'2-digit',month:'short'})}</span><span className={`status ${event.status==='Confirmado'?'confirmed':''}`}>{event.status}</span>{role==='owner'&&<b>{event.price===null?'Precio pendiente':money.format(balance)}</b>}</button>})}</article>{selected&&<EventDetail event={selected} addExpense={()=>setExpenseOpen(true)} role={role}/>}</section>}</>}{expenseOpen&&selected&&<ExpenseModal close={()=>setExpenseOpen(false)} save={addExpense}/>}</div>
}
function EventDetail({event,addExpense,role}:{event:EventRecord;addExpense:()=>void;role:SessionUser['role']}) {
  const [,refresh]=React.useState(0),[movement,setMovement]=React.useState<'payment'|'refund'|null>(null),[budgetOpen,setBudgetOpen]=React.useState(false),[priceOpen,setPriceOpen]=React.useState(false),[error,setError]=React.useState('')
  const received=totalPayments(event), extras=totalExpenses(event), totalCost=event.payrollActual+extras, balance=event.price===null?null:Math.max(event.price-received,0)
  const recordPayment=async(kind:'payment'|'refund',amount:string,date:string)=>{const item=await eventApi.addPayment(event.id,{transactionDate:date,amount,kind,idempotencyKey:crypto.randomUUID()});event.payments.push(fromApiPayment(item));refresh(value=>value+1);window.dispatchEvent(new Event('spl-financial-change'))}
  const settle=async(expense:Expense)=>{const pending=expense.amount-expense.paid;if(pending<=0)return;setError('');try{const result=await eventApi.settleExpense(expense.id,{paymentDate:new Date().toISOString().slice(0,10),amount:pending.toFixed(2),idempotencyKey:crypto.randomUUID()});expense.paid=Number(result.paidAmount);refresh(value=>value+1);window.dispatchEvent(new Event('spl-financial-change'))}catch{setError('No se pudo marcar el gasto como pagado.')}}
  const updateBudget=async(amount:string)=>{const updated=await eventApi.updatePayrollBudget(event.id,amount);event.payrollBudget=Number(updated.payrollBudget);refresh(value=>value+1)}
  const updatePrice=async(amount:string)=>{const updated=await eventApi.updateAgreedPrice(event.id,{agreedPrice:amount.trim()?Number(amount).toFixed(2):null,version:event.version});event.price=updated.agreedPrice===null?null:Number(updated.agreedPrice);event.version=updated.version;refresh(value=>value+1);window.dispatchEvent(new Event('spl-financial-change'))}
  return <article className="panel event-detail">
    <div className="detail-head"><div><span className={`unit-pill ${event.unit==='SPL'?'spl':''}`}>{event.unit}</span><h2>{event.name}</h2><p>{event.client} · {event.venue}</p></div><button className="icon-button"><MoreHorizontal size={20}/></button></div>
    <div className="detail-date"><CalendarDays size={17}/><span><small>Fecha del evento</small><strong>{new Date(`${event.date}T12:00:00`).toLocaleDateString('es-MX',{weekday:'long',day:'numeric',month:'long',year:'numeric'})}</strong></span></div>
    {role!=='coordinator'?<>
      <div className="detail-money"><div><span>Precio acordado</span><strong>{event.price===null?'Precio pendiente':money.format(event.price)}</strong><button className="inline-edit" onClick={()=>setPriceOpen(true)}>Editar precio acordado</button></div><div><span>Cobros netos</span><strong className="green">{money.format(received)}</strong></div><div><span>Saldo por cobrar</span><strong>{balance===null?'Sin calcular':money.format(balance)}</strong></div></div>
      <div className="movement-actions"><button onClick={()=>setMovement('payment')}><Plus size={14}/>Registrar abono</button><button onClick={()=>setMovement('refund')}>Registrar reembolso</button></div>
      <div className="payment-list">{event.payments.length===0?<span>Sin movimientos de cliente</span>:event.payments.map(payment=><div key={payment.id}><span>{payment.kind==='refund'?'Reembolso':'Abono'} · {payment.date}</span><strong className={payment.kind==='refund'?'refund':''}>{payment.kind==='refund'?'-':'+'}{money.format(payment.amount)}</strong></div>)}</div>
      <div className="cost-summary"><div><span>Nómina</span><strong>{money.format(event.payrollActual)}</strong><small>Presupuesto {money.format(event.payrollBudget)}</small><button className="inline-edit" onClick={()=>setBudgetOpen(true)}>Modificar presupuesto</button></div><div><span>Gastos extra</span><strong>{money.format(extras)}</strong><small>Presupuesto {money.format(event.expenseBudget)}</small></div><div className="total"><span>Gasto total del evento</span><strong>{money.format(totalCost)}</strong><small>Nómina + gastos extra</small></div></div>
      <div className="detail-section-head"><div><h3>Detalle de gastos extra</h3><span>{event.expenses.length} registros</span></div><button onClick={addExpense}><Plus size={15}/>Agregar</button></div>
      {error&&<div className="form-error" role="alert">{error}</div>}<div className="expense-detail-list">{event.expenses.length===0?<div className="empty-state"><Check size={20}/><strong>Sin gastos registrados</strong><span>Agrega cada gasto por separado para explicar el total.</span></div>:event.expenses.map(expense=><div key={expense.id}><span><strong>{expense.name}</strong><small>{expense.source==='payroll'?'Gasto originado en nómina':expense.category}</small></span><span><strong>{money.format(expense.amount)}</strong><small>{expense.paid>=expense.amount?'Pagado':'Pendiente'}</small>{expense.paid<expense.amount&&expense.source!=='payroll'&&<button className="settle-button" onClick={()=>void settle(expense)}>Marcar como pagado</button>}</span></div>)}</div>
    </>:<div className="operational-note"><strong>Información operativa</strong><span>La información financiera está protegida para este perfil.</span></div>}
    {movement&&<MovementModal kind={movement} eventName={event.name} close={()=>setMovement(null)} save={(amount,date)=>recordPayment(movement,amount,date)}/>} {budgetOpen&&<BudgetModal event={event} close={()=>setBudgetOpen(false)} save={updateBudget}/>} {priceOpen&&<PriceModal event={event} close={()=>setPriceOpen(false)} save={updatePrice}/>}
  </article>
}
function CreateEventModal({close,save,count,role}:{close:()=>void;save:(event:EventRecord)=>Promise<void>;count:number;role:SessionUser['role']}) {
  const [form,setForm]=React.useState({unit:(role==='coordinator'?'5to Elemento':'SPL') as Unit,client:'',venue:'',date:'',price:'',payrollBudget:'',expenseBudget:''}); const set=(key:keyof typeof form,value:string)=>setForm(current=>({...current,[key]:value}))
  const [saving,setSaving]=React.useState(false),[error,setError]=React.useState(''); const submit=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);setError('');try{await save({id:`draft-${count+1}`,version:1,unit:form.unit,name:`Evento · ${form.venue}`,client:form.client,venue:form.venue,date:form.date,price:form.price?Number(form.price):null,payrollBudget:Number(form.payrollBudget)||0,expenseBudget:Number(form.expenseBudget)||0,payrollActual:0,status:'Pendiente',payments:[],expenses:[]})}catch{setError('No se pudo crear el evento. Revisa la conexión antes de volver a intentarlo.')}finally{setSaving(false)}}
  return <div className="modal-layer" role="dialog"><button className="modal-backdrop" onClick={close}/><form className="event-modal" onSubmit={submit}><div className="modal-head"><div><p className="eyebrow">Nuevo registro</p><h2>Crear evento</h2></div><button type="button" onClick={close}><X size={20}/></button></div><p>Captura primero la información esencial. Los cobros y gastos se agregan desde el detalle del evento.</p>{error&&<div className="form-error" role="alert">{error}</div>}<div className="form-grid"><label className="full">Unidad<select value={form.unit} disabled={role==='coordinator'} onChange={e=>set('unit',e.target.value)}><option>SPL</option><option>5to Elemento</option></select></label><label>Cliente<input value={form.client} onChange={e=>set('client',e.target.value)} placeholder="Nombre del cliente" required/></label><label>Lugar<input value={form.venue} onChange={e=>set('venue',e.target.value)} placeholder="Lugar del evento" required/></label><label>Fecha<input type="date" value={form.date} onChange={e=>set('date',e.target.value)} required/></label>{role==='owner'&&<><label>Precio acordado<input type="number" min="0" step="0.01" value={form.price} onChange={e=>set('price',e.target.value)} placeholder="Puede quedar pendiente"/></label><label>Presupuesto de nómina<input type="number" min="0" step="0.01" value={form.payrollBudget} onChange={e=>set('payrollBudget',e.target.value)}/></label><label>Presupuesto de gastos extra<input type="number" min="0" step="0.01" value={form.expenseBudget} onChange={e=>set('expenseBudget',e.target.value)}/></label></>}</div><div className="modal-actions"><button type="button" onClick={close}>Cancelar</button><button className="primary" type="submit" disabled={saving}>{saving?'Guardando...':'Crear evento'}</button></div></form></div>
}
function FinancePage({events}:{events:EventRecord[]}){
  const [records,setRecords]=React.useState(events),[payroll,setPayroll]=React.useState<ApiPayroll[]>([]),[state,setState]=React.useState<'loading'|'ready'|'error'>('loading')
  React.useEffect(()=>{let active=true;setState('loading');Promise.all([Promise.all(events.map(async event=>{const [expenses,payments]=await Promise.all([eventApi.listExpenses(event.id),eventApi.listPayments(event.id)]);return{...event,expenses:expenses.map(fromApiExpense),payments:payments.map(fromApiPayment)}})),payrollApi.list()]).then(([loaded,workers])=>{if(active){setRecords(loaded);setPayroll(workers);setState('ready')}}).catch(()=>{if(active)setState('error')});return()=>{active=false}},[events])
  const enriched=records.map(event=>({...event,payrollActual:payroll.flatMap(item=>item.allocations).filter(item=>item.eventId===event.id).reduce((sum,item)=>sum+Number(item.amount),0)})),summary=calculateFinanceSummary(enriched)
  return <div className="content finance-page"><section className="page-heading"><div><p className="eyebrow">Control financiero</p><h1>Finanzas</h1><p>Consulta saldos, obligaciones y contribución directa con detalle por evento.</p></div></section>{state==='error'&&<div className="connection-banner" role="alert"><div><strong>No pudimos cargar las finanzas</strong><span>El backend no respondió. Intenta de nuevo cuando la conexión esté disponible.</span></div></div>}<section className="finance-metrics"><article><span>Precio acordado</span><strong>{money.format(Number(summary.agreed))}</strong><small>{records.length} eventos</small></article><article><span>Cobros netos</span><strong className="green">{money.format(Number(summary.received))}</strong><small>Abonos menos reembolsos</small></article><article><span>Por cobrar</span><strong>{money.format(Number(summary.receivable))}</strong><small>Saldo de clientes</small></article><article><span>Por pagar</span><strong className="orange">{money.format(Number(summary.payable))}</strong><small>Gastos pendientes</small></article></section><section className="finance-layout"><article className="panel finance-summary"><h2>Resultado directo</h2><div><span>Ingresos acordados</span><strong>{money.format(Number(summary.agreed))}</strong></div><div><span>Nómina asignada</span><strong>-{money.format(Number(summary.payroll))}</strong></div><div><span>Gastos de eventos</span><strong>-{money.format(Number(summary.expenses))}</strong></div><div className="finance-total"><span>Contribución directa</span><strong>{money.format(Number(summary.contribution))}</strong></div></article><article className="panel finance-table"><div className="finance-table-head"><h2>Detalle por evento</h2><span>{state==='loading'?'Actualizando...':'Datos conciliados'}</span></div><div className="finance-scroll"><table><thead><tr><th>Evento</th><th>Unidad</th><th>Precio</th><th>Cobrado</th><th>Costos</th><th>Contribución</th></tr></thead><tbody>{enriched.map(event=>{const received=totalPayments(event),cost=totalExpenses(event)+event.payrollActual,contribution=(event.price??0)-cost;return <tr key={event.id}><td><strong>{event.client}</strong><small>{event.venue}</small></td><td>{event.unit}</td><td>{event.price===null?'Pendiente':money.format(event.price)}</td><td>{money.format(received)}</td><td>{money.format(cost)}</td><td className={contribution<0?'negative':'positive'}>{event.price===null?'Sin calcular':money.format(contribution)}</td></tr>})}</tbody></table></div></article></section></div>
}
function SettingsPage({user}:{user:SessionUser}){
  const [preferences,setPreferences]=React.useState<Preferences>(()=>parsePreferences(localStorage.getItem('spl_preferences'))),[saved,setSaved]=React.useState(false),[connection,setConnection]=React.useState<'checking'|'online'|'offline'>('checking')
  React.useEffect(()=>{healthApi.status().then(()=>setConnection('online')).catch(()=>setConnection('offline'))},[])
  const save=()=>{localStorage.setItem('spl_preferences',JSON.stringify(preferences));document.documentElement.dataset.compact=preferences.compactMode?'true':'false';setSaved(true);setTimeout(()=>setSaved(false),1800)}
  const reset=()=>{setPreferences(defaultPreferences);localStorage.removeItem('spl_preferences');document.documentElement.dataset.compact='false'}
  return <div className="content settings-page"><section className="page-heading"><div><p className="eyebrow">Preferencias y acceso</p><h1>Configuración</h1><p>Administra tu experiencia, conexión y datos de la cuenta.</p></div></section><section className="settings-grid"><article className="panel settings-card"><div className="settings-title"><ShieldCheck size={20}/><div><h2>Cuenta y seguridad</h2><p>Sesión individual autorizada</p></div></div><dl><div><dt>Nombre</dt><dd>{user.displayName}</dd></div><div><dt>Correo</dt><dd>{user.email}</dd></div><div><dt>Perfil</dt><dd>{user.role==='coordinator'?'Coordinación':'Administrador'}</dd></div><div><dt>Duración de sesión</dt><dd>180 días en este equipo</dd></div></dl></article><article className="panel settings-card"><div className="settings-title"><Wifi size={20}/><div><h2>Conexión</h2><p>Estado de servicios locales</p></div></div><div className={`connection-status ${connection}`}><i/><span>{connection==='checking'?'Comprobando conexión':connection==='online'?'Backend conectado':'Backend sin conexión'}</span></div><div className="settings-fact"><Database size={17}/><span><strong>Datos centralizados</strong><small>La interfaz no almacena contraseñas ni secretos de Google.</small></span></div></article><form className="panel preferences-card" onSubmit={event=>{event.preventDefault();save()}}><h2>Preferencias</h2><div className="preferences-fields"><label>Unidad predeterminada<select value={preferences.defaultUnit} onChange={event=>setPreferences({...preferences,defaultUnit:event.target.value as Preferences['defaultUnit']})}><option>SPL</option><option>5to Elemento</option></select></label><label>Mes sugerido para reportes<select value={preferences.reportMonth} onChange={event=>setPreferences({...preferences,reportMonth:event.target.value as Preferences['reportMonth']})}><option value="current">Mes actual</option><option value="previous">Mes anterior</option></select></label><label className="toggle-row"><span><strong>Vista compacta</strong><small>Reduce espacios en tablas extensas.</small></span><input type="checkbox" checked={preferences.compactMode} onChange={event=>setPreferences({...preferences,compactMode:event.target.checked})}/></label></div><div className="settings-actions"><button type="button" onClick={reset}>Restablecer</button><button className="primary">{saved?'Guardado':'Guardar cambios'}</button></div></form></section></div>
}
function LoginScreen({onLogin}:{onLogin:(user:SessionUser)=>void}){
  const [email,setEmail]=React.useState(''),[password,setPassword]=React.useState(''),[error,setError]=React.useState(''),[busy,setBusy]=React.useState(false),[testBusy,setTestBusy]=React.useState(false),[desktopGoogle,setDesktopGoogle]=React.useState<boolean|null|undefined>(undefined),[testLogin,setTestLogin]=React.useState(false)
  const loginAttempt=React.useRef(0)
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{onLogin(await authApi.login(email,password))}catch{setError('Correo o contraseña incorrectos.')}finally{setBusy(false)}}
  const loginWithDesktopGoogle=async()=>{const attempt=++loginAttempt.current;setBusy(true);setError('');try{const {flowId}=await desktopGoogleApi.start(),user=await waitForDesktopGoogle(flowId,desktopGoogleApi.status);if(loginAttempt.current===attempt)onLogin(user)}catch{if(loginAttempt.current===attempt)setError('No pudimos completar el acceso con Google. Inténtalo nuevamente.')}finally{if(loginAttempt.current===attempt)setBusy(false)}}
  const enterTestMode=async()=>{loginAttempt.current++;setTestBusy(true);setError('');try{onLogin(await testLoginApi.login())}catch{setError('No pudimos iniciar el modo de pruebas.')}finally{setTestBusy(false)}}
  const googleButton=React.useRef<HTMLDivElement>(null)
  React.useEffect(()=>{
    let active=true
    desktopGoogleApi.config().then(result=>{if(active)setDesktopGoogle(result.enabled)}).catch(()=>{if(active)setDesktopGoogle(false)})
    testLoginApi.config().then(result=>{if(active)setTestLogin(result.enabled)}).catch(()=>{})
    return()=>{active=false}
  },[])
  React.useEffect(()=>{
    if(desktopGoogle!==null)return
    const clientId=import.meta.env.VITE_GOOGLE_CLIENT_ID
    if(!clientId)return
    const render=()=>{
      if(!window.google||!googleButton.current)return
      window.google.accounts.id.initialize({client_id:clientId,callback:async({credential})=>{
        setBusy(true)
        setError('')
        try{onLogin(await authApi.google(credential))}catch{setError('No pudimos autorizar esta cuenta de Google.')}finally{setBusy(false)}
      }})
      window.google.accounts.id.renderButton(googleButton.current,{theme:'filled_black',size:'large',text:'continue_with',shape:'rectangular',width:342,locale:'es'})
    }
    const script=document.createElement('script')
    script.src='https://accounts.google.com/gsi/client'
    script.async=true
    script.onload=render
    document.head.appendChild(script)
    return()=>script.remove()
  },[desktopGoogle,onLogin])
  return <main className="login-page"><section className="login-panel"><div className="login-brand"><div className="brand-mark">S</div><div><strong>SPL</strong><span>Control de eventos y finanzas</span></div></div><div className="login-copy"><p className="eyebrow">Acceso seguro</p><h1>Bienvenido</h1><p>Ingresa con una cuenta autorizada para continuar.</p></div>{desktopGoogle===true?<button className="desktop-google-button" type="button" disabled={busy} onClick={()=>void loginWithDesktopGoogle()}>{busy?'Esperando autorización...':'Continuar con Google nuevamente'}</button>:desktopGoogle===false?<div className="login-error" role="alert">No se pudo verificar Google para Windows. Revisa la configuración o vuelve a abrir la aplicación.</div>:<div className="google-button" ref={googleButton}/>} {testLogin&&<button className="test-login-button" type="button" disabled={testBusy} onClick={()=>void enterTestMode()}>{testBusy?'Abriendo modo de pruebas...':'Entrar en modo de pruebas'}</button>}<div className="login-divider"><span>o usa tu cuenta existente</span></div><form onSubmit={submit}><label>Correo electrónico<input type="email" autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Contraseña<input type="password" autoComplete="current-password" minLength={8} maxLength={128} value={password} onChange={e=>setPassword(e.target.value)} required/></label>{error&&<div className="login-error" role="alert">{error}</div>}<button className="primary" disabled={busy}>{busy?'Verificando...':'Iniciar sesión'}</button></form><small>La sesión permanece activa en este equipo de confianza.</small></section></main>
}
function App() {
  const [session,setSession]=React.useState<SessionUser|null|undefined>(undefined), [view,setView]=React.useState<View>('dashboard'), [scope,setScope]=React.useState<Scope>('SPL consolidado'), [mobileNav,setMobileNav]=React.useState(false), [creating,setCreating]=React.useState(false),[exporting,setExporting]=React.useState(false), [events,setEvents]=React.useState<EventRecord[]>([]), [selectedId,setSelectedId]=React.useState(''), [loadState,setLoadState]=React.useState<'loading'|'ready'|'error'>('loading')
  const load=React.useCallback(async()=>{setLoadState('loading');try{const loaded=(await eventApi.list()).map(fromApiEvent);
      if(session?.role!=='coordinator') {
        const labor=await payrollApi.list();
        await Promise.all(loaded.map(async event=>{const [expenses,payments]=await Promise.all([eventApi.listExpenses(event.id),eventApi.listPayments(event.id)]);event.expenses=expenses.map(fromApiExpense);event.payments=payments.map(fromApiPayment);event.payrollActual=labor.flatMap(entry=>entry.allocations).filter(a=>a.eventId===event.id).reduce((sum,a)=>sum+Number(a.amount),0)}))
      }
      setEvents(loaded);setSelectedId(current=>loaded.some(event=>event.id===current)?current:(loaded[0]?.id??''));setLoadState('ready')}catch{setLoadState('error')}},[session?.role])
  React.useEffect(()=>{authApi.me().then(user=>{const visibleUser=user.role==='admin'?{...user,role:'owner' as const}:user;setSession(visibleUser);if(visibleUser.role==='coordinator')setView('events')}).catch(()=>setSession(null))},[])
  React.useEffect(()=>{if(session)void load()},[load,session])
  const login=React.useCallback((user:SessionUser)=>{const visibleUser=user.role==='admin'?{...user,role:'owner' as const}:user;setSession(visibleUser);setView(visibleUser.role==='coordinator'?'events':'dashboard')},[])
  const logout=async()=>{try{await authApi.logout()}finally{setSession(null);setEvents([]);setSelectedId('');setCreating(false);setView('dashboard')}}
  const exportMonth=async(month:string)=>{const blob=await reportApi.monthly(month),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`SPL-reporte-${month}.xlsx`;link.click();URL.revokeObjectURL(url)}
  const save=async(event:EventRecord)=>{if(!session)return;const operational:CreateEventInput={businessUnit:event.unit,clientName:event.client,clientPhone:null,venue:event.venue,eventDate:event.date,operationalStatus:'Pendiente',operationalNotes:null};const input:CreateEventInput=session.role!=='coordinator'?{...operational,financialNotes:null,agreedPrice:event.price===null?null:event.price.toFixed(2),payrollBudget:event.payrollBudget.toFixed(2),extraExpenseBudget:event.expenseBudget.toFixed(2)}:operational;const created=fromApiEvent(await eventApi.create(input));setEvents(current=>[created,...current]);setSelectedId(created.id);setCreating(false);setView('events')}
  if(session===undefined)return <main className="session-loading" aria-live="polite">Verificando tu sesión...</main>
  if(session===null)return <LoginScreen onLogin={login}/>
  const page=view==='dashboard'&&session.role!=='coordinator'?<Dashboard scope={scope} setScope={setScope} events={events}/>:view==='finance'&&session.role!=='coordinator'?<FinancePage events={events}/>:view==='payroll'&&session.role!=='coordinator'?<PayrollPage events={events} onChanged={()=>void load()}/>:view==='settings'?<SettingsPage user={session}/>:<EventsPage events={events} setEvents={setEvents} selectedId={selectedId} setSelectedId={setSelectedId} openCreate={()=>setCreating(true)} loadState={loadState} retry={()=>void load()} role={session.role}/>
  return <div className="app-shell"><Sidebar view={view} setView={setView} mobileNav={mobileNav} close={()=>setMobileNav(false)} user={session} logout={()=>void logout()}/><main><header><button className="menu-button" onClick={()=>setMobileNav(true)}><Menu/></button><div className="search"><Search size={18}/><input placeholder="Buscar evento o cliente..."/></div>{session.role!=='coordinator'&&<button className="export" onClick={()=>setExporting(true)}><Download size={17}/>Exportar mes</button>}<button className="primary" onClick={()=>setCreating(true)}><Plus size={18}/>Nuevo evento</button></header>{page}</main>{creating&&<CreateEventModal close={()=>setCreating(false)} save={save} count={events.length} role={session.role}/>} {exporting&&<MonthModal close={()=>setExporting(false)} save={exportMonth}/>}</div>
}
ReactDOM.createRoot(document.getElementById('app')!).render(<React.StrictMode><App/></React.StrictMode>)
