import { PayrollPage } from './payroll/PayrollPage'
import { allocatePayrollCents, payrollAllocationUnit } from './payroll/cash-allocation'
import { CostBreakdown, WeeklyComparison, type DashboardCost } from './dashboard/DashboardCharts'
import { PayrollMonitoring } from './dashboard/PayrollMonitoring'
import { amountInPeriod, dashboardPeriod, inPeriod, isCalendarDate } from './dashboard/period'
import { PeriodSelector, type SavedPeriod } from './dashboard/PeriodSelector'
import { paidAmounts } from './dashboard/weekly'
import { QuickExpenseModal } from './QuickExpenseModal'
import { DirectIncomeModal } from './DirectIncomeModal'
import { FinanceExpenses } from './FinanceExpenses'
import { FinanceIncomeLedger } from './FinanceIncomeLedger'
import { financePeriodData } from './finance-model'
import { EXPENSE_CATEGORIES, DEFAULT_EXPENSE_CATEGORY } from './expense-categories'
import React from 'react'
import ReactDOM from 'react-dom/client'
import { CalendarDays, Check, ChevronDown, CircleDollarSign, Database, Download, LayoutDashboard, Menu, MoreHorizontal, Plus, Search, Settings, ShieldCheck, Trash2, Users, WalletCards, Wifi, X } from 'lucide-react'
import { authApi, desktopGoogleApi, directIncomeApi, eventApi, healthApi, payrollApi, quickExpenseApi, reportApi, testLoginApi, weeklyPayrollApi, type ApiDirectIncome, type ApiEvent, type ApiExpense, type ApiPayment, type ApiPayroll, type ApiQuickExpense, type ApiWeeklyPayroll, type CreateEventInput, type SessionUser } from './api'
import {openDesktopAuthorization,waitForDesktopGoogle} from './desktop-auth'
import {defaultPreferences,parsePreferences,type Preferences} from './settings'
import './styles.css'
type Scope = 'Todos' | 'SPL' | '5to Elemento'
type View = 'dashboard' | 'events' | 'finance' | 'payroll' | 'settings'
type Unit = 'SPL' | '5to Elemento'
type Expense = { id: string; name: string; category: string; date: string; amount: number; paid: number; source?: 'payroll'; notes?:string|null; cashDate?: string; cashPayments?: {date:string;amount:number}[] }
type Payment = { id: string; date: string; amount: number; kind?:'payment'|'refund'; version?:number }
type EventRecord = { id: string; version:number; unit: Unit; name: string; client: string; venue: string; date: string; price: number | null; payrollBudget: number; expenseBudget: number; payrollActual: number; laborItems:DashboardCost[]; status: 'Confirmado' | 'Pendiente'; payments: Payment[]; expenses: Expense[] }
type GoogleIdentityApi={initialize:(input:{client_id:string;callback:(response:{credential:string})=>void})=>void;renderButton:(element:HTMLElement,input:Record<string,unknown>)=>void}
declare global { interface Window { google?:{accounts:{id:GoogleIdentityApi}} } }
const money = new Intl.NumberFormat('es-MX', { style: 'currency', currency: 'MXN', minimumFractionDigits: 2 })
const totalPayments = (event: EventRecord) => event.payments.reduce((sum, item) => sum + (item.kind==='refund'?-item.amount:item.amount), 0)
const balanceDue = (event: EventRecord) => event.price===null?null:Math.max(Math.round(event.price*100)-Math.round(totalPayments(event)*100),0)/100
const paymentStatus = (event: EventRecord) => event.price!==null&&event.price>0&&balanceDue(event)===0?'Pagado':event.status
const todayLocal = () => {const now=new Date();return `${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`}
const totalExpenses = (event: EventRecord) => event.expenses.reduce((sum, item) => sum + item.amount, 0)
const visibleInScope = (unit:Unit,scope:Scope) => scope==='Todos'||unit===scope
const defaultUnit = (scope:Scope):Unit => scope==='5to Elemento'?'5to Elemento':'SPL'
const initialPeriod=():SavedPeriod=>({mode:'week',anchor:dashboardPeriod(todayLocal(),'week').start})
const periodKey=(user:SessionUser)=>`spl_dashboard_period_${user.userId}`
const scopeKey=(user:SessionUser)=>`spl_business_scope_${user.userId}`
const readPeriod=(user:SessionUser):SavedPeriod=>{try{const item=JSON.parse(localStorage.getItem(periodKey(user))??'null');return (item?.mode==='week'||item?.mode==='month')&&isCalendarDate(item?.anchor)?item:initialPeriod()}catch{return initialPeriod()}}
const readScope=(user:SessionUser):Scope=>{if(user.role==='coordinator')return '5to Elemento';const value=localStorage.getItem(scopeKey(user));return value==='SPL'||value==='5to Elemento'||value==='Todos'?value:'Todos'}
function fromApiEvent(event:ApiEvent):EventRecord { return {id:event.id,version:event.version,unit:event.businessUnit,name:`Evento · ${event.venue}`,client:event.clientName,venue:event.venue,date:event.eventDate,price:event.agreedPrice==null?null:Number(event.agreedPrice),payrollBudget:Number(event.payrollBudget??0),expenseBudget:Number(event.extraExpenseBudget??0),payrollActual:0,laborItems:[],status:event.operationalStatus==='Confirmado'||event.operationalStatus==='Completado'?'Confirmado':'Pendiente',payments:[],expenses:[]} }
function fromApiExpense(expense:ApiExpense):Expense { return {id:expense.id,name:expense.name,category:expense.category,date:expense.expenseDate,amount:Number(expense.amount),paid:Number(expense.paidAmount),source:expense.source,notes:expense.notes} }
function fromApiPayment(payment:ApiPayment):Payment{return{id:payment.id,date:payment.transactionDate,amount:Number(payment.amount),kind:payment.kind,version:payment.version}}
function FormModal({title,eyebrow,close,submit,children,submitLabel='Guardar'}:{title:string;eyebrow:string;close:()=>void;submit:(event:React.FormEvent)=>void;children:React.ReactNode;submitLabel?:string}){
  return <div className="modal-layer" role="dialog" aria-modal="true" aria-label={title}><button className="modal-backdrop" onClick={close}/><form className="event-modal compact-modal" onSubmit={submit}><div className="modal-head"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div><button type="button" aria-label="Cerrar" onClick={close}><X size={20}/></button></div><div className="form-grid">{children}</div><div className="modal-actions"><button type="button" onClick={close}>Cancelar</button><button className="primary" type="submit">{submitLabel}</button></div></form></div>
}
function ExpenseModal({close,save}:{close:()=>void;save:(value:{name:string;category:string;amount:string;expenseDate:string})=>Promise<void>}){
  const [form,setForm]=React.useState({name:'',category:DEFAULT_EXPENSE_CATEGORY,amount:'',expenseDate:new Date().toISOString().slice(0,10)}),[error,setError]=React.useState('')
  const submit=async(event:React.FormEvent)=>{event.preventDefault();setError('');try{await save(form);close()}catch{setError('No se pudo guardar el gasto. Revisa los datos y la conexión.')}}
  return <FormModal title="Agregar gasto extra" eyebrow="Detalle del evento" close={close} submit={event=>void submit(event)}><label className="full">Nombre del gasto<input autoFocus required maxLength={200} value={form.name} onChange={event=>setForm({...form,name:event.target.value})}/></label><label>Categoría<select value={form.category} onChange={event=>setForm({...form,category:event.target.value})}>{EXPENSE_CATEGORIES.map(category=><option key={category}>{category}</option>)}</select></label><label>Monto MXN<input type="number" min="0.01" step="0.01" required value={form.amount} onChange={event=>setForm({...form,amount:event.target.value})}/></label><label className="full">Fecha<input type="date" required value={form.expenseDate} onChange={event=>setForm({...form,expenseDate:event.target.value})}/></label>{error&&<div className="form-error full" role="alert">{error}</div>}</FormModal>
}
function MovementModal({kind,eventName,close,save}:{kind:'payment'|'refund';eventName:string;close:()=>void;save:(amount:string,date:string)=>Promise<void>}){
  const [amount,setAmount]=React.useState(''),[date,setDate]=React.useState(new Date().toISOString().slice(0,10)),[error,setError]=React.useState('')
  const submit=async(event:React.FormEvent)=>{event.preventDefault();setError('');try{await save(Number(amount).toFixed(2),date);close()}catch{setError('No se pudo guardar el movimiento.')}}
  return <FormModal title={kind==='payment'?'Registrar abono':'Registrar reembolso'} eyebrow={eventName} close={close} submit={event=>void submit(event)} submitLabel={kind==='payment'?'Guardar abono':'Guardar reembolso'}><label className="full">Monto MXN<input autoFocus type="number" min="0.01" step="0.01" required value={amount} onChange={event=>setAmount(event.target.value)}/></label><label className="full">Fecha del movimiento<input type="date" required value={date} onChange={event=>setDate(event.target.value)}/></label>{error&&<div className="form-error full" role="alert">{error}</div>}</FormModal>
}
function PayRemainingModal({eventName,amount,close,save}:{eventName:string;amount:number;close:()=>void;save:(date:string)=>Promise<void>}){
  const [date,setDate]=React.useState(new Date().toISOString().slice(0,10)),[error,setError]=React.useState(''),[busy,setBusy]=React.useState(false)
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{await save(date);close()}catch(e){setError(e instanceof Error?e.message:'No se pudo registrar el pago.')}finally{setBusy(false)}}
  return <FormModal title="Registrar pago del saldo" eyebrow={eventName} close={close} submit={e=>void submit(e)} submitLabel={busy?'Registrando...':'Confirmar pago completo'}><p className="full">Saldo a registrar: <strong>{money.format(amount)}</strong>. El servidor calculará el importe final.</p><label className="full">Fecha de pago<input autoFocus type="date" required value={date} onChange={e=>setDate(e.target.value)}/></label>{error&&<div className="form-error full" role="alert">{error}</div>}</FormModal>
}
function PriceModal({event,close,save}:{event:EventRecord;close:()=>void;save:(amount:string)=>Promise<void>}){
  const [amount,setAmount]=React.useState(event.price?.toFixed(2)??''),[error,setError]=React.useState('')
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setError('');try{await save(amount);close()}catch{setError('No se pudo actualizar el precio. Recarga el evento y vuelve a intentarlo.')}}
  return <FormModal title="Editar precio acordado" eyebrow={event.name} close={close} submit={event=>void submit(event)} submitLabel="Guardar precio"><label className="full">Precio MXN<input autoFocus type="number" min="0" step="0.01" value={amount} onChange={event=>setAmount(event.target.value)} placeholder="Puede quedar pendiente"/></label>{event.price!==null&&<button type="button" className="remove-price" onClick={()=>{setError('');void save('').then(close).catch(()=>setError('No se pudo quitar el precio.'))}}>Quitar precio acordado</button>}{error&&<div className="form-error full" role="alert">{error}</div>}</FormModal>
}
function MonthModal({close,save,defaultMonth}:{close:()=>void;save:(month:string)=>Promise<void>;defaultMonth:string}){
  const [month,setMonth]=React.useState(defaultMonth),[error,setError]=React.useState('')
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setError('');try{await save(month);close()}catch{setError('No pudimos generar el reporte.')}}
  return <FormModal title="Exportar reporte mensual" eyebrow="Finanzas" close={close} submit={event=>void submit(event)} submitLabel="Descargar Excel"><label className="full">Mes del reporte<input type="month" required value={month} onChange={event=>setMonth(event.target.value)}/></label>{error&&<div className="form-error full" role="alert">{error}</div>}</FormModal>
}
function Sidebar({ view, setView, mobileNav, close, user, logout, scope, setScope }: { view: View; setView: (view: View) => void; mobileNav: boolean; close: () => void; user:SessionUser; logout:()=>void;scope:Scope;setScope:(scope:Scope)=>void }) {
  const go = (next: View) => { setView(next); close() }
  return <><aside className={mobileNav?'sidebar open':'sidebar'}><div className="brand"><img className="brand-logo" src={scope==='5to Elemento'?'/quinto-elemento-logo.png':'/spl-logo.png'} alt={scope==='5to Elemento'?'Logotipo 5to Elemento':'Logotipo SPL'} /><div><strong>{scope==='5to Elemento'?'5to Elemento':'SPL'}</strong><span>{user.role==='coordinator'?'Coordinación de eventos':'Control financiero'}</span></div><button className="mobile-close" onClick={close} aria-label="Cerrar menú"><X size={20}/></button></div><div className="sidebar-scope"><ScopeControl value={scope} onChange={setScope} disabled={user.role==='coordinator'}/></div><nav>{user.role!=='coordinator'&&<button className={view==='dashboard'?'active':''} onClick={()=>go('dashboard')}><LayoutDashboard size={19}/>Panel general</button>}<button className={view==='events'?'active':''} onClick={()=>go('events')}><CalendarDays size={19}/>Eventos</button>{user.role!=='coordinator'&&<><button className={view==='finance'?'active':''} onClick={()=>go('finance')}><WalletCards size={19}/>Finanzas</button><button className={view==='payroll'?'active':''} onClick={()=>go('payroll')}><Users size={19}/>Nómina</button></>}<button className={view==='settings'?'active':''} onClick={()=>go('settings')}><Settings size={19}/>Configuración</button></nav><button className="user-card" onClick={logout}><div className="avatar">{user.displayName.split(' ').map(value=>value[0]).slice(0,2).join('')}</div><div><strong>{user.displayName}</strong><span>{user.role==='coordinator'?'Coordinación':'Administrador'} · Cerrar sesión</span></div><MoreHorizontal size={18}/></button></aside>{mobileNav&&<button className="backdrop" onClick={close} aria-label="Cerrar menú"/>}</>
}
function ScopeControl({ value, onChange, disabled=false }: { value: Scope; onChange: (scope: Scope) => void;disabled?:boolean }) { return <div className="scope-control"><label><span>Vista de negocio</span><div className="scope-select"><select aria-label="Vista de negocio" value={value} disabled={disabled} onChange={e => onChange(e.target.value as Scope)}><option>Todos</option><option>SPL</option><option>5to Elemento</option></select><ChevronDown size={16} aria-hidden="true"/></div></label></div> }
function Dashboard({ scope, events, warehouseCosts, quickExpenses, directIncomes, selectedPeriod, setSelectedPeriod }: { scope: Scope;events:EventRecord[];warehouseCosts:DashboardCost[];quickExpenses:ApiQuickExpense[];directIncomes:ApiDirectIncome[];selectedPeriod:SavedPeriod;setSelectedPeriod:(period:SavedPeriod)=>void }) {
  const {mode}=selectedPeriod
  const today=todayLocal(),period=dashboardPeriod(selectedPeriod.anchor,mode)
  const visible=events.filter(event=>visibleInScope(event.unit,scope))
  const visibleIncome=directIncomes.filter(income=>visibleInScope(income.businessUnit,scope))
  const costs:DashboardCost[]=[...visible.flatMap(event=>[
    ...event.expenses.map(expense=>({id:`expense:${expense.id}`,name:expense.name,category:expense.category,date:expense.date,amount:expense.amount,context:event.venue,kind:'expense' as const,payrollOrigin:expense.source==='payroll',cashDate:expense.cashDate,cashAmount:expense.paid,cashPayments:expense.cashPayments})),
    ...event.laborItems,
  ]),...warehouseCosts.filter(cost=>visibleInScope(cost.businessUnit??'SPL',scope)),...quickExpenses.filter(expense=>visibleInScope(expense.businessUnit,scope)).map(expense=>({id:`quick:${expense.id}`,name:expense.name,category:expense.category,date:expense.expenseDate,amount:Number(expense.amount),context:expense.businessUnit,kind:'expense' as const,cashDate:expense.expenseDate,cashAmount:Number(expense.amount)}))]
  const receipts=[...visible.flatMap(event=>event.payments.map(payment=>({date:payment.date,amount:payment.kind==='refund'?-payment.amount:payment.amount}))),...visibleIncome.filter(income=>income.receivedDate).map(income=>({date:income.receivedDate!,amount:Number(income.amount)}))]
  const paidCosts=paidAmounts(costs).filter(cost=>cost.amount>0)
  const periodCosts=paidCosts.filter(cost=>inPeriod(cost.date,period))
  const received=amountInPeriod(receipts,period),costTotal=amountInPeriod(paidCosts,period)
  const receivable=visible.filter(event=>event.date<=period.end).reduce((sum,event)=>sum+Math.max((event.price??0)-event.payments.filter(payment=>payment.date<=period.end).reduce((paid,payment)=>paid+(payment.kind==='refund'?-payment.amount:payment.amount),0),0),0)+visibleIncome.filter(income=>income.expectedDate<=period.end&&(!income.receivedDate||income.receivedDate>period.end)).reduce((sum,income)=>sum+Number(income.amount),0)
  const contribution=received-costTotal
  const metrics = [{label:'Cobros registrados',value:received,change:`${visible.length} eventos`,trend:'neutral',caption:'cobrados en el periodo'},{label:'Gastos pagados',value:costTotal,change:`${periodCosts.length} pagos`,trend:'neutral',caption:'salidas del periodo'},{label:'Saldo por cobrar',value:receivable,change:`al ${period.end}`,trend:'neutral',caption:'saldo a cierre del periodo'},{label:'Utilidad de caja',value:contribution,change:mode==='week'?'Semana':'Mes',trend:'neutral',caption:'cobros menos pagos'}]
  const upcoming=visible.filter(event=>event.date>=today).sort((a,b)=>a.date.localeCompare(b.date)||a.client.localeCompare(b.client)).slice(0,5)
  const unpaid=visible.filter(event=>(balanceDue(event)??0)>0).sort((a,b)=>{
    const aPast=a.date<today,bPast=b.date<today
    return aPast!==bPast?(aPast?-1:1):aPast?b.date.localeCompare(a.date):a.date.localeCompare(b.date)
  })
  return <div className="content"><section className="page-heading"><div><p className="eyebrow">Panel financiero</p><h1>Buen día, Oscar</h1><p>Consulta cobros y pagos según su fecha real.</p></div></section><PeriodSelector value={selectedPeriod} onChange={setSelectedPeriod} today={today}/><section className="metrics-grid">{metrics.map(metric=><article className="metric-card" key={metric.label}><div className="metric-title"><span>{metric.label}</span><CircleDollarSign size={19}/></div><strong>{money.format(metric.value)}</strong><div className={`metric-foot ${metric.trend}`}><b>{metric.change}</b><span>{metric.caption}</span></div></article>)}</section><CostBreakdown costs={periodCosts}/><section className="lower-grid"><article className="panel events-panel"><div className="panel-head"><div><h2>Próximos eventos</h2><p>Agenda de la vista seleccionada</p></div></div>{upcoming.length===0?<div className="empty-state">No hay próximos eventos</div>:<div className="event-list">{upcoming.map(event=><div className="event-row" key={event.id}><div className="date-box"><strong>{event.date.slice(8)}</strong><span>{new Date(`${event.date}T12:00:00`).toLocaleDateString('es-MX',{month:'short'}).toUpperCase()}</span></div><i className={`event-line ${event.unit==='5to Elemento'?'blue':''}`}/><div className="event-info"><strong>{event.name}</strong><span>{event.unit}</span></div><span className={`status ${paymentStatus(event)==='Pagado'||event.status==='Confirmado'?'confirmed':''}`}>{paymentStatus(event)}</span></div>)}</div>}</article><article className="panel budget-panel"><div className="panel-head"><div><h2>Saldos pendientes de eventos</h2><p>Eventos pasados y próximos sin pago completo</p></div><span className="count">{unpaid.length}</span></div>{unpaid.length===0?<div className="empty-state">No hay saldos pendientes</div>:unpaid.map(event=><div className="alert-item" key={event.id}><div><strong>{event.client} · {event.venue}</strong><b>{money.format(balanceDue(event)??0)}</b></div><span>{event.date<today?'Evento pasado':'Próximo evento'} · {new Date(`${event.date}T12:00:00`).toLocaleDateString('es-MX',{day:'numeric',month:'short',year:'numeric'})}</span></div>)}</article></section><WeeklyComparison receipts={receipts} costs={costs} today={period.end}/></div>
}
function EventsPage({ events, setEvents, selectedId, setSelectedId, openCreate, loadState, retry, role, scope }: { events: EventRecord[]; setEvents: React.Dispatch<React.SetStateAction<EventRecord[]>>; selectedId: string; setSelectedId: (id:string)=>void; openCreate:()=>void; loadState:'loading'|'ready'|'error'; retry:()=>void; role:SessionUser['role'];scope:Scope }) {
  const [expenseOpen,setExpenseOpen]=React.useState(false); const filtered=events.filter(event=>visibleInScope(event.unit,scope)); const selected=filtered.find(event=>event.id===selectedId) ?? filtered[0]
  React.useEffect(()=>{const update=()=>setEvents(current=>[...current]);window.addEventListener('spl-financial-change',update);return()=>window.removeEventListener('spl-financial-change',update)},[setEvents])
  React.useEffect(()=>{if(!selectedId||role==='coordinator')return;let active=true;Promise.all([eventApi.listExpenses(selectedId),eventApi.listPayments(selectedId)]).then(([expenses,payments])=>{if(active)setEvents(current=>current.map(event=>event.id===selectedId?{...event,expenses:expenses.map(item=>({...fromApiExpense(item),cashDate:event.expenses.find(old=>old.id===item.id)?.cashDate,cashPayments:event.expenses.find(old=>old.id===item.id)?.cashPayments})),payments:payments.map(fromApiPayment)}:event))}).catch(()=>{});return()=>{active=false}},[selectedId,setEvents,role])
  const addExpense=async(value:{name:string;category:string;amount:string;expenseDate:string})=>{if(!selected)return;const item=await eventApi.addExpense(selected.id,{...value,amount:Number(value.amount).toFixed(2)});setEvents(current=>current.map(event=>event.id===selected.id?{...event,expenses:[...event.expenses,fromApiExpense(item)]}:event))}
  const deleteEvent=async(event:EventRecord)=>{await eventApi.deleteEvent(event.id,event.version);setEvents(current=>current.filter(item=>item.id!==event.id));setSelectedId(events.find(item=>item.id!==event.id)?.id??'');window.dispatchEvent(new Event('spl-financial-change'))}
  return <div className="content events-workspace"><section className="page-heading"><div><p className="eyebrow">{role==='owner'?'Operación y finanzas':'Agenda operativa'}</p><h1>Eventos</h1><p>{role==='owner'?'Consulta cada evento y abre los registros que explican sus totales.':'Administra únicamente la información operativa de 5to Elemento.'}</p></div><button className="primary page-action" onClick={openCreate}><Plus size={18}/>Nuevo evento</button></section>{loadState==='error'&&<div className="connection-banner" role="alert"><div><strong>No pudimos cargar los eventos</strong><span>Revisa tu conexión. Tus datos no fueron modificados.</span></div><button onClick={retry}>Reintentar</button></div>}{loadState==='loading'&&<div className="loading-state" aria-live="polite">Cargando eventos...</div>}{loadState==='ready'&&<><div className="event-toolbar"><span>{scope==='Todos'?'Todos los negocios':scope}</span><span>{filtered.length} eventos</span></div>{filtered.length===0?<div className="panel no-events"><CalendarDays size={24}/><strong>No hay eventos en esta vista</strong><span>Crea la primera reservación para comenzar.</span><button className="primary" onClick={openCreate}>Nuevo evento</button></div>:<section className="event-workspace-grid"><article className={`panel event-table-panel ${role==='coordinator'?'operational':''}`}><div className="event-table-head"><span>Evento</span><span>Fecha</span><span>Estado</span>{role==='owner'&&<span>Saldo</span>}</div>{filtered.map(event=>{const balance=Math.max((event.price??0)-totalPayments(event),0);return <button className={`event-table-row ${selected?.id===event.id?'selected':''}`} onClick={()=>setSelectedId(event.id)} key={event.id}><div><i className={event.unit==='SPL'?'unit-spl':'unit-5to'}/><span><strong>{event.name}</strong><small>{event.client} · {event.id}</small></span></div><span>{new Date(`${event.date}T12:00:00`).toLocaleDateString('es-MX',{day:'2-digit',month:'short'})}</span><span className={`status ${paymentStatus(event)==='Pagado'||event.status==='Confirmado'?'confirmed':''}`}>{paymentStatus(event)}</span>{role==='owner'&&<b>{event.price===null?'Precio pendiente':money.format(balance)}</b>}</button>})}</article>{selected&&<EventDetail event={selected} addExpense={()=>setExpenseOpen(true)} deleteEvent={()=>deleteEvent(selected)} role={role}/>}</section>}</>}{expenseOpen&&selected&&<ExpenseModal close={()=>setExpenseOpen(false)} save={addExpense}/>}</div>
}
function EventDetail({event,addExpense,deleteEvent,role}:{event:EventRecord;addExpense:()=>void;deleteEvent:()=>Promise<void>;role:SessionUser['role']}) {
  const [,refresh]=React.useState(0),[movement,setMovement]=React.useState<'payment'|'refund'|null>(null),[priceOpen,setPriceOpen]=React.useState(false),[payOpen,setPayOpen]=React.useState(false),[confirmDelete,setConfirmDelete]=React.useState(false),[removingPayment,setRemovingPayment]=React.useState<string|null>(null),[error,setError]=React.useState('')
  const received=totalPayments(event), extras=totalExpenses(event), totalCost=event.payrollActual+extras, balance=event.price===null?null:Math.max(event.price-received,0)
  const recordPayment=async(kind:'payment'|'refund',amount:string,date:string)=>{const item=await eventApi.addPayment(event.id,{transactionDate:date,amount,kind,idempotencyKey:crypto.randomUUID()});event.payments.push(fromApiPayment(item));refresh(value=>value+1);window.dispatchEvent(new Event('spl-financial-change'))}
  const payRemaining=async(date:string)=>{const item=await eventApi.payRemaining(event.id,{transactionDate:date,idempotencyKey:crypto.randomUUID()});event.payments.push(fromApiPayment(item));refresh(value=>value+1);window.dispatchEvent(new Event('spl-financial-change'))}
  const deletePayment=async(payment:Payment)=>{setError('');try{await eventApi.deletePayment(payment.id,payment.version??1);event.payments=event.payments.filter(item=>item.id!==payment.id);setRemovingPayment(null);refresh(value=>value+1);window.dispatchEvent(new Event('spl-financial-change'))}catch(e){setError(e instanceof Error?e.message:'No se pudo quitar el movimiento.')}}
  const removeEvent=async()=>{setError('');try{await deleteEvent()}catch(e){setError(e instanceof Error?e.message:'No se pudo eliminar el evento.')}}
  const settle=async(expense:Expense)=>{const pending=expense.amount-expense.paid;if(pending<=0)return;setError('');try{const result=await eventApi.settleExpense(expense.id,{paymentDate:new Date().toISOString().slice(0,10),amount:pending.toFixed(2),idempotencyKey:crypto.randomUUID()});expense.paid=Number(result.paidAmount);expense.cashDate=result.paymentDate;expense.cashPayments=[...(expense.cashPayments??[]),{date:result.paymentDate,amount:pending}];refresh(value=>value+1);window.dispatchEvent(new Event('spl-financial-change'))}catch{setError('No se pudo marcar el gasto como pagado.')}}
  const updatePrice=async(amount:string)=>{const updated=await eventApi.updateAgreedPrice(event.id,{agreedPrice:amount.trim()?Number(amount).toFixed(2):null,version:event.version});event.price=updated.agreedPrice===null?null:Number(updated.agreedPrice);event.version=updated.version;refresh(value=>value+1);window.dispatchEvent(new Event('spl-financial-change'))}
  return <article className="panel event-detail">
    <div className="detail-head"><div><span className={`unit-pill ${event.unit==='SPL'?'spl':''}`}>{event.unit}</span><span className={`status ${paymentStatus(event)==='Pagado'||event.status==='Confirmado'?'confirmed':''}`}>{paymentStatus(event)}</span><h2>{event.name}</h2><p>{event.client} · {event.venue}</p></div>{role!=='coordinator'&&<button className="icon-button" aria-label="Eliminar evento" title="Eliminar evento" onClick={()=>setConfirmDelete(true)}><Trash2 size={20}/></button>}</div>
    {confirmDelete&&<div className="delete-confirm" role="group" aria-label="Confirmar eliminación del evento"><p>¿Eliminar este evento? Dejará de aparecer en la agenda y los reportes, incluso si ya está pagado. Sus movimientos quedarán conservados en la auditoría.</p><button onClick={()=>setConfirmDelete(false)}>Cancelar</button><button className="danger-button" onClick={()=>void removeEvent()}>Sí, eliminar evento</button></div>}
    <div className="detail-date"><CalendarDays size={17}/><span><small>Fecha del evento</small><strong>{new Date(`${event.date}T12:00:00`).toLocaleDateString('es-MX',{weekday:'long',day:'numeric',month:'long',year:'numeric'})}</strong></span></div>
    {role!=='coordinator'?<>
      <div className="detail-money"><div><span>Precio acordado</span><strong>{event.price===null?'Precio pendiente':money.format(event.price)}</strong><button className="inline-edit" onClick={()=>setPriceOpen(true)}>Editar precio acordado</button></div><div><span>Cobros netos</span><strong className="green">{money.format(received)}</strong></div><div><span>Saldo por cobrar</span><strong>{balance===null?'Sin calcular':money.format(balance)}</strong></div></div>
      <div className="movement-actions"><button onClick={()=>setMovement('payment')}><Plus size={14}/>Registrar abono</button><button onClick={()=>setMovement('refund')}>Registrar reembolso</button>{balance!==null&&balance>0&&<button className="pay-remaining-button" onClick={()=>setPayOpen(true)}><Check size={14}/>Pago completo</button>}</div>
      <div className="payment-list">{event.payments.length===0?<span>Sin movimientos de cliente</span>:event.payments.map(payment=><div key={payment.id}><span>{payment.kind==='refund'?'Reembolso':'Abono'} · {payment.date}</span><strong className={payment.kind==='refund'?'refund':''}>{payment.kind==='refund'?'-':'+'}{money.format(payment.amount)}</strong>{removingPayment===payment.id?<span className="payment-remove-confirm"><button onClick={()=>setRemovingPayment(null)}>Cancelar</button><button className="danger-button" onClick={()=>void deletePayment(payment)}>Confirmar</button></span>:<button className="icon-button remove-payment" aria-label={`Quitar ${payment.kind==='refund'?'reembolso':'abono'} del ${payment.date}`} title="Quitar movimiento" onClick={()=>setRemovingPayment(payment.id)}><Trash2 size={15}/></button>}</div>)}</div>
      <div className="cost-summary"><div><span>Nómina</span><strong>{money.format(event.payrollActual)}</strong></div><div><span>Gastos extra</span><strong>{money.format(extras)}</strong></div><div className="total"><span>Gasto total del evento</span><strong>{money.format(totalCost)}</strong><small>Nómina + gastos extra</small></div></div>
      <div className="detail-section-head"><div><h3>Detalle de gastos extra</h3><span>{event.expenses.length} registros</span></div><button onClick={addExpense}><Plus size={15}/>Agregar</button></div>
      {error&&<div className="form-error" role="alert">{error}</div>}<div className="expense-detail-list">{event.expenses.length===0?<div className="empty-state"><Check size={20}/><strong>Sin gastos registrados</strong><span>Agrega cada gasto por separado para explicar el total.</span></div>:event.expenses.map(expense=><div key={expense.id}><span><strong>{expense.name}</strong><small>{expense.source==='payroll'?'Gasto originado en nómina':expense.category}</small></span><span><strong>{money.format(expense.amount)}</strong><small>{expense.paid>=expense.amount?'Pagado':'Pendiente'}</small>{expense.paid<expense.amount&&expense.source!=='payroll'&&<button className="settle-button" onClick={()=>void settle(expense)}>Marcar como pagado</button>}</span></div>)}</div>
    </>:<div className="operational-note"><strong>Información operativa</strong><span>La información financiera está protegida para este perfil.</span></div>}
    {movement&&<MovementModal kind={movement} eventName={event.name} close={()=>setMovement(null)} save={(amount,date)=>recordPayment(movement,amount,date)}/>} {priceOpen&&<PriceModal event={event} close={()=>setPriceOpen(false)} save={updatePrice}/>} {payOpen&&balance!==null&&<PayRemainingModal eventName={event.name} amount={balance} close={()=>setPayOpen(false)} save={payRemaining}/>}
  </article>
}
function CreateEventModal({close,save,count,role,defaultUnit:initialUnit}:{close:()=>void;save:(event:EventRecord)=>Promise<void>;count:number;role:SessionUser['role'];defaultUnit:Unit}) {
  const [form,setForm]=React.useState({unit:(role==='coordinator'?'5to Elemento':initialUnit) as Unit,client:'',venue:'',date:'',price:''}); const set=(key:keyof typeof form,value:string)=>setForm(current=>({...current,[key]:value}))
  const [saving,setSaving]=React.useState(false),[error,setError]=React.useState(''); const submit=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);setError('');try{await save({id:`draft-${count+1}`,version:1,unit:form.unit,name:`Evento · ${form.venue}`,client:form.client,venue:form.venue,date:form.date,price:form.price?Number(form.price):null,payrollBudget:0,expenseBudget:0,payrollActual:0,laborItems:[],status:'Pendiente',payments:[],expenses:[]})}catch{setError('No se pudo crear el evento. Revisa la conexión antes de volver a intentarlo.')}finally{setSaving(false)}}
  return <div className="modal-layer" role="dialog"><button className="modal-backdrop" onClick={close}/><form className="event-modal" onSubmit={submit}><div className="modal-head"><div><p className="eyebrow">Nuevo registro</p><h2>Crear evento</h2></div><button type="button" onClick={close}><X size={20}/></button></div><p>Captura primero la información esencial. Los cobros y gastos se agregan desde el detalle del evento.</p>{error&&<div className="form-error" role="alert">{error}</div>}<div className="form-grid"><label className="full">Unidad<select value={form.unit} disabled={role==='coordinator'} onChange={e=>set('unit',e.target.value)}><option>SPL</option><option>5to Elemento</option></select></label><label>Cliente<input value={form.client} onChange={e=>set('client',e.target.value)} placeholder="Nombre del cliente" required/></label><label>Lugar<input value={form.venue} onChange={e=>set('venue',e.target.value)} placeholder="Lugar del evento" required/></label><label>Fecha<input type="date" value={form.date} onChange={e=>set('date',e.target.value)} required/></label>{role==='owner'&&<label>Precio acordado<input type="number" min="0" step="0.01" value={form.price} onChange={e=>set('price',e.target.value)} placeholder="Puede quedar pendiente"/></label>}</div><div className="modal-actions"><button type="button" onClick={close}>Cancelar</button><button className="primary" type="submit" disabled={saving}>{saving?'Guardando...':'Crear evento'}</button></div></form></div>
}
function FinancePage({events,scope,quickExpenses,directIncomes,warehouseCosts,selectedPeriod,setSelectedPeriod,onIncomeChanged}:{events:EventRecord[];scope:Scope;quickExpenses:ApiQuickExpense[];directIncomes:ApiDirectIncome[];warehouseCosts:DashboardCost[];selectedPeriod:SavedPeriod;setSelectedPeriod:(period:SavedPeriod)=>void;onIncomeChanged:(income:ApiDirectIncome|null,id:string)=>void}){
  const [records,setRecords]=React.useState(events),[payroll,setPayroll]=React.useState<ApiPayroll[]>([]),[weekly,setWeekly]=React.useState<ApiWeeklyPayroll[]>([]),[state,setState]=React.useState<'loading'|'ready'|'error'>('loading'),[incomeAction,setIncomeAction]=React.useState<ApiDirectIncome|null>(null),[actionType,setActionType]=React.useState<'receive'|'delete'|null>(null),[receivedDate,setReceivedDate]=React.useState(todayLocal()),[incomeError,setIncomeError]=React.useState(''),[actionBusy,setActionBusy]=React.useState(false),[ledgerOpen,setLedgerOpen]=React.useState(false)
  const ledgerId=React.useId()
  React.useEffect(()=>{let active=true;setState('loading');Promise.all([Promise.all(events.map(async event=>{const [expenses,payments]=await Promise.all([eventApi.listExpenses(event.id),eventApi.listPayments(event.id)]);return{...event,expenses:expenses.map(item=>({...fromApiExpense(item),cashDate:event.expenses.find(old=>old.id===item.id)?.cashDate,cashPayments:event.expenses.find(old=>old.id===item.id)?.cashPayments})),payments:payments.map(fromApiPayment)}})),payrollApi.list(),weeklyPayrollApi.list()]).then(([loaded,workers,batches])=>{if(active){setRecords(loaded);setPayroll(workers);setWeekly(batches);setState('ready')}}).catch(()=>{if(active)setState('error')});return()=>{active=false}},[events])
  const period=dashboardPeriod(selectedPeriod.anchor,selectedPeriod.mode)
  const data=financePeriodData({events:records,incomes:directIncomes,quickExpenses,warehouseCosts,scope,period})
  const payrollUnits=new Map(weekly.flatMap(batch=>batch.lines.map(line=>[line.id,batch.businessUnit] as const)))
  const eventUnits=new Map(records.map(event=>[event.id,event.unit] as const))
  const scopedPayroll=payroll.filter(entry=>entry.allocations.some(allocation=>visibleInScope(payrollAllocationUnit(allocation,eventUnits,payrollUnits.get(entry.id)),scope)))
  const visiblePayroll=scopedPayroll.filter(entry=>inPeriod(entry.periodEnd,period))
  const laborCosts=[...records.flatMap(event=>event.laborItems),...warehouseCosts.filter(cost=>cost.kind==='labor')]
  const pendingLabor=payroll.filter(entry=>entry.periodEnd<=period.end).reduce((sum,entry)=>{
    const cashPaid=paidAmounts(laborCosts.filter(cost=>cost.id.startsWith(`labor:${entry.id}:`))).filter(cost=>cost.date<=period.end).reduce((total,cost)=>total+Math.round(cost.amount*100),0)
    const outstanding=Math.max(Math.round(Number(entry.netPay)*100)-cashPaid,0)/100
    const shares=allocatePayrollCents(outstanding,entry.allocations.map(allocation=>allocation.amount))
    return sum+entry.allocations.reduce((subtotal,allocation,index)=>subtotal+(visibleInScope(payrollAllocationUnit(allocation,eventUnits,payrollUnits.get(entry.id)),scope)?Math.round(shares[index]*100):0),0)
  },0)/100
  const payable=data.expenses.reduce((sum,expense)=>sum+Math.round(expense.pending*100),0)/100+pendingLabor
  const pendingIncome=data.periodIncomes.filter(income=>!income.receivedDate||income.receivedDate>period.end)
  const doIncomeAction=async()=>{if(!incomeAction||!actionType)return;setActionBusy(true);setIncomeError('');try{if(actionType==='receive'){const updated=await directIncomeApi.receive(incomeAction.id,receivedDate,incomeAction.version);onIncomeChanged(updated,incomeAction.id)}else{await directIncomeApi.delete(incomeAction.id,incomeAction.version);onIncomeChanged(null,incomeAction.id)}setIncomeAction(null);setActionType(null)}catch(reason){setIncomeError(reason instanceof Error?reason.message:'No se pudo completar la operación.')}finally{setActionBusy(false)}}
  const beginIncomeAction=(income:ApiDirectIncome,type:'receive'|'delete')=>{setIncomeAction(income);setActionType(type);setReceivedDate(todayLocal());setIncomeError('')}
  return <div className="content finance-page">
    <section className="page-heading"><div><p className="eyebrow">Control financiero</p><h1>Finanzas</h1><p>Consulta ingresos, costos y pagos del periodo seleccionado.</p></div></section>
    <PeriodSelector value={selectedPeriod} onChange={setSelectedPeriod} today={todayLocal()}/>
    {state==='error'&&<div className="connection-banner" role="alert"><div><strong>No pudimos cargar las finanzas</strong><span>Revisa la conexión e intenta entrar de nuevo.</span></div></div>}
    {state==='loading'&&<div className="loading-state" role="status">Cargando finanzas...</div>}
    <section className="finance-metrics">
      <article><span>Ingresos acordados y utilidades</span><strong>{money.format(data.agreed)}</strong><small>{data.periodEvents.length} eventos · {data.periodIncomes.length} utilidades del periodo</small></article>
      <article><span>Por cobrar</span><strong>{money.format(data.receivable)}</strong><small>Saldo al cierre del periodo</small></article>
      <article><span>Por pagar</span><strong className="orange">{money.format(payable)}</strong><small>Gastos y sueldos pendientes al cierre</small></article>
    </section>
    <section className="finance-layout">
      <article className="panel finance-summary">
        <h2>Resultado completo</h2>
        <div><span>Ingresos acordados y utilidades</span><strong>{money.format(data.agreed)}</strong></div>
        <div><span>Sueldos y costos laborales</span><strong>{money.format(data.expectedLabor===0?0:-data.expectedLabor)}</strong></div>
        <div><span>Gastos registrados</span><strong>{money.format(data.expectedExpenses===0?0:-data.expectedExpenses)}</strong></div>
        <div className={data.expectedResult<0?'finance-total negative-result':'finance-total'}><span>Resultado previsto</span><strong>{money.format(data.expectedResult)}</strong></div>
        <p className="finance-summary-explanation">Ingresos previstos menos costos registrados según su fecha. Incluye los saldos pendientes.</p>
        <div className="finance-cash-result"><span>Resultado de caja del periodo<small>Cobros netos {money.format(data.received)} menos pagos {money.format(data.cashExpenses+data.cashLabor)}</small></span><strong className={data.cashResult<0?'orange':''}>{money.format(data.cashResult)}</strong></div>
        <button type="button" className="finance-summary-toggle" aria-label={ledgerOpen?'Ocultar entradas del periodo':'Ver entradas del periodo'} aria-expanded={ledgerOpen} aria-controls={ledgerId} onClick={()=>setLedgerOpen(value=>!value)}><span>{ledgerOpen?'Ocultar entradas':'Ver entradas del periodo'}</span><ChevronDown size={20} aria-hidden="true"/></button>
        {ledgerOpen&&<FinanceIncomeLedger movements={data.movements} id={ledgerId}/>}
      </article>
      <article className="panel finance-table"><div className="finance-table-head"><h2>Detalle por evento</h2><span>{state==='loading'?'Actualizando...':'Eventos del periodo'}</span></div>{data.periodEvents.length===0?<div className="empty-state">No hay eventos en este periodo.</div>:<div className="finance-scroll"><table><thead><tr><th>Evento</th><th>Unidad</th><th>Precio</th><th>Cobrado al cierre</th><th>Costos previstos</th><th>Contribución prevista</th></tr></thead><tbody>{data.periodEvents.map(event=>{const received=event.payments.filter(payment=>payment.date<=period.end).reduce((sum,payment)=>sum+(payment.kind==='refund'?-payment.amount:payment.amount),0),cost=event.expenses.filter(expense=>inPeriod(expense.date,period)).reduce((sum,expense)=>sum+expense.amount,0)+event.laborItems.filter(labor=>inPeriod(labor.date,period)).reduce((sum,labor)=>sum+labor.amount,0),result=(event.price??0)-cost;return <tr key={event.id}><td><strong>{event.client}</strong><small>{event.venue}</small></td><td>{event.unit}</td><td>{event.price===null?'Pendiente':money.format(event.price)}</td><td>{money.format(received)}</td><td>{money.format(cost)}</td><td className={result<0?'negative':'positive'}>{event.price===null?'Sin calcular':money.format(result)}</td></tr>})}</tbody></table></div>}</article>
      <article className="panel finance-incomes"><div className="finance-table-head"><h2>Utilidades sin evento</h2><span>{pendingIncome.length} pendientes al cierre</span></div>{data.periodIncomes.length===0?<div className="empty-state">No hay utilidades registradas en este periodo.</div>:<div className="finance-income-list">{[...data.periodIncomes].sort((a,b)=>(b.receivedDate&&b.receivedDate<=period.end?b.receivedDate:b.expectedDate).localeCompare(a.receivedDate&&a.receivedDate<=period.end?a.receivedDate:a.expectedDate)).map(income=>{const receivedAtCutoff=!!income.receivedDate&&income.receivedDate<=period.end;return <div key={income.id}><div><strong>{income.name}</strong><span>{income.businessUnit} · {receivedAtCutoff?`Cobrado ${income.receivedDate}`:`Previsto ${income.expectedDate}`}</span>{income.notes&&<p>{income.notes}</p>}</div><b>{money.format(Number(income.amount))}</b><span className={receivedAtCutoff?'expense-paid':'expense-pending'}>{receivedAtCutoff?'Cobrada':'Pendiente al cierre'}</span><div className="finance-income-actions">{!income.receivedDate&&<button onClick={()=>beginIncomeAction(income,'receive')}>Marcar cobrada</button>}<button className="finance-delete" aria-label={`Eliminar utilidad ${income.name}`} onClick={()=>beginIncomeAction(income,'delete')}><Trash2 size={16}/></button></div></div>})}</div>}</article>
      <FinanceExpenses expenses={data.expenses} periodEnd={period.end}/>
    </section>
    <PayrollMonitoring payroll={visiblePayroll} batches={weekly.filter(batch=>visibleInScope(batch.businessUnit,scope)&&inPeriod(batch.periodEnd,period))} events={records.filter(event=>visibleInScope(event.unit,scope))}/>
    {incomeAction&&actionType&&<FormModal title={actionType==='receive'?'Registrar cobro de utilidad':'Eliminar utilidad'} eyebrow={incomeAction.name} close={()=>setIncomeAction(null)} submit={event=>{event.preventDefault();void doIncomeAction()}} submitLabel={actionBusy?'Procesando...':actionType==='receive'?'Registrar cobro':'Sí, eliminar utilidad'}>{actionType==='receive'?<label className="full">Fecha real de cobro<input autoFocus type="date" required value={receivedDate} onChange={event=>setReceivedDate(event.target.value)}/></label>:<p className="full">¿Eliminar esta utilidad? Dejará de aparecer en finanzas y reportes. La auditoría conservará el registro.</p>}{incomeError&&<div className="form-error full" role="alert">{incomeError}</div>}</FormModal>}
  </div>
}
function SettingsPage({user}:{user:SessionUser}){
  const [preferences,setPreferences]=React.useState<Preferences>(()=>parsePreferences(localStorage.getItem('spl_preferences'))),[saved,setSaved]=React.useState(false),[connection,setConnection]=React.useState<'checking'|'online'|'offline'>('checking')
  React.useEffect(()=>{healthApi.status().then(()=>setConnection('online')).catch(()=>setConnection('offline'))},[])
  const save=()=>{localStorage.setItem('spl_preferences',JSON.stringify(preferences));document.documentElement.dataset.compact=preferences.compactMode?'true':'false';setSaved(true);setTimeout(()=>setSaved(false),1800)}
  const reset=()=>{setPreferences(defaultPreferences);localStorage.removeItem('spl_preferences');document.documentElement.dataset.compact='false'}
  return <div className="content settings-page"><section className="page-heading"><div><p className="eyebrow">Preferencias y acceso</p><h1>Configuración</h1><p>Administra tu experiencia, conexión y datos de la cuenta.</p></div></section><section className="settings-grid"><article className="panel settings-card"><div className="settings-title"><ShieldCheck size={20}/><div><h2>Cuenta y seguridad</h2><p>Sesión individual autorizada</p></div></div><dl><div><dt>Nombre</dt><dd>{user.displayName}</dd></div><div><dt>Correo</dt><dd>{user.email}</dd></div><div><dt>Perfil</dt><dd>{user.role==='coordinator'?'Coordinación':'Administrador'}</dd></div><div><dt>Duración de sesión</dt><dd>180 días en este equipo</dd></div></dl></article><article className="panel settings-card"><div className="settings-title"><Wifi size={20}/><div><h2>Conexión</h2><p>Estado de servicios locales</p></div></div><div className={`connection-status ${connection}`}><i/><span>{connection==='checking'?'Comprobando conexión':connection==='online'?'Backend conectado':'Backend sin conexión'}</span></div><div className="settings-fact"><Database size={17}/><span><strong>Datos centralizados</strong><small>La interfaz no almacena contraseñas ni secretos de Google.</small></span></div></article><form className="panel preferences-card" onSubmit={event=>{event.preventDefault();save()}}><h2>Preferencias</h2><div className="preferences-fields"><label>Unidad predeterminada<select value={preferences.defaultUnit} onChange={event=>setPreferences({...preferences,defaultUnit:event.target.value as Preferences['defaultUnit']})}><option>SPL</option><option>5to Elemento</option></select></label><label>Mes sugerido para reportes<select value={preferences.reportMonth} onChange={event=>setPreferences({...preferences,reportMonth:event.target.value as Preferences['reportMonth']})}><option value="current">Mes actual</option><option value="previous">Mes anterior</option></select></label><label className="toggle-row"><span><strong>Vista compacta</strong><small>Reduce espacios en tablas extensas.</small></span><input type="checkbox" checked={preferences.compactMode} onChange={event=>setPreferences({...preferences,compactMode:event.target.checked})}/></label></div><div className="settings-actions"><button type="button" onClick={reset}>Restablecer</button><button className="primary">{saved?'Guardado':'Guardar cambios'}</button></div></form></section></div>
}
function LoginScreen({onLogin}:{onLogin:(user:SessionUser)=>void}){
  const [email,setEmail]=React.useState(''),[password,setPassword]=React.useState(''),[error,setError]=React.useState(''),[busy,setBusy]=React.useState(false),[testBusy,setTestBusy]=React.useState(false),[desktopGoogle,setDesktopGoogle]=React.useState<boolean|null|undefined>(undefined),[testLogin,setTestLogin]=React.useState(false)
  const loginAttempt=React.useRef(0)
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{onLogin(await authApi.login(email,password))}catch{setError('Correo o contraseña incorrectos.')}finally{setBusy(false)}}
  const loginWithDesktopGoogle=async()=>{const attempt=++loginAttempt.current;setBusy(true);setError('');try{const {flowId,authorizationUrl}=await desktopGoogleApi.start();await openDesktopAuthorization(authorizationUrl);const user=await waitForDesktopGoogle(flowId,desktopGoogleApi.status);if(loginAttempt.current===attempt)onLogin(user)}catch(error){if(loginAttempt.current===attempt)setError(error instanceof Error?error.message:'No pudimos completar el acceso con Google. Inténtalo nuevamente.')}finally{if(loginAttempt.current===attempt)setBusy(false)}}
  const enterTestMode=async()=>{loginAttempt.current++;setTestBusy(true);setError('');try{onLogin(await testLoginApi.login())}catch{setError('No pudimos iniciar el modo de pruebas.')}finally{setTestBusy(false)}}
  const googleButton=React.useRef<HTMLDivElement>(null)
  React.useEffect(()=>{
    let active=true
    desktopGoogleApi.config().then(result=>{if(active)setDesktopGoogle(result.enabled)}).catch(()=>{if(active)setDesktopGoogle(false)})
    testLoginApi.config().then(result=>{if(active)setTestLogin(result.enabled)}).catch(()=>{})
    return()=>{active=false}
  },[])
  React.useEffect(()=>{
    if(desktopGoogle!==null)return
    const clientId=import.meta.env.VITE_GOOGLE_CLIENT_ID
    if(!clientId)return
    const render=()=>{
      if(!window.google||!googleButton.current)return
      window.google.accounts.id.initialize({client_id:clientId,callback:async({credential})=>{
        setBusy(true)
        setError('')
        try{onLogin(await authApi.google(credential))}catch{setError('No pudimos autorizar esta cuenta de Google.')}finally{setBusy(false)}
      }})
      window.google.accounts.id.renderButton(googleButton.current,{theme:'filled_black',size:'large',text:'continue_with',shape:'rectangular',width:342,locale:'es'})
    }
    const script=document.createElement('script')
    script.src='https://accounts.google.com/gsi/client'
    script.async=true
    script.onload=render
    document.head.appendChild(script)
    return()=>script.remove()
  },[desktopGoogle,onLogin])
  return <main className="login-page"><section className="login-panel"><div className="login-brand"><img className="brand-logo" src="/spl-logo.png" alt="Logotipo SPL" /><div><strong>SPL</strong><span>Control de eventos y finanzas</span></div></div><div className="login-copy"><p className="eyebrow">Acceso seguro</p><h1>Bienvenido</h1><p>Ingresa con una cuenta autorizada para continuar.</p></div>{desktopGoogle===true?<button className="desktop-google-button" type="button" disabled={busy} onClick={()=>void loginWithDesktopGoogle()}>{busy?'Esperando autorización...':'Continuar con Google nuevamente'}</button>:desktopGoogle===false?<div className="login-error" role="alert">No se pudo verificar Google para Windows. Revisa la configuración o vuelve a abrir la aplicación.</div>:<div className="google-button" ref={googleButton}/>} {testLogin&&<button className="test-login-button" type="button" disabled={testBusy} onClick={()=>void enterTestMode()}>{testBusy?'Abriendo modo de pruebas...':'Entrar en modo de pruebas'}</button>}<div className="login-divider"><span>o usa tu cuenta existente</span></div><form onSubmit={submit}><label>Correo electrónico<input type="email" autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Contraseña<input type="password" autoComplete="current-password" minLength={8} maxLength={128} value={password} onChange={e=>setPassword(e.target.value)} required/></label>{error&&<div className="login-error" role="alert">{error}</div>}<button className="primary" disabled={busy}>{busy?'Verificando...':'Iniciar sesión'}</button></form><small>La sesión permanece activa en este equipo de confianza.</small></section></main>
}
function App() {
  const [session,setSession]=React.useState<SessionUser|null|undefined>(undefined), [view,setView]=React.useState<View>('dashboard'), [scope,setScope]=React.useState<Scope>('Todos'),[selectedPeriod,setSelectedPeriod]=React.useState<SavedPeriod>(initialPeriod), [mobileNav,setMobileNav]=React.useState(false), [creating,setCreating]=React.useState(false),[creatingExpense,setCreatingExpense]=React.useState(false),[creatingIncome,setCreatingIncome]=React.useState(false),[exporting,setExporting]=React.useState(false), [events,setEvents]=React.useState<EventRecord[]>([]), [warehouseCosts,setWarehouseCosts]=React.useState<DashboardCost[]>([]), [quickExpenses,setQuickExpenses]=React.useState<ApiQuickExpense[]>([]),[directIncomes,setDirectIncomes]=React.useState<ApiDirectIncome[]>([]), [selectedId,setSelectedId]=React.useState(''), [loadState,setLoadState]=React.useState<'loading'|'ready'|'error'>('loading')
  const loadGeneration=React.useRef(0)
  const sessionIdentity=React.useRef(session?.userId)
  sessionIdentity.current=session?.userId
  const load=React.useCallback(async()=>{const generation=++loadGeneration.current,identity=session?.userId;const current=()=>generation===loadGeneration.current&&identity===sessionIdentity.current;setLoadState('loading');try{const loaded=(await eventApi.list()).map(fromApiEvent);let nextQuick:ApiQuickExpense[]=[],nextIncomes:ApiDirectIncome[]=[],nextWarehouse:DashboardCost[]=[];
      if(session?.role!=='coordinator') {
        const [quick,incomes]=await Promise.all([quickExpenseApi.list(),directIncomeApi.list()]);nextQuick=quick;nextIncomes=incomes
        const [labor,weekly,settlements,legacy]=await Promise.all([payrollApi.list(),weeklyPayrollApi.list(),eventApi.listExpenseSettlements(),weeklyPayrollApi.legacy()]);
        const payrollDates=new Map(weekly.flatMap(batch=>batch.lines.map(line=>[line.id,batch.payments.findLast(payment=>!payment.reversedAt)?.paymentDate] as const)))
        const laborDate=(id:string)=>payrollDates.get(id)
        const cashShares=new Map(labor.map(entry=>[entry.id,allocatePayrollCents(entry.paidAmount,entry.allocations.map(allocation=>allocation.amount))] as const))
        const legacyCashShares=new Map(labor.map(entry=>[entry.id,legacy.settlements.filter(payment=>payment.payrollEntryId===entry.id).map(payment=>({date:payment.paymentDate,shares:allocatePayrollCents(payment.amount,entry.allocations.map(allocation=>allocation.amount))}))] as const))
        const laborCash=(entry:ApiPayroll,index:number)=>cashShares.get(entry.id)?.[index]??0
        const laborPayments=(entry:ApiPayroll,index:number)=>payrollDates.has(entry.id)?undefined:legacyCashShares.get(entry.id)?.map(payment=>({date:payment.date,amount:payment.shares[index]}))
        const payrollUnit=new Map(weekly.flatMap(batch=>batch.lines.map(line=>[line.id,batch.businessUnit] as const)))
        const eventUnits=new Map(loaded.map(event=>[event.id,event.unit] as const))
        const warehouseLabor:DashboardCost[]=labor.flatMap(entry=>entry.allocations.flatMap((allocation,index)=>allocation.scope==='warehouse'?[{id:`labor:${entry.id}:${index}`,name:entry.employeeName,category:'Nómina de almacén',date:entry.periodEnd,amount:Number(allocation.amount),context:'Almacén',kind:'labor' as const,businessUnit:payrollAllocationUnit(allocation,eventUnits,payrollUnit.get(entry.id)),cashDate:laborDate(entry.id),cashAmount:laborCash(entry,index),cashPayments:laborPayments(entry,index)}]:[]))
        const warehouseExtras:DashboardCost[]=weekly.flatMap(batch=>batch.expenses.filter(expense=>expense.scope==='warehouse').map(expense=>({id:`weekly:${batch.id}:${expense.id}`,name:expense.concept,category:expense.category??'Gastos de nómina',date:batch.periodEnd,amount:Number(expense.amount),context:'Almacén',kind:'expense',businessUnit:batch.businessUnit,payrollOrigin:true,notes:expense.notes??null,cashDate:batch.payments.findLast(payment=>!payment.reversedAt)?.paymentDate})))
        nextWarehouse=[...warehouseLabor,...warehouseExtras]
        await Promise.all(loaded.map(async event=>{const [expenses,payments]=await Promise.all([eventApi.listExpenses(event.id),eventApi.listPayments(event.id)]);event.expenses=expenses.map(expense=>({...fromApiExpense(expense),cashDate:expense.source==='payroll'?weekly.find(batch=>batch.id===expense.payrollId)?.payments.findLast(payment=>!payment.reversedAt)?.paymentDate:undefined,cashPayments:expense.source==='payroll'?undefined:settlements.filter(settlement=>settlement.expenseId===expense.id).map(settlement=>({date:settlement.paymentDate,amount:Number(settlement.amount)}))}));event.payments=payments.map(fromApiPayment);event.laborItems=labor.flatMap(entry=>entry.allocations.flatMap((allocation,index)=>allocation.scope==='event'&&allocation.eventId===event.id?[{id:`labor:${entry.id}:${event.id}:${index}`,name:entry.employeeName,category:'Nómina de eventos',date:entry.periodEnd,amount:Number(allocation.amount),context:event.venue,kind:'labor' as const,businessUnit:payrollAllocationUnit(allocation,eventUnits,payrollUnit.get(entry.id)),cashDate:laborDate(entry.id),cashAmount:laborCash(entry,index),cashPayments:laborPayments(entry,index)}]:[]));event.payrollActual=event.laborItems.reduce((sum,item)=>sum+item.amount,0)}))
      }
      if(!current())return;setQuickExpenses(nextQuick);setDirectIncomes(nextIncomes);setWarehouseCosts(nextWarehouse);setEvents(loaded);setSelectedId(selected=>loaded.some(event=>event.id===selected)?selected:(loaded[0]?.id??''));setLoadState('ready')}catch{if(current())setLoadState('error')}},[session?.userId,session?.role])
  React.useEffect(()=>{authApi.me().then(user=>{const visibleUser=user.role==='admin'?{...user,role:'owner' as const}:user;setScope(readScope(visibleUser));setSelectedPeriod(readPeriod(visibleUser));setSession(visibleUser);if(visibleUser.role==='coordinator')setView('events')}).catch(()=>setSession(null))},[])
  React.useEffect(()=>{if(session)void load()},[load,session])
  React.useEffect(()=>{if(session&&session.role!=='coordinator')localStorage.setItem(scopeKey(session),scope)},[scope,session])
  React.useEffect(()=>{if(session)localStorage.setItem(periodKey(session),JSON.stringify(selectedPeriod))},[selectedPeriod,session])
  React.useEffect(()=>{window.scrollTo(0,0)},[view])
  const login=React.useCallback((user:SessionUser)=>{const visibleUser=user.role==='admin'?{...user,role:'owner' as const}:user;setScope(readScope(visibleUser));setSelectedPeriod(readPeriod(visibleUser));setSession(visibleUser);setView(visibleUser.role==='coordinator'?'events':'dashboard')},[])
  const logout=async()=>{loadGeneration.current++;sessionIdentity.current=undefined;try{await authApi.logout()}finally{setSession(null);setEvents([]);setWarehouseCosts([]);setQuickExpenses([]);setDirectIncomes([]);setSelectedId('');setCreating(false);setCreatingExpense(false);setCreatingIncome(false);setView('dashboard')}}
  const saveQuick=async(id:string,input:Pick<ApiQuickExpense,'name'|'category'|'amount'|'expenseDate'|'businessUnit'|'notes'|'paymentMethod'>)=>{const expense=await quickExpenseApi.save(id,input);setQuickExpenses(current=>current.some(item=>item.id===id)?current:[expense,...current])}
  const saveIncome=async(id:string,input:Pick<ApiDirectIncome,'name'|'amount'|'businessUnit'|'expectedDate'|'receivedDate'|'notes'>)=>{const income=await directIncomeApi.save(id,input);setDirectIncomes(current=>current.some(item=>item.id===id)?current:[income,...current])}
  const incomeChanged=(income:ApiDirectIncome|null,id:string)=>setDirectIncomes(current=>income?current.map(item=>item.id===id?income:item):current.filter(item=>item.id!==id))
  const exportMonth=async(month:string)=>{const blob=await reportApi.monthly(month),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`SPL-reporte-${month}.xlsx`;link.click();URL.revokeObjectURL(url)}
  const save=async(event:EventRecord)=>{if(!session)return;const operational:CreateEventInput={businessUnit:event.unit,clientName:event.client,clientPhone:null,venue:event.venue,eventDate:event.date,operationalStatus:'Pendiente',operationalNotes:null};const input:CreateEventInput=session.role!=='coordinator'?{...operational,financialNotes:null,agreedPrice:event.price===null?null:event.price.toFixed(2)}:operational;const created=fromApiEvent(await eventApi.create(input));setEvents(current=>[created,...current]);setSelectedId(created.id);setCreating(false);setView('events')}
  if(session===undefined)return <main className="session-loading" aria-live="polite">Verificando tu sesión...</main>
  if(session===null)return <LoginScreen onLogin={login}/>
  const page=view==='dashboard'&&session.role!=='coordinator'?<Dashboard scope={scope} events={events} warehouseCosts={warehouseCosts} quickExpenses={quickExpenses} directIncomes={directIncomes} selectedPeriod={selectedPeriod} setSelectedPeriod={setSelectedPeriod}/>:view==='finance'&&session.role!=='coordinator'?<FinancePage events={events} scope={scope} quickExpenses={quickExpenses} directIncomes={directIncomes} warehouseCosts={warehouseCosts} selectedPeriod={selectedPeriod} setSelectedPeriod={setSelectedPeriod} onIncomeChanged={incomeChanged}/>:view==='payroll'&&session.role!=='coordinator'?<PayrollPage events={events} scope={scope} onChanged={()=>void load()}/>:view==='settings'?<SettingsPage user={session}/>:<EventsPage events={events} setEvents={setEvents} selectedId={selectedId} setSelectedId={setSelectedId} openCreate={()=>setCreating(true)} loadState={loadState} retry={()=>void load()} role={session.role} scope={scope}/>
  return <div className="app-shell"><Sidebar view={view} setView={setView} mobileNav={mobileNav} close={()=>setMobileNav(false)} user={session} logout={()=>void logout()} scope={scope} setScope={setScope}/><main><header><button className="menu-button" onClick={()=>setMobileNav(true)}><Menu/></button><div className="search"><Search size={18}/><input placeholder="Buscar evento o cliente..."/></div>{session.role!=='coordinator'&&<button className="export" onClick={()=>setExporting(true)}><Download size={17}/>Exportar mes</button>}{session.role!=='coordinator'&&<button className="quick-expense-button" onClick={()=>setCreatingExpense(true)}><Plus size={18}/>Gasto nuevo</button>}{session.role!=='coordinator'&&<button className="quick-income-button" onClick={()=>setCreatingIncome(true)} aria-label="Utilidad nueva" title="Utilidad nueva"><CircleDollarSign size={18}/><span>Utilidad nueva</span></button>}<button className="primary" onClick={()=>setCreating(true)}><Plus size={18}/>Nuevo evento</button></header>{page}</main>{creating&&<CreateEventModal close={()=>setCreating(false)} save={save} count={events.length} role={session.role} defaultUnit={defaultUnit(scope)}/>} {exporting&&<MonthModal close={()=>setExporting(false)} save={exportMonth} defaultMonth={(view==='dashboard'||view==='finance'?selectedPeriod.anchor:todayLocal()).slice(0,7)}/>} {creatingExpense&&<QuickExpenseModal close={()=>setCreatingExpense(false)} save={saveQuick} defaultUnit={defaultUnit(scope)}/>}{creatingIncome&&session.role!=='coordinator'&&<DirectIncomeModal close={()=>setCreatingIncome(false)} save={saveIncome} defaultUnit={defaultUnit(scope)}/>}</div>
}
ReactDOM.createRoot(document.getElementById('app')!).render(<React.StrictMode><App/></React.StrictMode>)
